In [1]:
from pathlib import Path
import pandas as pd

In [2]:
season_df.columns.tolist()

NameError: name 'season_df' is not defined

In [5]:
%whos

Variable   Type      Data/Info
------------------------------
Path       type      <class 'pathlib._local.Path'>
pd         module    <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>

In [ ]:
season_folder = Path("../data/raw/2025 PL Season")

print(season_folder)

..\data\raw\2025 PL Season

In [ ]:
files = list(season_folder.glob("*.xls"))

print(files)

[WindowsPath('../data/raw/2025 PL Season/Premier League home and away .xls'), WindowsPath('../data/raw/2025 PL Season/Premier League Overall.xls'), WindowsPath('../data/raw/2025 PL Season/Squad Goalkeeping 2024-2025 Premier League.xls'), WindowsPath('../data/raw/2025 PL Season/Squad Goalkeeping Opponent.xls'), WindowsPath('../data/raw/2025 PL Season/Squad Miscellaneous Stats 2024-2025 Premier League.xls'), WindowsPath('../data/raw/2025 PL Season/Squad Miscellaneous Stats Opponent.xls'), WindowsPath('../data/raw/2025 PL Season/Squad Playing Time 2024-2025 Premier League.xls'), WindowsPath('../data/raw/2025 PL Season/Squad Playing Time Opponent.xls'), WindowsPath('../data/raw/2025 PL Season/Squad Shooting 2024-2025 Premier League .xls'), WindowsPath('../data/raw/2025 PL Season/Squad Shooting Opponent .xls'), WindowsPath('../data/raw/2025 PL Season/Squad Standard Stats 2024-2025 Premier League opponent stats.xls'), WindowsPath('../data/raw/2025 PL Season/Squad Standard Stats 2024-2025 Premier League.xls')]

In [ ]:
for file in files:
    print(file.name)

Premier League home and away .xls
Premier League Overall.xls
Squad Goalkeeping 2024-2025 Premier League.xls
Squad Goalkeeping Opponent.xls
Squad Miscellaneous Stats 2024-2025 Premier League.xls
Squad Miscellaneous Stats Opponent.xls
Squad Playing Time 2024-2025 Premier League.xls
Squad Playing Time Opponent.xls
Squad Shooting 2024-2025 Premier League .xls
Squad Shooting Opponent .xls
Squad Standard Stats 2024-2025 Premier League opponent stats.xls
Squad Standard Stats 2024-2025 Premier League.xls

In [ ]:
def load_fbref_table(file_path):
    """
    Loads one FBref HTML table stored as a .xls file.
    Returns a Pandas DataFrame.
    """

    tables = pd.read_html(file_path)

    return tables[0]

In [ ]:
overall_df = load_fbref_table(files[0])

overall_df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Home                                   \
                  Rk              Squad   MP   W  D  L  GF  GA  GD Pts Pts/MP
0                  1          Liverpool   19  14  4  1  42  16  26  46   2.42
1                  2            Arsenal   19  11  6  2  35  17  18  39   2.05
2                  3    Manchester City   19  13  3  3  43  23  20  42   2.21
3                  4            Chelsea   19  12  5  2  35  18  17  41   2.16
4                  5          Newcastle   19  12  2  5  40  20  20  38   2.00

  Away
    MP   W  D  L  GF  GA  GD Pts Pts/MP
0   19  11  5  3  44  25  19  38   2.00
1   19   9  8  2  34  17  17  35   1.84
2   19   8  5  6  29  21   8  29   1.53
3   19   8  4  7  29  25   4  28   1.47
4   19   8  4  7  28  27   1  28   1.47

In [ ]:
all_tables = {}

for file in files:
    table_name = file.stem
    all_tables[table_name] = load_fbref_table(file)

print(f"Loaded {len(all_tables)} tables.")

Loaded 12 tables.

In [ ]:
all_tables["Squad Goalkeeping"].head()

KeyError: 'Squad Goalkeeping'

In [ ]:


all_tables.keys()

dict_keys(['Premier League home and away ', 'Premier League Overall', 'Squad Goalkeeping 2024-2025 Premier League', 'Squad Goalkeeping Opponent', 'Squad Miscellaneous Stats 2024-2025 Premier League', 'Squad Miscellaneous Stats Opponent', 'Squad Playing Time 2024-2025 Premier League', 'Squad Playing Time Opponent', 'Squad Shooting 2024-2025 Premier League ', 'Squad Shooting Opponent ', 'Squad Standard Stats 2024-2025 Premier League opponent stats', 'Squad Standard Stats 2024-2025 Premier League'])

In [ ]:
for name, df in all_tables.items():
    print("=" * 60)
    print(name)
    print(df.shape)
    print(df.columns.tolist())
    print()

============================================================
Premier League home and away
(20, 20)
[('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Squad'), ('Home', 'MP'), ('Home', 'W'), ('Home', 'D'), ('Home', 'L'), ('Home', 'GF'), ('Home', 'GA'), ('Home', 'GD'), ('Home', 'Pts'), ('Home', 'Pts/MP'), ('Away', 'MP'), ('Away', 'W'), ('Away', 'D'), ('Away', 'L'), ('Away', 'GF'), ('Away', 'GA'), ('Away', 'GD'), ('Away', 'Pts'), ('Away', 'Pts/MP')]

============================================================
Premier League Overall
(20, 15)
['Rk', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP', 'Attendance', 'Top Team Scorer', 'Goalkeeper', 'Notes']

============================================================
Squad Goalkeeping 2024-2025 Premier League
(20, 21)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'GA'), ('Performance', 'GA90'), ('Performance', 'SoTA'), ('Performance', 'Saves'), ('Performance', 'Save%'), ('Performance', 'W'), ('Performance', 'D'), ('Performance', 'L'), ('Performance', 'CS'), ('Performance', 'CS%'), ('Penalty Kicks', 'PKatt'), ('Penalty Kicks', 'PKA'), ('Penalty Kicks', 'PKsv'), ('Penalty Kicks', 'PKm'), ('Penalty Kicks', 'Save%')]

============================================================
Squad Goalkeeping Opponent
(20, 21)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'GA'), ('Performance', 'GA90'), ('Performance', 'SoTA'), ('Performance', 'Saves'), ('Performance', 'Save%'), ('Performance', 'W'), ('Performance', 'D'), ('Performance', 'L'), ('Performance', 'CS'), ('Performance', 'CS%'), ('Penalty Kicks', 'PKatt'), ('Penalty Kicks', 'PKA'), ('Penalty Kicks', 'PKsv'), ('Penalty Kicks', 'PKm'), ('Penalty Kicks', 'Save%')]

============================================================
Squad Miscellaneous Stats 2024-2025 Premier League
(20, 15)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Performance', '2CrdY'), ('Performance', 'Fls'), ('Performance', 'Fld'), ('Performance', 'Off'), ('Performance', 'Crs'), ('Performance', 'Int'), ('Performance', 'TklW'), ('Performance', 'PKwon'), ('Performance', 'PKcon'), ('Performance', 'OG')]

============================================================
Squad Miscellaneous Stats Opponent
(20, 15)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Performance', '2CrdY'), ('Performance', 'Fls'), ('Performance', 'Fld'), ('Performance', 'Off'), ('Performance', 'Crs'), ('Performance', 'Int'), ('Performance', 'TklW'), ('Performance', 'PKwon'), ('Performance', 'PKcon'), ('Performance', 'OG')]

============================================================
Squad Playing Time 2024-2025 Premier League
(20, 19)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Playing Time', 'MP'), ('Playing Time', 'Min'), ('Playing Time', 'Mn/MP'), ('Playing Time', 'Min%'), ('Playing Time', '90s'), ('Starts', 'Starts'), ('Starts', 'Mn/Start'), ('Starts', 'Compl'), ('Subs', 'Subs'), ('Subs', 'Mn/Sub'), ('Subs', 'unSub'), ('Team Success', 'PPM'), ('Team Success', 'onG'), ('Team Success', 'onGA'), ('Team Success', '+/-'), ('Team Success', '+/-90')]

============================================================
Squad Playing Time Opponent
(20, 19)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Playing Time', 'MP'), ('Playing Time', 'Min'), ('Playing Time', 'Mn/MP'), ('Playing Time', 'Min%'), ('Playing Time', '90s'), ('Starts', 'Starts'), ('Starts', 'Mn/Start'), ('Starts', 'Compl'), ('Subs', 'Subs'), ('Subs', 'Mn/Sub'), ('Subs', 'unSub'), ('Team Success', 'PPM'), ('Team Success', 'onG'), ('Team Success', 'onGA'), ('Team Success', '+/-'), ('Team Success', '+/-90')]

============================================================
Squad Shooting 2024-2025 Premier League
(20, 13)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Standard', 'Gls'), ('Standard', 'Sh'), ('Standard', 'SoT'), ('Standard', 'SoT%'), ('Standard', 'Sh/90'), ('Standard', 'SoT/90'), ('Standard', 'G/Sh'), ('Standard', 'G/SoT'), ('Standard', 'PK'), ('Standard', 'PKatt')]

============================================================
Squad Shooting Opponent
(20, 13)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Standard', 'Gls'), ('Standard', 'Sh'), ('Standard', 'SoT'), ('Standard', 'SoT%'), ('Standard', 'Sh/90'), ('Standard', 'SoT/90'), ('Standard', 'G/Sh'), ('Standard', 'G/SoT'), ('Standard', 'PK'), ('Standard', 'PKatt')]

============================================================
Squad Standard Stats 2024-2025 Premier League opponent stats
(20, 21)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Poss'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'Gls'), ('Performance', 'Ast'), ('Performance', 'G+A'), ('Performance', 'G-PK'), ('Performance', 'PK'), ('Performance', 'PKatt'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'), ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'), ('Per 90 Minutes', 'G+A-PK')]

============================================================
Squad Standard Stats 2024-2025 Premier League
(20, 21)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Poss'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'Gls'), ('Performance', 'Ast'), ('Performance', 'G+A'), ('Performance', 'G-PK'), ('Performance', 'PK'), ('Performance', 'PKatt'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'), ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'), ('Per 90 Minutes', 'G+A-PK')]

In [ ]:
def load_fbref_table(file_path):
    tables = pd.read_html(file_path)
    return tables[0]

all_tables = {}

for file in files:
    table_name = file.stem.strip()
    all_tables[table_name] = load_fbref_table(file)

In [ ]:
print(all_tables.keys())

dict_keys(['Premier League home and away', 'Premier League Overall', 'Squad Goalkeeping 2024-2025 Premier League', 'Squad Goalkeeping Opponent', 'Squad Miscellaneous Stats 2024-2025 Premier League', 'Squad Miscellaneous Stats Opponent', 'Squad Playing Time 2024-2025 Premier League', 'Squad Playing Time Opponent', 'Squad Shooting 2024-2025 Premier League', 'Squad Shooting Opponent', 'Squad Standard Stats 2024-2025 Premier League opponent stats', 'Squad Standard Stats 2024-2025 Premier League'])

In [ ]:
for name, df in all_tables.items():
    print("=" * 60)
    print(name)
    print(df.shape)
    print(df.columns.tolist())
    print()

============================================================
Premier League home and away
(20, 20)
[('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Squad'), ('Home', 'MP'), ('Home', 'W'), ('Home', 'D'), ('Home', 'L'), ('Home', 'GF'), ('Home', 'GA'), ('Home', 'GD'), ('Home', 'Pts'), ('Home', 'Pts/MP'), ('Away', 'MP'), ('Away', 'W'), ('Away', 'D'), ('Away', 'L'), ('Away', 'GF'), ('Away', 'GA'), ('Away', 'GD'), ('Away', 'Pts'), ('Away', 'Pts/MP')]

============================================================
Premier League Overall
(20, 15)
['Rk', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP', 'Attendance', 'Top Team Scorer', 'Goalkeeper', 'Notes']

============================================================
Squad Goalkeeping 2024-2025 Premier League
(20, 21)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'GA'), ('Performance', 'GA90'), ('Performance', 'SoTA'), ('Performance', 'Saves'), ('Performance', 'Save%'), ('Performance', 'W'), ('Performance', 'D'), ('Performance', 'L'), ('Performance', 'CS'), ('Performance', 'CS%'), ('Penalty Kicks', 'PKatt'), ('Penalty Kicks', 'PKA'), ('Penalty Kicks', 'PKsv'), ('Penalty Kicks', 'PKm'), ('Penalty Kicks', 'Save%')]

============================================================
Squad Goalkeeping Opponent
(20, 21)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'GA'), ('Performance', 'GA90'), ('Performance', 'SoTA'), ('Performance', 'Saves'), ('Performance', 'Save%'), ('Performance', 'W'), ('Performance', 'D'), ('Performance', 'L'), ('Performance', 'CS'), ('Performance', 'CS%'), ('Penalty Kicks', 'PKatt'), ('Penalty Kicks', 'PKA'), ('Penalty Kicks', 'PKsv'), ('Penalty Kicks', 'PKm'), ('Penalty Kicks', 'Save%')]

============================================================
Squad Miscellaneous Stats 2024-2025 Premier League
(20, 15)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Performance', '2CrdY'), ('Performance', 'Fls'), ('Performance', 'Fld'), ('Performance', 'Off'), ('Performance', 'Crs'), ('Performance', 'Int'), ('Performance', 'TklW'), ('Performance', 'PKwon'), ('Performance', 'PKcon'), ('Performance', 'OG')]

============================================================
Squad Miscellaneous Stats Opponent
(20, 15)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Performance', '2CrdY'), ('Performance', 'Fls'), ('Performance', 'Fld'), ('Performance', 'Off'), ('Performance', 'Crs'), ('Performance', 'Int'), ('Performance', 'TklW'), ('Performance', 'PKwon'), ('Performance', 'PKcon'), ('Performance', 'OG')]

============================================================
Squad Playing Time 2024-2025 Premier League
(20, 19)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Playing Time', 'MP'), ('Playing Time', 'Min'), ('Playing Time', 'Mn/MP'), ('Playing Time', 'Min%'), ('Playing Time', '90s'), ('Starts', 'Starts'), ('Starts', 'Mn/Start'), ('Starts', 'Compl'), ('Subs', 'Subs'), ('Subs', 'Mn/Sub'), ('Subs', 'unSub'), ('Team Success', 'PPM'), ('Team Success', 'onG'), ('Team Success', 'onGA'), ('Team Success', '+/-'), ('Team Success', '+/-90')]

============================================================
Squad Playing Time Opponent
(20, 19)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Playing Time', 'MP'), ('Playing Time', 'Min'), ('Playing Time', 'Mn/MP'), ('Playing Time', 'Min%'), ('Playing Time', '90s'), ('Starts', 'Starts'), ('Starts', 'Mn/Start'), ('Starts', 'Compl'), ('Subs', 'Subs'), ('Subs', 'Mn/Sub'), ('Subs', 'unSub'), ('Team Success', 'PPM'), ('Team Success', 'onG'), ('Team Success', 'onGA'), ('Team Success', '+/-'), ('Team Success', '+/-90')]

============================================================
Squad Shooting 2024-2025 Premier League
(20, 13)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Standard', 'Gls'), ('Standard', 'Sh'), ('Standard', 'SoT'), ('Standard', 'SoT%'), ('Standard', 'Sh/90'), ('Standard', 'SoT/90'), ('Standard', 'G/Sh'), ('Standard', 'G/SoT'), ('Standard', 'PK'), ('Standard', 'PKatt')]

============================================================
Squad Shooting Opponent
(20, 13)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Standard', 'Gls'), ('Standard', 'Sh'), ('Standard', 'SoT'), ('Standard', 'SoT%'), ('Standard', 'Sh/90'), ('Standard', 'SoT/90'), ('Standard', 'G/Sh'), ('Standard', 'G/SoT'), ('Standard', 'PK'), ('Standard', 'PKatt')]

============================================================
Squad Standard Stats 2024-2025 Premier League opponent stats
(20, 21)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Poss'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'Gls'), ('Performance', 'Ast'), ('Performance', 'G+A'), ('Performance', 'G-PK'), ('Performance', 'PK'), ('Performance', 'PKatt'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'), ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'), ('Per 90 Minutes', 'G+A-PK')]

============================================================
Squad Standard Stats 2024-2025 Premier League
(20, 21)
[('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Poss'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'Gls'), ('Performance', 'Ast'), ('Performance', 'G+A'), ('Performance', 'G-PK'), ('Performance', 'PK'), ('Performance', 'PKatt'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'), ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'), ('Per 90 Minutes', 'G+A-PK')]

In [ ]:
for name, df in all_tables.items():
    print("=" * 80)
    print(name)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print()

================================================================================
Premier League home and away
Shape: (20, 20)
Columns: [('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Squad'), ('Home', 'MP'), ('Home', 'W'), ('Home', 'D'), ('Home', 'L'), ('Home', 'GF'), ('Home', 'GA'), ('Home', 'GD'), ('Home', 'Pts'), ('Home', 'Pts/MP'), ('Away', 'MP'), ('Away', 'W'), ('Away', 'D'), ('Away', 'L'), ('Away', 'GF'), ('Away', 'GA'), ('Away', 'GD'), ('Away', 'Pts'), ('Away', 'Pts/MP')]

================================================================================
Premier League Overall
Shape: (20, 15)
Columns: ['Rk', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP', 'Attendance', 'Top Team Scorer', 'Goalkeeper', 'Notes']

================================================================================
Squad Goalkeeping 2024-2025 Premier League
Shape: (20, 21)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'GA'), ('Performance', 'GA90'), ('Performance', 'SoTA'), ('Performance', 'Saves'), ('Performance', 'Save%'), ('Performance', 'W'), ('Performance', 'D'), ('Performance', 'L'), ('Performance', 'CS'), ('Performance', 'CS%'), ('Penalty Kicks', 'PKatt'), ('Penalty Kicks', 'PKA'), ('Penalty Kicks', 'PKsv'), ('Penalty Kicks', 'PKm'), ('Penalty Kicks', 'Save%')]

================================================================================
Squad Goalkeeping Opponent
Shape: (20, 21)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'GA'), ('Performance', 'GA90'), ('Performance', 'SoTA'), ('Performance', 'Saves'), ('Performance', 'Save%'), ('Performance', 'W'), ('Performance', 'D'), ('Performance', 'L'), ('Performance', 'CS'), ('Performance', 'CS%'), ('Penalty Kicks', 'PKatt'), ('Penalty Kicks', 'PKA'), ('Penalty Kicks', 'PKsv'), ('Penalty Kicks', 'PKm'), ('Penalty Kicks', 'Save%')]

================================================================================
Squad Miscellaneous Stats 2024-2025 Premier League
Shape: (20, 15)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Performance', '2CrdY'), ('Performance', 'Fls'), ('Performance', 'Fld'), ('Performance', 'Off'), ('Performance', 'Crs'), ('Performance', 'Int'), ('Performance', 'TklW'), ('Performance', 'PKwon'), ('Performance', 'PKcon'), ('Performance', 'OG')]

================================================================================
Squad Miscellaneous Stats Opponent
Shape: (20, 15)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Performance', '2CrdY'), ('Performance', 'Fls'), ('Performance', 'Fld'), ('Performance', 'Off'), ('Performance', 'Crs'), ('Performance', 'Int'), ('Performance', 'TklW'), ('Performance', 'PKwon'), ('Performance', 'PKcon'), ('Performance', 'OG')]

================================================================================
Squad Playing Time 2024-2025 Premier League
Shape: (20, 19)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Playing Time', 'MP'), ('Playing Time', 'Min'), ('Playing Time', 'Mn/MP'), ('Playing Time', 'Min%'), ('Playing Time', '90s'), ('Starts', 'Starts'), ('Starts', 'Mn/Start'), ('Starts', 'Compl'), ('Subs', 'Subs'), ('Subs', 'Mn/Sub'), ('Subs', 'unSub'), ('Team Success', 'PPM'), ('Team Success', 'onG'), ('Team Success', 'onGA'), ('Team Success', '+/-'), ('Team Success', '+/-90')]

================================================================================
Squad Playing Time Opponent
Shape: (20, 19)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Playing Time', 'MP'), ('Playing Time', 'Min'), ('Playing Time', 'Mn/MP'), ('Playing Time', 'Min%'), ('Playing Time', '90s'), ('Starts', 'Starts'), ('Starts', 'Mn/Start'), ('Starts', 'Compl'), ('Subs', 'Subs'), ('Subs', 'Mn/Sub'), ('Subs', 'unSub'), ('Team Success', 'PPM'), ('Team Success', 'onG'), ('Team Success', 'onGA'), ('Team Success', '+/-'), ('Team Success', '+/-90')]

================================================================================
Squad Shooting 2024-2025 Premier League
Shape: (20, 13)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Standard', 'Gls'), ('Standard', 'Sh'), ('Standard', 'SoT'), ('Standard', 'SoT%'), ('Standard', 'Sh/90'), ('Standard', 'SoT/90'), ('Standard', 'G/Sh'), ('Standard', 'G/SoT'), ('Standard', 'PK'), ('Standard', 'PKatt')]

================================================================================
Squad Shooting Opponent
Shape: (20, 13)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Standard', 'Gls'), ('Standard', 'Sh'), ('Standard', 'SoT'), ('Standard', 'SoT%'), ('Standard', 'Sh/90'), ('Standard', 'SoT/90'), ('Standard', 'G/Sh'), ('Standard', 'G/SoT'), ('Standard', 'PK'), ('Standard', 'PKatt')]

================================================================================
Squad Standard Stats 2024-2025 Premier League opponent stats
Shape: (20, 21)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Poss'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'Gls'), ('Performance', 'Ast'), ('Performance', 'G+A'), ('Performance', 'G-PK'), ('Performance', 'PK'), ('Performance', 'PKatt'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'), ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'), ('Per 90 Minutes', 'G+A-PK')]

================================================================================
Squad Standard Stats 2024-2025 Premier League
Shape: (20, 21)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Poss'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'Gls'), ('Performance', 'Ast'), ('Performance', 'G+A'), ('Performance', 'G-PK'), ('Performance', 'PK'), ('Performance', 'PKatt'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'), ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'), ('Per 90 Minutes', 'G+A-PK')]

In [ ]:
def flatten_fbref_columns(df):
    df = df.copy()
    df.columns = [
        "_".join([str(x) for x in col if "Unnamed" not in str(x)]).strip("_")
        if isinstance(col, tuple)
        else str(col).strip()
        for col in df.columns
    ]
    return df

In [ ]:
standard_df = flatten_fbref_columns(all_tables["Squad Standard Stats 2024-2025 Premier League"])
standard_df.head()

,Squad,# Pl,Age,Poss,Playing Time_MP,Playing Time_Starts,Playing Time_Min,Playing Time_90s,Performance_Gls,Performance_Ast,...,Performance_G-PK,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Per 90 Minutes_G+A,Per 90 Minutes_G-PK,Per 90 Minutes_G+A-PK
0,Arsenal,25,25.8,56.9,38,418,3420,38.0,67,55,...,65,2,2,70,6,1.76,1.45,3.21,1.71,3.16
1,Aston Villa,28,27.0,50.5,38,418,3420,38.0,56,45,...,53,3,6,76,4,1.47,1.18,2.66,1.39,2.58
2,Bournemouth,29,25.1,48.5,38,418,3420,38.0,57,41,...,51,6,7,97,3,1.50,1.08,2.58,1.34,2.42
3,Brentford,28,25.8,47.9,38,418,3420,38.0,65,44,...,60,5,6,62,1,1.71,1.16,2.87,1.58,2.74
4,Brighton,32,24.8,52.3,38,418,3420,38.0,64,41,...,57,7,7,78,3,1.68,1.08,2.76,1.50,2.58

In [ ]:
all_tables["Squad Shooting 2024-2025 Premier League"].head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Standard            \
               Squad               # Pl                90s      Gls   Sh  SoT
0            Arsenal                 25               38.0       67  544  178
1        Aston Villa                 28               38.0       56  478  159
2        Bournemouth                 29               38.0       57  574  192
3          Brentford                 28               38.0       65  434  173
4           Brighton                 32               38.0       64  526  183


   SoT%  Sh/90 SoT/90  G/Sh G/SoT PK PKatt
0  32.7  14.32   4.68  0.12  0.37  2     2
1  33.3  12.58   4.18  0.11  0.33  3     6
2  33.4  15.11   5.05  0.09  0.27  6     7
3  39.9  11.42   4.55  0.14  0.35  5     6
4  34.8  13.84   4.82  0.11  0.31  7     7

In [ ]:
all_tables["Squad Standard Stats 2024-2025 Premier League"].head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
               Squad               # Pl                Age               Poss
0            Arsenal                 25               25.8               56.9
1        Aston Villa                 28               27.0               50.5
2        Bournemouth                 29               25.1               48.5
3          Brentford                 28               25.8               47.9
4           Brighton                 32               24.8               52.3

  Playing Time                    Performance      ...                     \
            MP Starts   Min   90s         Gls Ast  ... G-PK PK PKatt CrdY
0           38    418  3420  38.0          67  55  ...   65  2     2   70
1           38    418  3420  38.0          56  45  ...   53  3     6   76
2           38    418  3420  38.0          57  41  ...   51  6     7   97
3           38    418  3420  38.0          65  44  ...   60  5     6   62
4           38    418  3420  38.0          64  41  ...   57  7     7   78

       Per 90 Minutes
  CrdR            Gls   Ast   G+A  G-PK G+A-PK
0    6           1.76  1.45  3.21  1.71   3.16
1    4           1.47  1.18  2.66  1.39   2.58
2    3           1.50  1.08  2.58  1.34   2.42
3    1           1.71  1.16  2.87  1.58   2.74
4    3           1.68  1.08  2.76  1.50   2.58

[5 rows x 21 columns]

In [ ]:
def flatten_fbref_columns(df):
    df = df.copy()
    df.columns = [
        "_".join([str(x) for x in col if "Unnamed" not in str(x)]).strip("_")
        if isinstance(col, tuple)
        else str(col).strip()
        for col in df.columns
    ]
    return df

In [ ]:
def clean_column_names(df):
    df = df.copy()
    df.columns = df.columns.str.replace(r"\s+", "_", regex=True)
    df.columns = df.columns.str.replace(r"_+", "_", regex=True)
    df.columns = df.columns.str.strip("_")
    return df

In [ ]:
standard_df = flatten_fbref_columns(all_tables["Squad Standard Stats 2024-2025 Premier League"])
standard_df = clean_column_names(standard_df)
standard_df.head()

,Squad,#_Pl,Age,Poss,Playing_Time_MP,Playing_Time_Starts,Playing_Time_Min,Playing_Time_90s,Performance_Gls,Performance_Ast,...,Performance_G-PK,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,Per_90_Minutes_Gls,Per_90_Minutes_Ast,Per_90_Minutes_G+A,Per_90_Minutes_G-PK,Per_90_Minutes_G+A-PK
0,Arsenal,25,25.8,56.9,38,418,3420,38.0,67,55,...,65,2,2,70,6,1.76,1.45,3.21,1.71,3.16
1,Aston Villa,28,27.0,50.5,38,418,3420,38.0,56,45,...,53,3,6,76,4,1.47,1.18,2.66,1.39,2.58
2,Bournemouth,29,25.1,48.5,38,418,3420,38.0,57,41,...,51,6,7,97,3,1.50,1.08,2.58,1.34,2.42
3,Brentford,28,25.8,47.9,38,418,3420,38.0,65,44,...,60,5,6,62,1,1.71,1.16,2.87,1.58,2.74
4,Brighton,32,24.8,52.3,38,418,3420,38.0,64,41,...,57,7,7,78,3,1.68,1.08,2.76,1.50,2.58

In [ ]:
standard_df = standard_df.rename(columns={"#_Pl": "Players_Used"})

In [ ]:
shooting_df = flatten_fbref_columns(all_tables["Squad Shooting 2024-2025 Premier League"])
shooting_df = clean_column_names(shooting_df)

shooting_df = shooting_df.rename(columns={"#_Pl": "Players_Used"})
shooting_df.head()

,Squad,Players_Used,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,Standard_Sh/90,Standard_SoT/90,Standard_G/Sh,Standard_G/SoT,Standard_PK,Standard_PKatt
0,Arsenal,25,38.0,67,544,178,32.7,14.32,4.68,0.12,0.37,2,2
1,Aston Villa,28,38.0,56,478,159,33.3,12.58,4.18,0.11,0.33,3,6
2,Bournemouth,29,38.0,57,574,192,33.4,15.11,5.05,0.09,0.27,6,7
3,Brentford,28,38.0,65,434,173,39.9,11.42,4.55,0.14,0.35,5,6
4,Brighton,32,38.0,64,526,183,34.8,13.84,4.82,0.11,0.31,7,7

In [ ]:
shooting_df.shape
shooting_df.columns.tolist()

['Squad',
 'Players_Used',
 '90s',
 'Standard_Gls',
 'Standard_Sh',
 'Standard_SoT',
 'Standard_SoT%',
 'Standard_Sh/90',
 'Standard_SoT/90',
 'Standard_G/Sh',
 'Standard_G/SoT',
 'Standard_PK',
 'Standard_PKatt']

In [ ]:
shooting_df = flatten_fbref_columns(all_tables["Squad Shooting 2024-2025 Premier League"])
shooting_df = clean_column_names(shooting_df)

shooting_df = shooting_df.rename(columns={
    "#_Pl": "Players_Used",
    "Standard_Gls": "Shooting_Gls",
    "Standard_Sh": "Shooting_Sh",
    "Standard_SoT": "Shooting_SoT",
    "Standard_SoT%": "Shooting_SoT_pct",
    "Standard_Sh/90": "Shooting_Sh_per_90",
    "Standard_SoT/90": "Shooting_SoT_per_90",
    "Standard_G/Sh": "Shooting_G_per_Sh",
    "Standard_G/SoT": "Shooting_G_per_SoT",
    "Standard_PK": "Shooting_PK",
    "Standard_PKatt": "Shooting_PKatt",
})

shooting_df.head()

,Squad,Players_Used,90s,Shooting_Gls,Shooting_Sh,Shooting_SoT,Shooting_SoT_pct,Shooting_Sh_per_90,Shooting_SoT_per_90,Shooting_G_per_Sh,Shooting_G_per_SoT,Shooting_PK,Shooting_PKatt
0,Arsenal,25,38.0,67,544,178,32.7,14.32,4.68,0.12,0.37,2,2
1,Aston Villa,28,38.0,56,478,159,33.3,12.58,4.18,0.11,0.33,3,6
2,Bournemouth,29,38.0,57,574,192,33.4,15.11,5.05,0.09,0.27,6,7
3,Brentford,28,38.0,65,434,173,39.9,11.42,4.55,0.14,0.35,5,6
4,Brighton,32,38.0,64,526,183,34.8,13.84,4.82,0.11,0.31,7,7

In [ ]:
goalkeeping_df = flatten_fbref_columns(all_tables["Squad Goalkeeping 2024-2025 Premier League"])
goalkeeping_df = clean_column_names(goalkeeping_df)

goalkeeping_df = goalkeeping_df.rename(columns={
    "#_Pl": "Players_Used",
    "Playing_Time_MP": "GK_MP",
    "Playing_Time_Starts": "GK_Starts",
    "Playing_Time_Min": "GK_Min",
    "Playing_Time_90s": "GK_90s",
    "Performance_GA": "GK_GA",
    "Performance_GA90": "GK_GA90",
    "Performance_SoTA": "GK_SoTA",
    "Performance_Saves": "GK_Saves",
    "Performance_Save%": "GK_Save_pct",
    "Performance_W": "GK_W",
    "Performance_D": "GK_D",
    "Performance_L": "GK_L",
    "Performance_CS": "GK_CS",
    "Performance_CS%": "GK_CS_pct",
    "Penalty_Kicks_PKatt": "GK_PKatt",
    "Penalty_Kicks_PKA": "GK_PKA",
    "Penalty_Kicks_PKsv": "GK_PKsv",
    "Penalty_Kicks_PKm": "GK_PKm",
    "Penalty_Kicks_Save%": "GK_Pen_Save_pct",
})

goalkeeping_df.head()

,Squad,Players_Used,GK_MP,GK_Starts,GK_Min,GK_90s,GK_GA,GK_GA90,GK_SoTA,GK_Saves,...,GK_W,GK_D,GK_L,GK_CS,GK_CS_pct,GK_PKatt,GK_PKA,GK_PKsv,GK_PKm,GK_Pen_Save_pct
0,Arsenal,1,38,38,3420,38.0,34,0.89,120,86,...,20,14,4,13,34.2,3,3,0,0,0.0
1,Aston Villa,2,38,38,3420,38.0,51,1.34,156,104,...,19,9,10,9,23.7,3,2,1,0,33.3
2,Bournemouth,3,38,38,3420,38.0,46,1.21,172,126,...,15,11,12,9,23.7,4,4,0,0,0.0
3,Brentford,2,38,38,3420,38.0,57,1.50,207,153,...,16,8,14,8,21.1,1,1,0,0,0.0
4,Brighton,2,38,38,3420,38.0,59,1.55,147,90,...,16,13,9,8,21.1,9,9,0,0,0.0

In [ ]:
goalkeeping_df.columns.tolist()

['Squad',
 'Players_Used',
 'GK_MP',
 'GK_Starts',
 'GK_Min',
 'GK_90s',
 'GK_GA',
 'GK_GA90',
 'GK_SoTA',
 'GK_Saves',
 'GK_Save_pct',
 'GK_W',
 'GK_D',
 'GK_L',
 'GK_CS',
 'GK_CS_pct',
 'GK_PKatt',
 'GK_PKA',
 'GK_PKsv',
 'GK_PKm',
 'GK_Pen_Save_pct']

In [ ]:
playing_time_df = flatten_fbref_columns(all_tables["Squad Playing Time 2024-2025 Premier League"])
playing_time_df = clean_column_names(playing_time_df)

playing_time_df = playing_time_df.rename(columns={
    "#_Pl": "Players_Used",
    "Age": "Avg_Age",
    "Playing_Time_MP": "PT_MP",
    "Playing_Time_Starts": "PT_Starts",
    "Playing_Time_Min": "PT_Min",
    "Playing_Time_Mn/MP": "PT_Min_per_MP",
    "Playing_Time_Min%": "PT_Min_pct",
    "Playing_Time_90s": "PT_90s",
    "Playing_Time_Mn/Start": "PT_Min_per_Start",
    "Playing_Time_Compl": "PT_Compl",
    "Playing_Time_Subs": "PT_Subs",
    "Playing_Time_Mn/Sub": "PT_Min_per_Sub",
    "Playing_Time_unSub": "PT_unSub",
    "Team_Success_PPM": "PT_Points_Per_Match",
    "Team_Success_onG": "PT_onG",
    "Team_Success_onGA": "PT_onGA",
    "Team_Success_+/-": "PT_Goal_Diff",
})

playing_time_df.head()

,Squad,Players_Used,Avg_Age,PT_MP,PT_Min,PT_Min_per_MP,PT_Min_pct,PT_90s,Starts_Starts,Starts_Mn/Start,Starts_Compl,Subs_Subs,Subs_Mn/Sub,Subs_unSub,PT_Points_Per_Match,PT_onG,PT_onGA,PT_Goal_Diff,Team_Success_+/-90
0,Arsenal,25,25.8,38,3420,90,100,38.0,418,83,272,142,18,200,1.95,69,34,35,0.92
1,Aston Villa,28,27.0,38,3420,90,100,38.0,418,80,246,170,23,170,1.74,58,51,7,0.18
2,Bournemouth,29,25.1,38,3420,90,100,38.0,418,83,254,162,18,180,1.47,58,46,12,0.32
3,Brentford,28,25.8,38,3420,90,100,38.0,418,85,277,142,15,200,1.47,66,57,9,0.24
4,Brighton,32,24.8,38,3420,90,100,38.0,418,82,231,184,18,158,1.61,66,59,7,0.18

In [ ]:
playing_time_df.columns.tolist()

['Squad',
 'Players_Used',
 'Avg_Age',
 'PT_MP',
 'PT_Min',
 'PT_Min_per_MP',
 'PT_Min_pct',
 'PT_90s',
 'Starts_Starts',
 'Starts_Mn/Start',
 'Starts_Compl',
 'Subs_Subs',
 'Subs_Mn/Sub',
 'Subs_unSub',
 'PT_Points_Per_Match',
 'PT_onG',
 'PT_onGA',
 'PT_Goal_Diff',
 'Team_Success_+/-90']

In [ ]:
playing_time_df = playing_time_df.rename(columns={
    "Starts_Starts": "PT_Starts",
    "Starts_Mn/Start": "PT_Min_per_Start",
    "Starts_Compl": "PT_Compl",
    "Subs_Subs": "PT_Subs",
    "Subs_Mn/Sub": "PT_Min_per_Sub",
    "Subs_unSub": "PT_Unused_Sub",
    "Team_Success_+/-90": "PT_Goal_Diff_per_90",
})

In [ ]:
misc_df = flatten_fbref_columns(all_tables["Squad Miscellaneous Stats 2024-2025 Premier League"])
misc_df = clean_column_names(misc_df)

misc_df = misc_df.rename(columns={
    "#_Pl": "Players_Used",
    "Performance_CrdY": "Misc_CrdY",
    "Performance_CrdR": "Misc_CrdR",
    "Performance_2CrdY": "Misc_2CrdY",
    "Performance_Fls": "Misc_Fls",
    "Performance_Fld": "Misc_Fld",
    "Performance_Off": "Misc_Off",
    "Performance_Crs": "Misc_Crs",
    "Performance_Int": "Misc_Int",
    "Performance_TklW": "Misc_TklW",
    "Performance_PKwon": "Misc_PKwon",
    "Performance_PKcon": "Misc_PKcon",
    "Performance_OG": "Misc_OG",
})

misc_df.head()

,Squad,Players_Used,90s,Misc_CrdY,Misc_CrdR,Misc_2CrdY,Misc_Fls,Misc_Fld,Misc_Off,Misc_Crs,Misc_Int,Misc_TklW,Misc_PKwon,Misc_PKcon,Misc_OG
0,Arsenal,25,38.0,70,6,3,401,405,80,766,225,348,2,3,0
1,Aston Villa,28,38.0,76,4,2,406,499,55,604,240,372,6,3,0
2,Bournemouth,29,38.0,97,3,0,525,400,70,832,351,399,7,4,0
3,Brentford,28,38.0,62,1,0,320,339,63,674,285,380,6,1,3
4,Brighton,32,38.0,78,3,2,438,411,46,704,315,431,6,9,2

In [ ]:
misc_df.columns.tolist()

['Squad',
 'Players_Used',
 '90s',
 'Misc_CrdY',
 'Misc_CrdR',
 'Misc_2CrdY',
 'Misc_Fls',
 'Misc_Fld',
 'Misc_Off',
 'Misc_Crs',
 'Misc_Int',
 'Misc_TklW',
 'Misc_PKwon',
 'Misc_PKcon',
 'Misc_OG']

In [ ]:
misc_df = misc_df.rename(columns={
    "90s": "Misc_90s"
})

In [ ]:
home_away_df = flatten_fbref_columns(all_tables["Premier League home and away"])
home_away_df = clean_column_names(home_away_df)
home_away_df.head()

,Rk,Squad,Home_MP,Home_W,Home_D,Home_L,Home_GF,Home_GA,Home_GD,Home_Pts,Home_Pts/MP,Away_MP,Away_W,Away_D,Away_L,Away_GF,Away_GA,Away_GD,Away_Pts,Away_Pts/MP
0,1,Liverpool,19,14,4,1,42,16,26,46,2.42,19,11,5,3,44,25,19,38,2.00
1,2,Arsenal,19,11,6,2,35,17,18,39,2.05,19,9,8,2,34,17,17,35,1.84
2,3,Manchester City,19,13,3,3,43,23,20,42,2.21,19,8,5,6,29,21,8,29,1.53
3,4,Chelsea,19,12,5,2,35,18,17,41,2.16,19,8,4,7,29,25,4,28,1.47
4,5,Newcastle,19,12,2,5,40,20,20,38,2.00,19,8,4,7,28,27,1,28,1.47

In [ ]:
home_away_df.columns.tolist()

['Rk',
 'Squad',
 'Home_MP',
 'Home_W',
 'Home_D',
 'Home_L',
 'Home_GF',
 'Home_GA',
 'Home_GD',
 'Home_Pts',
 'Home_Pts/MP',
 'Away_MP',
 'Away_W',
 'Away_D',
 'Away_L',
 'Away_GF',
 'Away_GA',
 'Away_GD',
 'Away_Pts',
 'Away_Pts/MP']

In [ ]:
season_df = overall_df
season_df = season_df.merge(standard_df, on="Squad", how="left")
season_df = season_df.merge(shooting_df, on="Squad", how="left")
season_df = season_df.merge(goalkeeping_df, on="Squad", how="left")
season_df = season_df.merge(playing_time_df, on="Squad", how="left")
season_df = season_df.merge(misc_df, on="Squad", how="left")
season_df = season_df.merge(home_away_df, on="Squad", how="left")

MergeError: Not allowed to merge between different levels. (2 levels on the left, 1 on the right)

In [ ]:
season_df = overall_df.merge(standard_df, on="Squad", how="left")

MergeError: Not allowed to merge between different levels. (2 levels on the left, 1 on the right)

In [ ]:
print(type(overall_df.columns))

<class 'pandas.MultiIndex'>

In [ ]:
print(type(standard_df.columns))

<class 'pandas.Index'>

In [ ]:
print(overall_df.columns)

MultiIndex([('Unnamed: 0_level_0',     'Rk'),
            ('Unnamed: 1_level_0',  'Squad'),
            (              'Home',     'MP'),
            (              'Home',      'W'),
            (              'Home',      'D'),
            (              'Home',      'L'),
            (              'Home',     'GF'),
            (              'Home',     'GA'),
            (              'Home',     'GD'),
            (              'Home',    'Pts'),
            (              'Home', 'Pts/MP'),
            (              'Away',     'MP'),
            (              'Away',      'W'),
            (              'Away',      'D'),
            (              'Away',      'L'),
            (              'Away',     'GF'),
            (              'Away',     'GA'),
            (              'Away',     'GD'),
            (              'Away',    'Pts'),
            (              'Away', 'Pts/MP')],
           )

In [ ]:
for name, df in [
    ("overall", overall_df),
    ("standard", standard_df),
    ("shooting", shooting_df),
    ("goalkeeping", goalkeeping_df),
    ("playing_time", playing_time_df),
    ("misc", misc_df),
    ("home_away", home_away_df),
]:
    print(name, type(df.columns))

overall <class 'pandas.MultiIndex'>
standard <class 'pandas.Index'>
shooting <class 'pandas.Index'>
goalkeeping <class 'pandas.Index'>
playing_time <class 'pandas.Index'>
misc <class 'pandas.Index'>
home_away <class 'pandas.Index'>

In [ ]:
overall_df = all_tables["Premier League Overall"].copy()

overall_df = clean_column_names(overall_df)

overall_df.head()

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top_Team_Scorer,Goalkeeper,Notes
0,1,Liverpool,38,25,9,4,86,41,45,84,2.21,60324,Mohamed Salah - 29,Alisson,â Champions League via league finish
1,2,Arsenal,38,20,14,4,69,34,35,74,1.95,60251,Kai Havertz - 9,David Raya,â Champions League via league finish
2,3,Manchester City,38,21,8,9,72,44,28,71,1.87,52756,Erling Haaland - 22,Ederson Moraes,â Champions League via league finish
3,4,Chelsea,38,20,9,9,64,43,21,69,1.82,39672,Cole Palmer - 15,Robert SÃ¡nchez,â Champions League via league finish
4,5,Newcastle,38,20,6,12,68,47,21,66,1.74,52187,Alexander Isak - 23,Nick Pope,â Champions League via league finish

In [ ]:
print(type(overall_df.columns))
print(overall_df.columns)

<class 'pandas.Index'>
Index(['Rk', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP',
       'Attendance', 'Top_Team_Scorer', 'Goalkeeper', 'Notes'],
      dtype='str')

In [ ]:
season_df = overall_df.merge(
    standard_df,
    on="Squad",
    how="left"
)

print(season_df.shape)
season_df.head()

(20, 35)

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,...,Performance_G-PK,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,Per_90_Minutes_Gls,Per_90_Minutes_Ast,Per_90_Minutes_G+A,Per_90_Minutes_G-PK,Per_90_Minutes_G+A-PK
0,1,Liverpool,38,25,9,4,86,41,45,84,...,76,9,9,67,3,2.24,1.71,3.95,2.00,3.71
1,2,Arsenal,38,20,14,4,69,34,35,74,...,65,2,2,70,6,1.76,1.45,3.21,1.71,3.16
2,3,Manchester City,38,21,8,9,72,44,28,71,...,68,3,4,59,2,1.87,1.34,3.21,1.79,3.13
3,4,Chelsea,38,20,9,9,64,43,21,69,...,57,4,5,101,2,1.61,1.24,2.84,1.50,2.74
4,5,Newcastle,38,20,6,12,68,47,21,66,...,61,5,6,68,1,1.74,1.32,3.05,1.61,2.92

In [ ]:
season_df.columns.tolist()

['Rk',
 'Squad',
 'MP',
 'W',
 'D',
 'L',
 'GF',
 'GA',
 'GD',
 'Pts',
 'Pts/MP',
 'Attendance',
 'Top_Team_Scorer',
 'Goalkeeper',
 'Notes',
 'Players_Used',
 'Age',
 'Poss',
 'Playing_Time_MP',
 'Playing_Time_Starts',
 'Playing_Time_Min',
 'Playing_Time_90s',
 'Performance_Gls',
 'Performance_Ast',
 'Performance_G+A',
 'Performance_G-PK',
 'Performance_PK',
 'Performance_PKatt',
 'Performance_CrdY',
 'Performance_CrdR',
 'Per_90_Minutes_Gls',
 'Per_90_Minutes_Ast',
 'Per_90_Minutes_G+A',
 'Per_90_Minutes_G-PK',
 'Per_90_Minutes_G+A-PK']

In [7]:
all_tables.keys()

NameError: name 'all_tables' is not defined

In [9]:
from pathlib import Path

season_path = Path(r"C:\Users\karab\PremierLeagueML\2025 PL Season")

list(season_path.iterdir())

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\karab\\PremierLeagueML\\2025 PL Season'

In [10]:
from pathlib import Path

list(Path(r"C:\Users\karab").glob("**/PremierLeagueML"))

KeyboardInterrupt:

In [11]:
from pathlib import Path
import pandas as pd

season_path = Path(
    r"C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season"
)

print(season_path)
print(season_path.exists())

C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season
True

In [12]:
files = list(season_path.glob("*.xls"))

print("Number of files:", len(files))

for file in files:
    print(file.name)

Number of files: 12
Premier League home and away .xls
Premier League Overall.xls
Squad Goalkeeping 2024-2025 Premier League.xls
Squad Goalkeeping Opponent.xls
Squad Miscellaneous Stats 2024-2025 Premier League.xls
Squad Miscellaneous Stats Opponent.xls
Squad Playing Time 2024-2025 Premier League.xls
Squad Playing Time Opponent.xls
Squad Shooting 2024-2025 Premier League .xls
Squad Shooting Opponent .xls
Squad Standard Stats 2024-2025 Premier League opponent stats.xls
Squad Standard Stats 2024-2025 Premier League.xls

In [13]:
all_tables = {}

for file in files:
    tables = pd.read_html(file)

    print(f"\n{file.name}")
    print(f"Tables found: {len(tables)}")

    # For now, take the first table from each file
    all_tables[file.stem.strip()] = tables[0]

Premier League home and away .xls
Tables found: 1

Premier League Overall.xls
Tables found: 1

Squad Goalkeeping 2024-2025 Premier League.xls
Tables found: 1

Squad Goalkeeping Opponent.xls
Tables found: 1

Squad Miscellaneous Stats 2024-2025 Premier League.xls
Tables found: 1

Squad Miscellaneous Stats Opponent.xls
Tables found: 1

Squad Playing Time 2024-2025 Premier League.xls
Tables found: 1

Squad Playing Time Opponent.xls
Tables found: 1

Squad Shooting 2024-2025 Premier League .xls
Tables found: 1

Squad Shooting Opponent .xls
Tables found: 1

Squad Standard Stats 2024-2025 Premier League opponent stats.xls
Tables found: 1

Squad Standard Stats 2024-2025 Premier League.xls
Tables found: 1

In [14]:
all_tables.keys()

dict_keys(['Premier League home and away', 'Premier League Overall', 'Squad Goalkeeping 2024-2025 Premier League', 'Squad Goalkeeping Opponent', 'Squad Miscellaneous Stats 2024-2025 Premier League', 'Squad Miscellaneous Stats Opponent', 'Squad Playing Time 2024-2025 Premier League', 'Squad Playing Time Opponent', 'Squad Shooting 2024-2025 Premier League', 'Squad Shooting Opponent', 'Squad Standard Stats 2024-2025 Premier League opponent stats', 'Squad Standard Stats 2024-2025 Premier League'])

In [15]:
len(all_tables)

12

In [16]:
for name, df in all_tables.items():
    print("=" * 80)
    print(name)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())

================================================================================
Premier League home and away
Shape: (20, 20)
Columns: [('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Squad'), ('Home', 'MP'), ('Home', 'W'), ('Home', 'D'), ('Home', 'L'), ('Home', 'GF'), ('Home', 'GA'), ('Home', 'GD'), ('Home', 'Pts'), ('Home', 'Pts/MP'), ('Away', 'MP'), ('Away', 'W'), ('Away', 'D'), ('Away', 'L'), ('Away', 'GF'), ('Away', 'GA'), ('Away', 'GD'), ('Away', 'Pts'), ('Away', 'Pts/MP')]
================================================================================
Premier League Overall
Shape: (20, 15)
Columns: ['Rk', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP', 'Attendance', 'Top Team Scorer', 'Goalkeeper', 'Notes']
================================================================================
Squad Goalkeeping 2024-2025 Premier League
Shape: (20, 21)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'GA'), ('Performance', 'GA90'), ('Performance', 'SoTA'), ('Performance', 'Saves'), ('Performance', 'Save%'), ('Performance', 'W'), ('Performance', 'D'), ('Performance', 'L'), ('Performance', 'CS'), ('Performance', 'CS%'), ('Penalty Kicks', 'PKatt'), ('Penalty Kicks', 'PKA'), ('Penalty Kicks', 'PKsv'), ('Penalty Kicks', 'PKm'), ('Penalty Kicks', 'Save%')]
================================================================================
Squad Goalkeeping Opponent
Shape: (20, 21)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'GA'), ('Performance', 'GA90'), ('Performance', 'SoTA'), ('Performance', 'Saves'), ('Performance', 'Save%'), ('Performance', 'W'), ('Performance', 'D'), ('Performance', 'L'), ('Performance', 'CS'), ('Performance', 'CS%'), ('Penalty Kicks', 'PKatt'), ('Penalty Kicks', 'PKA'), ('Penalty Kicks', 'PKsv'), ('Penalty Kicks', 'PKm'), ('Penalty Kicks', 'Save%')]
================================================================================
Squad Miscellaneous Stats 2024-2025 Premier League
Shape: (20, 15)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Performance', '2CrdY'), ('Performance', 'Fls'), ('Performance', 'Fld'), ('Performance', 'Off'), ('Performance', 'Crs'), ('Performance', 'Int'), ('Performance', 'TklW'), ('Performance', 'PKwon'), ('Performance', 'PKcon'), ('Performance', 'OG')]
================================================================================
Squad Miscellaneous Stats Opponent
Shape: (20, 15)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Performance', '2CrdY'), ('Performance', 'Fls'), ('Performance', 'Fld'), ('Performance', 'Off'), ('Performance', 'Crs'), ('Performance', 'Int'), ('Performance', 'TklW'), ('Performance', 'PKwon'), ('Performance', 'PKcon'), ('Performance', 'OG')]
================================================================================
Squad Playing Time 2024-2025 Premier League
Shape: (20, 19)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Playing Time', 'MP'), ('Playing Time', 'Min'), ('Playing Time', 'Mn/MP'), ('Playing Time', 'Min%'), ('Playing Time', '90s'), ('Starts', 'Starts'), ('Starts', 'Mn/Start'), ('Starts', 'Compl'), ('Subs', 'Subs'), ('Subs', 'Mn/Sub'), ('Subs', 'unSub'), ('Team Success', 'PPM'), ('Team Success', 'onG'), ('Team Success', 'onGA'), ('Team Success', '+/-'), ('Team Success', '+/-90')]
================================================================================
Squad Playing Time Opponent
Shape: (20, 19)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Playing Time', 'MP'), ('Playing Time', 'Min'), ('Playing Time', 'Mn/MP'), ('Playing Time', 'Min%'), ('Playing Time', '90s'), ('Starts', 'Starts'), ('Starts', 'Mn/Start'), ('Starts', 'Compl'), ('Subs', 'Subs'), ('Subs', 'Mn/Sub'), ('Subs', 'unSub'), ('Team Success', 'PPM'), ('Team Success', 'onG'), ('Team Success', 'onGA'), ('Team Success', '+/-'), ('Team Success', '+/-90')]
================================================================================
Squad Shooting 2024-2025 Premier League
Shape: (20, 13)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Standard', 'Gls'), ('Standard', 'Sh'), ('Standard', 'SoT'), ('Standard', 'SoT%'), ('Standard', 'Sh/90'), ('Standard', 'SoT/90'), ('Standard', 'G/Sh'), ('Standard', 'G/SoT'), ('Standard', 'PK'), ('Standard', 'PKatt')]
================================================================================
Squad Shooting Opponent
Shape: (20, 13)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', '90s'), ('Standard', 'Gls'), ('Standard', 'Sh'), ('Standard', 'SoT'), ('Standard', 'SoT%'), ('Standard', 'Sh/90'), ('Standard', 'SoT/90'), ('Standard', 'G/Sh'), ('Standard', 'G/SoT'), ('Standard', 'PK'), ('Standard', 'PKatt')]
================================================================================
Squad Standard Stats 2024-2025 Premier League opponent stats
Shape: (20, 21)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Poss'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'Gls'), ('Performance', 'Ast'), ('Performance', 'G+A'), ('Performance', 'G-PK'), ('Performance', 'PK'), ('Performance', 'PKatt'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'), ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'), ('Per 90 Minutes', 'G+A-PK')]
================================================================================
Squad Standard Stats 2024-2025 Premier League
Shape: (20, 21)
Columns: [('Unnamed: 0_level_0', 'Squad'), ('Unnamed: 1_level_0', '# Pl'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Poss'), ('Playing Time', 'MP'), ('Playing Time', 'Starts'), ('Playing Time', 'Min'), ('Playing Time', '90s'), ('Performance', 'Gls'), ('Performance', 'Ast'), ('Performance', 'G+A'), ('Performance', 'G-PK'), ('Performance', 'PK'), ('Performance', 'PKatt'), ('Performance', 'CrdY'), ('Performance', 'CrdR'), ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'), ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'), ('Per 90 Minutes', 'G+A-PK')]

In [17]:
def clean_fbref_columns(df):
    df = df.copy()

    # Flatten MultiIndex columns
    if isinstance(df.columns, pd.MultiIndex):
        new_columns = []

        for col in df.columns:
            parts = []

            for part in col:
                part = str(part).strip()

                # Ignore empty / unnamed levels
                if part and not part.startswith("Unnamed"):
                    parts.append(part)

            # Remove duplicates while preserving order
            parts = list(dict.fromkeys(parts))

            if len(parts) == 1:
                new_columns.append(parts[0])
            else:
                new_columns.append("_".join(parts))

        df.columns = new_columns

    # Clean normal columns
    else:
        df.columns = [
            str(col).strip()
            for col in df.columns
        ]

    return df

In [18]:
standard_df = all_tables["Squad Standard Stats 2024-2025 Premier League"]

standard_df = clean_fbref_columns(standard_df)

print(standard_df.shape)
print(standard_df.columns.tolist())

(20, 21)
['Squad', '# Pl', 'Age', 'Poss', 'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s', 'Performance_Gls', 'Performance_Ast', 'Performance_G+A', 'Performance_G-PK', 'Performance_PK', 'Performance_PKatt', 'Performance_CrdY', 'Performance_CrdR', 'Per 90 Minutes_Gls', 'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A', 'Per 90 Minutes_G-PK', 'Per 90 Minutes_G+A-PK']

In [19]:
cleaned_tables = {}

for name, df in all_tables.items():
    cleaned_tables[name] = clean_fbref_columns(df)

print("Tables cleaned:", len(cleaned_tables))

Tables cleaned: 12

In [20]:
for name, df in cleaned_tables.items():
    print("\n" + "=" * 80)
    print(name)
    print("Shape:", df.shape)
    print("Columns:")
    print(df.columns.tolist())

================================================================================
Premier League home and away
Shape: (20, 20)
Columns:
['Rk', 'Squad', 'Home_MP', 'Home_W', 'Home_D', 'Home_L', 'Home_GF', 'Home_GA', 'Home_GD', 'Home_Pts', 'Home_Pts/MP', 'Away_MP', 'Away_W', 'Away_D', 'Away_L', 'Away_GF', 'Away_GA', 'Away_GD', 'Away_Pts', 'Away_Pts/MP']

================================================================================
Premier League Overall
Shape: (20, 15)
Columns:
['Rk', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP', 'Attendance', 'Top Team Scorer', 'Goalkeeper', 'Notes']

================================================================================
Squad Goalkeeping 2024-2025 Premier League
Shape: (20, 21)
Columns:
['Squad', '# Pl', 'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s', 'Performance_GA', 'Performance_GA90', 'Performance_SoTA', 'Performance_Saves', 'Performance_Save%', 'Performance_W', 'Performance_D', 'Performance_L', 'Performance_CS', 'Performance_CS%', 'Penalty Kicks_PKatt', 'Penalty Kicks_PKA', 'Penalty Kicks_PKsv', 'Penalty Kicks_PKm', 'Penalty Kicks_Save%']

================================================================================
Squad Goalkeeping Opponent
Shape: (20, 21)
Columns:
['Squad', '# Pl', 'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s', 'Performance_GA', 'Performance_GA90', 'Performance_SoTA', 'Performance_Saves', 'Performance_Save%', 'Performance_W', 'Performance_D', 'Performance_L', 'Performance_CS', 'Performance_CS%', 'Penalty Kicks_PKatt', 'Penalty Kicks_PKA', 'Penalty Kicks_PKsv', 'Penalty Kicks_PKm', 'Penalty Kicks_Save%']

================================================================================
Squad Miscellaneous Stats 2024-2025 Premier League
Shape: (20, 15)
Columns:
['Squad', '# Pl', '90s', 'Performance_CrdY', 'Performance_CrdR', 'Performance_2CrdY', 'Performance_Fls', 'Performance_Fld', 'Performance_Off', 'Performance_Crs', 'Performance_Int', 'Performance_TklW', 'Performance_PKwon', 'Performance_PKcon', 'Performance_OG']

================================================================================
Squad Miscellaneous Stats Opponent
Shape: (20, 15)
Columns:
['Squad', '# Pl', '90s', 'Performance_CrdY', 'Performance_CrdR', 'Performance_2CrdY', 'Performance_Fls', 'Performance_Fld', 'Performance_Off', 'Performance_Crs', 'Performance_Int', 'Performance_TklW', 'Performance_PKwon', 'Performance_PKcon', 'Performance_OG']

================================================================================
Squad Playing Time 2024-2025 Premier League
Shape: (20, 19)
Columns:
['Squad', '# Pl', 'Age', 'Playing Time_MP', 'Playing Time_Min', 'Playing Time_Mn/MP', 'Playing Time_Min%', 'Playing Time_90s', 'Starts', 'Starts_Mn/Start', 'Starts_Compl', 'Subs', 'Subs_Mn/Sub', 'Subs_unSub', 'Team Success_PPM', 'Team Success_onG', 'Team Success_onGA', 'Team Success_+/-', 'Team Success_+/-90']

================================================================================
Squad Playing Time Opponent
Shape: (20, 19)
Columns:
['Squad', '# Pl', 'Age', 'Playing Time_MP', 'Playing Time_Min', 'Playing Time_Mn/MP', 'Playing Time_Min%', 'Playing Time_90s', 'Starts', 'Starts_Mn/Start', 'Starts_Compl', 'Subs', 'Subs_Mn/Sub', 'Subs_unSub', 'Team Success_PPM', 'Team Success_onG', 'Team Success_onGA', 'Team Success_+/-', 'Team Success_+/-90']

================================================================================
Squad Shooting 2024-2025 Premier League
Shape: (20, 13)
Columns:
['Squad', '# Pl', '90s', 'Standard_Gls', 'Standard_Sh', 'Standard_SoT', 'Standard_SoT%', 'Standard_Sh/90', 'Standard_SoT/90', 'Standard_G/Sh', 'Standard_G/SoT', 'Standard_PK', 'Standard_PKatt']

================================================================================
Squad Shooting Opponent
Shape: (20, 13)
Columns:
['Squad', '# Pl', '90s', 'Standard_Gls', 'Standard_Sh', 'Standard_SoT', 'Standard_SoT%', 'Standard_Sh/90', 'Standard_SoT/90', 'Standard_G/Sh', 'Standard_G/SoT', 'Standard_PK', 'Standard_PKatt']

================================================================================
Squad Standard Stats 2024-2025 Premier League opponent stats
Shape: (20, 21)
Columns:
['Squad', '# Pl', 'Age', 'Poss', 'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s', 'Performance_Gls', 'Performance_Ast', 'Performance_G+A', 'Performance_G-PK', 'Performance_PK', 'Performance_PKatt', 'Performance_CrdY', 'Performance_CrdR', 'Per 90 Minutes_Gls', 'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A', 'Per 90 Minutes_G-PK', 'Per 90 Minutes_G+A-PK']

================================================================================
Squad Standard Stats 2024-2025 Premier League
Shape: (20, 21)
Columns:
['Squad', '# Pl', 'Age', 'Poss', 'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s', 'Performance_Gls', 'Performance_Ast', 'Performance_G+A', 'Performance_G-PK', 'Performance_PK', 'Performance_PKatt', 'Performance_CrdY', 'Performance_CrdR', 'Per 90 Minutes_Gls', 'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A', 'Per 90 Minutes_G-PK', 'Per 90 Minutes_G+A-PK']

In [21]:
for name, df in cleaned_tables.items():
    print(f"{name}: {'Squad' in df.columns}")

Premier League home and away: True
Premier League Overall: True
Squad Goalkeeping 2024-2025 Premier League: True
Squad Goalkeeping Opponent: True
Squad Miscellaneous Stats 2024-2025 Premier League: True
Squad Miscellaneous Stats Opponent: True
Squad Playing Time 2024-2025 Premier League: True
Squad Playing Time Opponent: True
Squad Shooting 2024-2025 Premier League: True
Squad Shooting Opponent: True
Squad Standard Stats 2024-2025 Premier League opponent stats: True
Squad Standard Stats 2024-2025 Premier League: True

In [22]:
def merge_team_table(master_df, new_df, table_name):
    """
    Merge a team-level FBref table into the master dataset.
    """
    
    # Remove duplicate Squad rows if any exist
    new_df = new_df.drop_duplicates(subset="Squad")

    # Don't bring across duplicate columns
    duplicate_columns = [
        col for col in new_df.columns
        if col in master_df.columns and col != "Squad"
    ]
    
    new_df = new_df.drop(columns=duplicate_columns)

    # Merge
    master_df = master_df.merge(
        new_df,
        on="Squad",
        how="left",
        validate="one_to_one"
    )

    print(
        f"{table_name:<55} "
        f"Shape: {master_df.shape}"
    )

    return master_df

In [23]:
master_df = cleaned_tables[
    "Premier League Overall"
].copy()

print(master_df.shape)

(20, 15)

In [24]:
master_df.head()

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Liverpool,38,25,9,4,86,41,45,84,2.21,60324,Mohamed Salah - 29,Alisson,â Champions League via league finish
1,2,Arsenal,38,20,14,4,69,34,35,74,1.95,60251,Kai Havertz - 9,David Raya,â Champions League via league finish
2,3,Manchester City,38,21,8,9,72,44,28,71,1.87,52756,Erling Haaland - 22,Ederson Moraes,â Champions League via league finish
3,4,Chelsea,38,20,9,9,64,43,21,69,1.82,39672,Cole Palmer - 15,Robert SÃ¡nchez,â Champions League via league finish
4,5,Newcastle,38,20,6,12,68,47,21,66,1.74,52187,Alexander Isak - 23,Nick Pope,â Champions League via league finish

In [25]:
master_df = merge_team_table(
    master_df,
    cleaned_tables["Premier League home and away"],
    "Home/Away"
)

Home/Away                                               Shape: (20, 33)

In [26]:
master_df = merge_team_table(
    master_df,
    cleaned_tables["Squad Standard Stats 2024-2025 Premier League"],
    "Standard Stats"
)

Standard Stats                                          Shape: (20, 53)

In [27]:
master_df = merge_team_table(
    master_df,
    cleaned_tables["Squad Shooting 2024-2025 Premier League"],
    "Shooting"
)

Shooting                                                Shape: (20, 64)

In [28]:
master_df = merge_team_table(
    master_df,
    cleaned_tables["Squad Goalkeeping 2024-2025 Premier League"],
    "Goalkeeping"
)

Goalkeeping                                             Shape: (20, 79)

In [29]:
master_df = merge_team_table(
    master_df,
    cleaned_tables["Squad Playing Time 2024-2025 Premier League"],
    "Playing Time"
)

Playing Time                                            Shape: (20, 92)

In [30]:
master_df = merge_team_table(
    master_df,
    cleaned_tables["Squad Miscellaneous Stats 2024-2025 Premier League"],
    "Miscellaneous"
)

Miscellaneous                                           Shape: (20, 102)

In [31]:
print("Shape:", master_df.shape)

print("\nFirst 20 columns:")
print(master_df.columns[:20].tolist())

print("\nLast 20 columns:")
print(master_df.columns[-20:].tolist())

Shape: (20, 102)

First 20 columns:
['Rk', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP', 'Attendance', 'Top Team Scorer', 'Goalkeeper', 'Notes', 'Home_MP', 'Home_W', 'Home_D', 'Home_L', 'Home_GF']

Last 20 columns:
['Starts_Mn/Start', 'Starts_Compl', 'Subs', 'Subs_Mn/Sub', 'Subs_unSub', 'Team Success_PPM', 'Team Success_onG', 'Team Success_onGA', 'Team Success_+/-', 'Team Success_+/-90', 'Performance_2CrdY', 'Performance_Fls', 'Performance_Fld', 'Performance_Off', 'Performance_Crs', 'Performance_Int', 'Performance_TklW', 'Performance_PKwon', 'Performance_PKcon', 'Performance_OG']

In [32]:
print("\nData types:")
print(master_df.dtypes.value_counts())

Data types:
int64      75
float64    23
str         4
Name: count, dtype: int64

In [33]:
print("\nMissing values:")
missing = master_df.isna().sum()

print(
    missing[missing > 0]
    .sort_values(ascending=False)
)

Missing values:
Notes    8
dtype: int64

In [34]:
print("\nMissing values:")
missing = master_df.isna().sum()

print(
    missing[missing > 0]
    .sort_values(ascending=False)
)

Missing values:
Notes    8
dtype: int64

In [35]:
print("Number of teams:", master_df["Squad"].nunique())

print("\nTeams:")
print(master_df["Squad"].tolist())

Number of teams: 20

Teams:
['Liverpool', 'Arsenal', 'Manchester City', 'Chelsea', 'Newcastle', 'Aston Villa', 'Nottingham', 'Brighton', 'Bournemouth', 'Brentford', 'Fulham', 'Crystal Palace', 'Everton', 'West Ham', 'Manchester Utd', 'Wolves', 'Tottenham', 'Leicester City', 'Ipswich Town', 'Southampton']

In [36]:
duplicates = master_df.columns[
    master_df.columns.duplicated()
]

print("Duplicate columns:")
print(duplicates.tolist())

Duplicate columns:
[]

In [37]:
duplicate_teams = master_df[
    master_df["Squad"].duplicated(keep=False)
]

print(duplicate_teams)

Empty DataFrame
Columns: [Rk, Squad, MP, W, D, L, GF, GA, GD, Pts, Pts/MP, Attendance, Top Team Scorer, Goalkeeper, Notes, Home_MP, Home_W, Home_D, Home_L, Home_GF, Home_GA, Home_GD, Home_Pts, Home_Pts/MP, Away_MP, Away_W, Away_D, Away_L, Away_GF, Away_GA, Away_GD, Away_Pts, Away_Pts/MP, # Pl, Age, Poss, Playing Time_MP, Playing Time_Starts, Playing Time_Min, Playing Time_90s, Performance_Gls, Performance_Ast, Performance_G+A, Performance_G-PK, Performance_PK, Performance_PKatt, Performance_CrdY, Performance_CrdR, Per 90 Minutes_Gls, Per 90 Minutes_Ast, Per 90 Minutes_G+A, Per 90 Minutes_G-PK, Per 90 Minutes_G+A-PK, 90s, Standard_Gls, Standard_Sh, Standard_SoT, Standard_SoT%, Standard_Sh/90, Standard_SoT/90, Standard_G/Sh, Standard_G/SoT, Standard_PK, Standard_PKatt, Performance_GA, Performance_GA90, Performance_SoTA, Performance_Saves, Performance_Save%, Performance_W, Performance_D, Performance_L, Performance_CS, Performance_CS%, Penalty Kicks_PKatt, Penalty Kicks_PKA, Penalty Kicks_PKsv, Penalty Kicks_PKm, Penalty Kicks_Save%, Playing Time_Mn/MP, Playing Time_Min%, Starts, Starts_Mn/Start, Starts_Compl, Subs, Subs_Mn/Sub, Subs_unSub, Team Success_PPM, Team Success_onG, Team Success_onGA, Team Success_+/-, Team Success_+/-90, Performance_2CrdY, Performance_Fls, Performance_Fld, Performance_Off, Performance_Crs, Performance_Int, Performance_TklW, Performance_PKwon, ...]
Index: []

[0 rows x 102 columns]

In [38]:
opponent_tables = {
    name: df
    for name, df in cleaned_tables.items()
    if "Opponent" in name
}

for name, df in opponent_tables.items():
    print("\n" + "=" * 80)
    print(name)
    print("Shape:", df.shape)
    print(df.columns.tolist())

================================================================================
Squad Goalkeeping Opponent
Shape: (20, 21)
['Squad', '# Pl', 'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s', 'Performance_GA', 'Performance_GA90', 'Performance_SoTA', 'Performance_Saves', 'Performance_Save%', 'Performance_W', 'Performance_D', 'Performance_L', 'Performance_CS', 'Performance_CS%', 'Penalty Kicks_PKatt', 'Penalty Kicks_PKA', 'Penalty Kicks_PKsv', 'Penalty Kicks_PKm', 'Penalty Kicks_Save%']

================================================================================
Squad Miscellaneous Stats Opponent
Shape: (20, 15)
['Squad', '# Pl', '90s', 'Performance_CrdY', 'Performance_CrdR', 'Performance_2CrdY', 'Performance_Fls', 'Performance_Fld', 'Performance_Off', 'Performance_Crs', 'Performance_Int', 'Performance_TklW', 'Performance_PKwon', 'Performance_PKcon', 'Performance_OG']

================================================================================
Squad Playing Time Opponent
Shape: (20, 19)
['Squad', '# Pl', 'Age', 'Playing Time_MP', 'Playing Time_Min', 'Playing Time_Mn/MP', 'Playing Time_Min%', 'Playing Time_90s', 'Starts', 'Starts_Mn/Start', 'Starts_Compl', 'Subs', 'Subs_Mn/Sub', 'Subs_unSub', 'Team Success_PPM', 'Team Success_onG', 'Team Success_onGA', 'Team Success_+/-', 'Team Success_+/-90']

================================================================================
Squad Shooting Opponent
Shape: (20, 13)
['Squad', '# Pl', '90s', 'Standard_Gls', 'Standard_Sh', 'Standard_SoT', 'Standard_SoT%', 'Standard_Sh/90', 'Standard_SoT/90', 'Standard_G/Sh', 'Standard_G/SoT', 'Standard_PK', 'Standard_PKatt']

In [39]:
print(master_df.columns.tolist())

['Rk', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP', 'Attendance', 'Top Team Scorer', 'Goalkeeper', 'Notes', 'Home_MP', 'Home_W', 'Home_D', 'Home_L', 'Home_GF', 'Home_GA', 'Home_GD', 'Home_Pts', 'Home_Pts/MP', 'Away_MP', 'Away_W', 'Away_D', 'Away_L', 'Away_GF', 'Away_GA', 'Away_GD', 'Away_Pts', 'Away_Pts/MP', '# Pl', 'Age', 'Poss', 'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s', 'Performance_Gls', 'Performance_Ast', 'Performance_G+A', 'Performance_G-PK', 'Performance_PK', 'Performance_PKatt', 'Performance_CrdY', 'Performance_CrdR', 'Per 90 Minutes_Gls', 'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A', 'Per 90 Minutes_G-PK', 'Per 90 Minutes_G+A-PK', '90s', 'Standard_Gls', 'Standard_Sh', 'Standard_SoT', 'Standard_SoT%', 'Standard_Sh/90', 'Standard_SoT/90', 'Standard_G/Sh', 'Standard_G/SoT', 'Standard_PK', 'Standard_PKatt', 'Performance_GA', 'Performance_GA90', 'Performance_SoTA', 'Performance_Saves', 'Performance_Save%', 'Performance_W', 'Performance_D', 'Performance_L', 'Performance_CS', 'Performance_CS%', 'Penalty Kicks_PKatt', 'Penalty Kicks_PKA', 'Penalty Kicks_PKsv', 'Penalty Kicks_PKm', 'Penalty Kicks_Save%', 'Playing Time_Mn/MP', 'Playing Time_Min%', 'Starts', 'Starts_Mn/Start', 'Starts_Compl', 'Subs', 'Subs_Mn/Sub', 'Subs_unSub', 'Team Success_PPM', 'Team Success_onG', 'Team Success_onGA', 'Team Success_+/-', 'Team Success_+/-90', 'Performance_2CrdY', 'Performance_Fls', 'Performance_Fld', 'Performance_Off', 'Performance_Crs', 'Performance_Int', 'Performance_TklW', 'Performance_PKwon', 'Performance_PKcon', 'Performance_OG']

In [41]:
print(match_df.shape)
print(match_df.columns.tolist())
print(match_df.head(10))

NameError: name 'match_df' is not defined

In [ ]:
from pathlib import Path

project_path = Path(r"C:\Users\karab\PremierLeagueML")

for path in project_path.rglob("*"):
    if path.is_file():
        print(path.relative_to(project_path))

.venv\.gitignore
.venv\pyvenv.cfg
notebooks\01_Data_Loading.ipynb
notebooks\02_Load_All_Files.ipynb
data\raw\2022 PL Season\PL 2022 HomeAway.xls
data\raw\2022 PL Season\PL 2022 Overall.xls
data\raw\2022 PL Season\Squad Goalkeeping Opponent.xls
data\raw\2022 PL Season\Squad Goalkeeping Squad.xls
data\raw\2022 PL Season\Squad Miscellaneous Stats O.xls
data\raw\2022 PL Season\Squad Miscellaneous Stats S.xls
data\raw\2022 PL Season\Squad Playing Time Opponent.xls
data\raw\2022 PL Season\Squad Playing Time S.xls
data\raw\2022 PL Season\Squad Shooting Opponent.xls
data\raw\2022 PL Season\Squad Shooting S.xls
data\raw\2022 PL Season\Squad Standard Stats Opponent.xls
data\raw\2022 PL Season\Squad Standard Stats Squad .xls
data\raw\2023 PL Season\Premier League 2023 HomeAway.xls
data\raw\2023 PL Season\Premier League 2023 Overall.xls
data\raw\2023 PL Season\Squad Goalkeeping Opponent Stats.xls
data\raw\2023 PL Season\Squad Goalkeeping Squad Stats.xls
data\raw\2023 PL Season\Squad Miscellaneous Stats Opponent Stats.xls
data\raw\2023 PL Season\Squad Miscellaneous Stats Squad Stats.xls
data\raw\2023 PL Season\Squad Playing Time Opponent Stats.xls
data\raw\2023 PL Season\Squad Playing Time Squad Stats.xls
data\raw\2023 PL Season\Squad Shooting Opponent stats.xls
data\raw\2023 PL Season\Squad Standard Stats 2023.xls
data\raw\2023 PL Season\Squad Standard Stats Opponent Stats.xls
data\raw\2023 PL Season\Squad Sthooting Squad Stats.xls
data\raw\2024 PL Season\2024 PL Season Home Away.xls
data\raw\2024 PL Season\2024 PL Season overall.xls
data\raw\2024 PL Season\Squad Goalkeeping 2023-2024 Premier League Opponent Stats.xls
data\raw\2024 PL Season\Squad Goalkeeping 2023-2024 Premier League Opponents.xls
data\raw\2024 PL Season\Squad Goalkeeping 2023-2024 Premier League.xls
data\raw\2024 PL Season\Squad Miscellaneous Stats 2023-2024 Premier League Opponents.xls
data\raw\2024 PL Season\Squad Miscellaneous Stats 2023-2024 Premier League.xls
data\raw\2024 PL Season\Squad Playing Time 2023-2024 Premier Leagu Opponents.xls
data\raw\2024 PL Season\Squad Playing Time 2023-2024 Premier League.xls
data\raw\2024 PL Season\Squad Shooting 2023-2024 Premier League.xls
data\raw\2024 PL Season\Squad Standard Stats 2023-2024 Premier League Opponet Stats.xls
data\raw\2024 PL Season\Squad Standard Stats 2023-2024 Premier League.xls
data\raw\2025 PL Season\Premier League home and away .xls
data\raw\2025 PL Season\Premier League Overall.xls
data\raw\2025 PL Season\Squad Goalkeeping 2024-2025 Premier League.xls
data\raw\2025 PL Season\Squad Goalkeeping Opponent.xls
data\raw\2025 PL Season\Squad Miscellaneous Stats 2024-2025 Premier League.xls
data\raw\2025 PL Season\Squad Miscellaneous Stats Opponent.xls
data\raw\2025 PL Season\Squad Playing Time 2024-2025 Premier League.xls
data\raw\2025 PL Season\Squad Playing Time Opponent.xls
data\raw\2025 PL Season\Squad Shooting 2024-2025 Premier League .xls
data\raw\2025 PL Season\Squad Shooting Opponent .xls
data\raw\2025 PL Season\Squad Standard Stats 2024-2025 Premier League opponent stats.xls
data\raw\2025 PL Season\Squad Standard Stats 2024-2025 Premier League.xls
data\raw\2026 PL Season\Premier League 2026 Overall.xls
data\raw\2026 PL Season\Premier League Home,away.xls
data\raw\2026 PL Season\Squad goalkeeping 2026 PL.xls
data\raw\2026 PL Season\Squad Goalkeeping Opponent.xls
data\raw\2026 PL Season\Squad Miscellaneous Stats 2025-2026 Premier Leag.xls
data\raw\2026 PL Season\Squad Miscellaneous Stats Opponent.xls
data\raw\2026 PL Season\Squad Playing Time 2025-2026 Premier League.xls
data\raw\2026 PL Season\Squad Playing Time Opponent.xls
data\raw\2026 PL Season\Squad Shooting 2025-2026 Premier League.xls
data\raw\2026 PL Season\Squad Shooting Opponent .xls
data\raw\2026 PL Season\Squad Standard Stats 2025-2026 Premier League.xls
data\raw\2026 PL Season\Squad Standard Stats Opponent.xls
.venv\Scripts\activate
.venv\Scripts\activate.bat
.venv\Scripts\activate.fish
.venv\Scripts\Activate.ps1
.venv\Scripts\cffi-gen-src.exe
.venv\Scripts\deactivate.bat
.venv\Scripts\debugpy-adapter.exe
.venv\Scripts\debugpy.exe
.venv\Scripts\f2py.exe
.venv\Scripts\fonttools.exe
.venv\Scripts\httpx.exe
.venv\Scripts\idna.exe
.venv\Scripts\ipython.exe
.venv\Scripts\ipython3.exe
.venv\Scripts\jlpm.exe
.venv\Scripts\jsonpointer
.venv\Scripts\jsonschema.exe
.venv\Scripts\jupyter-builder.exe
.venv\Scripts\jupyter-console.exe
.venv\Scripts\jupyter-dejavu.exe
.venv\Scripts\jupyter-events.exe
.venv\Scripts\jupyter-execute.exe
.venv\Scripts\jupyter-kernel.exe
.venv\Scripts\jupyter-kernelspec.exe
.venv\Scripts\jupyter-lab.exe
.venv\Scripts\jupyter-labextension.exe
.venv\Scripts\jupyter-labhub.exe
.venv\Scripts\jupyter-migrate.exe
.venv\Scripts\jupyter-nbconvert.exe
.venv\Scripts\jupyter-notebook.exe
.venv\Scripts\jupyter-run.exe
.venv\Scripts\jupyter-server.exe
.venv\Scripts\jupyter-troubleshoot.exe
.venv\Scripts\jupyter-trust.exe
.venv\Scripts\jupyter.exe
.venv\Scripts\mistune.exe
.venv\Scripts\normalizer.exe
.venv\Scripts\numpy-config.exe
.venv\Scripts\pip.exe
.venv\Scripts\pip3.13.exe
.venv\Scripts\pip3.exe
.venv\Scripts\pybabel.exe
.venv\Scripts\pyftmerge.exe
.venv\Scripts\pyftsubset.exe
.venv\Scripts\pygmentize.exe
.venv\Scripts\pyjson5.exe
.venv\Scripts\python.exe
.venv\Scripts\pythonw.exe
.venv\Scripts\runxlrd.py
.venv\Scripts\send2trash.exe
.venv\Scripts\ttx.exe
.venv\Scripts\wsdump.exe
.venv\share\applications\jupyter-notebook.desktop
.venv\share\applications\jupyterlab.desktop
.venv\share\man\man1\ipython.1
.venv\share\man\man1\ttx.1
.venv\share\jupyter\nbextensions\jupyter-js-widgets\extension.js
.venv\share\jupyter\nbextensions\jupyter-js-widgets\extension.js.LICENSE.txt
.venv\share\jupyter\nbextensions\jupyter-js-widgets\extension.js.map
.venv\share\jupyter\nbconvert\templates\asciidoc\conf.json
.venv\share\jupyter\nbconvert\templates\asciidoc\index.asciidoc.j2
.venv\share\jupyter\nbconvert\templates\base\celltags.j2
.venv\share\jupyter\nbconvert\templates\base\cell_id_anchor.j2
.venv\share\jupyter\nbconvert\templates\base\display_priority.j2
.venv\share\jupyter\nbconvert\templates\base\jupyter_widgets.html.j2
.venv\share\jupyter\nbconvert\templates\base\mathjax.html.j2
.venv\share\jupyter\nbconvert\templates\base\null.j2
.venv\share\jupyter\nbconvert\templates\basic\conf.json
.venv\share\jupyter\nbconvert\templates\basic\index.html.j2
.venv\share\jupyter\nbconvert\templates\classic\base.html.j2
.venv\share\jupyter\nbconvert\templates\classic\conf.json
.venv\share\jupyter\nbconvert\templates\classic\index.html.j2
.venv\share\jupyter\nbconvert\templates\compatibility\display_priority.tpl
.venv\share\jupyter\nbconvert\templates\compatibility\full.tpl
.venv\share\jupyter\nbconvert\templates\lab\base.html.j2
.venv\share\jupyter\nbconvert\templates\lab\conf.json
.venv\share\jupyter\nbconvert\templates\lab\index.html.j2
.venv\share\jupyter\nbconvert\templates\lab\mermaidjs.html.j2
.venv\share\jupyter\nbconvert\templates\latex\base.tex.j2
.venv\share\jupyter\nbconvert\templates\latex\conf.json
.venv\share\jupyter\nbconvert\templates\latex\display_priority.j2
.venv\share\jupyter\nbconvert\templates\latex\document_contents.tex.j2
.venv\share\jupyter\nbconvert\templates\latex\index.tex.j2
.venv\share\jupyter\nbconvert\templates\latex\null.j2
.venv\share\jupyter\nbconvert\templates\latex\report.tex.j2
.venv\share\jupyter\nbconvert\templates\latex\style_bw_ipython.tex.j2
.venv\share\jupyter\nbconvert\templates\latex\style_bw_python.tex.j2
.venv\share\jupyter\nbconvert\templates\latex\style_ipython.tex.j2
.venv\share\jupyter\nbconvert\templates\latex\style_jupyter.tex.j2
.venv\share\jupyter\nbconvert\templates\latex\style_python.tex.j2
.venv\share\jupyter\nbconvert\templates\markdown\conf.json
.venv\share\jupyter\nbconvert\templates\markdown\index.md.j2
.venv\share\jupyter\nbconvert\templates\python\conf.json
.venv\share\jupyter\nbconvert\templates\python\index.py.j2
.venv\share\jupyter\nbconvert\templates\reveal\base.html.j2
.venv\share\jupyter\nbconvert\templates\reveal\cellslidedata.j2
.venv\share\jupyter\nbconvert\templates\reveal\conf.json
.venv\share\jupyter\nbconvert\templates\reveal\index.html.j2
.venv\share\jupyter\nbconvert\templates\rst\conf.json
.venv\share\jupyter\nbconvert\templates\rst\index.rst.j2
.venv\share\jupyter\nbconvert\templates\script\conf.json
.venv\share\jupyter\nbconvert\templates\script\script.j2
.venv\share\jupyter\nbconvert\templates\webpdf\conf.json
.venv\share\jupyter\nbconvert\templates\webpdf\index.pdf.j2
.venv\share\jupyter\nbconvert\templates\reveal\static\custom_reveal.css
.venv\share\jupyter\nbconvert\templates\lab\static\index.css
.venv\share\jupyter\nbconvert\templates\lab\static\theme-dark.css
.venv\share\jupyter\nbconvert\templates\lab\static\theme-light.css
.venv\share\jupyter\nbconvert\templates\classic\static\style.css
.venv\share\jupyter\labextensions\jupyterlab_pygments\install.json
.venv\share\jupyter\labextensions\jupyterlab_pygments\package.json
.venv\share\jupyter\labextensions\jupyterlab_pygments\static\568.1e2faa2ba0bbe59c4780.js
.venv\share\jupyter\labextensions\jupyterlab_pygments\static\747.67662283a5707eeb4d4c.js
.venv\share\jupyter\labextensions\jupyterlab_pygments\static\remoteEntry.5cbb9d2323598fbda535.js
.venv\share\jupyter\labextensions\jupyterlab_pygments\static\style.js
.venv\share\jupyter\labextensions\jupyterlab_pygments\static\third-party-licenses.json
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\build_log.json
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\install.json
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\package.json
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\lib_index_js.56f37fb50492d0d63a45.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\lib_index_js.56f37fb50492d0d63a45.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\packages_base-manager_lib_index_js.13941b475e5b5a1ab133.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\packages_base-manager_lib_index_js.13941b475e5b5a1ab133.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\packages_base_lib_index_js-webpack_sharing_consume_default_jquery_jquery.5dd13f8e980fa3c50bfe.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\packages_base_lib_index_js-webpack_sharing_consume_default_jquery_jquery.5dd13f8e980fa3c50bfe.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\packages_controls_lib_index_js.6d5d05e0ec5e0c9f8185.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\packages_controls_lib_index_js.6d5d05e0ec5e0c9f8185.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\packages_controls_lib_version_js.105c0edf5e497d01e132.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\packages_controls_lib_version_js.105c0edf5e497d01e132.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\packages_output_lib_index_js.49c9e4037a3b9e9e3b18.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\packages_output_lib_index_js.49c9e4037a3b9e9e3b18.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\remoteEntry.9077b3d2deaffb329dfc.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\remoteEntry.9077b3d2deaffb329dfc.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\style.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\vendors-node_modules_backbone_backbone_js-node_modules_lodash_isEqual_js.ab532abfb6832a50f59e.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\vendors-node_modules_backbone_backbone_js-node_modules_lodash_isEqual_js.ab532abfb6832a50f59e.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\vendors-node_modules_base64-js_index_js-node_modules_sanitize-html_index_js.c79fc2bcc3f69676beda.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\vendors-node_modules_base64-js_index_js-node_modules_sanitize-html_index_js.c79fc2bcc3f69676beda.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\vendors-node_modules_d3-color_src_color_js-node_modules_d3-format_src_defaultLocale_js-node_m-09b215.2643c43f22ad111f4f82.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\vendors-node_modules_d3-color_src_color_js-node_modules_d3-format_src_defaultLocale_js-node_m-09b215.2643c43f22ad111f4f82.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\vendors-node_modules_jquery_dist_jquery_js.3afdf979a9caffdf15a7.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\vendors-node_modules_jquery_dist_jquery_js.3afdf979a9caffdf15a7.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\vendors-node_modules_semver_index_js.7a90c08b9ce3dac425c6.js
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\vendors-node_modules_semver_index_js.7a90c08b9ce3dac425c6.js.map
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\schemas\@jupyter-widgets\jupyterlab-manager\package.json.orig
.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\schemas\@jupyter-widgets\jupyterlab-manager\plugin.json
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\package.json
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\static\148.69fc9844a15ddd92.js
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\static\232.e5496ffb26186f51.js
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\static\590.b9d4a9533b932747.js
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\static\800.68f27b88f2605791.js
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\static\remoteEntry.633dbd75f801b3bc.js
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\static\style.js
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\static\third-party-licenses.json
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\schemas\@jupyter-notebook\lab-extension\interface-switcher.json
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\schemas\@jupyter-notebook\lab-extension\launch-tree.json
.venv\share\jupyter\labextensions\@jupyter-notebook\lab-extension\schemas\@jupyter-notebook\lab-extension\package.json.orig
.venv\share\jupyter\lab\static\0031b1860ea4ad75.woff
.venv\share\jupyter\lab\static\0271fb5e3e1adc0f.woff
.venv\share\jupyter\lab\static\04103ccddd44c0a5.woff
.venv\share\jupyter\lab\static\04dd5282f2256565.woff
.venv\share\jupyter\lab\static\088d0df35947deff.woff
.venv\share\jupyter\lab\static\0e53fe4feaaacc48.woff
.venv\share\jupyter\lab\static\1014.073326ef5d98db5e.js
.venv\share\jupyter\lab\static\1027.289ea871537e71a7.js
.venv\share\jupyter\lab\static\1028.812a1281fd9f7ba1.js
.venv\share\jupyter\lab\static\109.493a12dc42da3115.js
.venv\share\jupyter\lab\static\1164.8f9ceacce3ada5a5.js
.venv\share\jupyter\lab\static\1207.29d49de7be30f3c3.js
.venv\share\jupyter\lab\static\1286.7087e8344ef3005e.js
.venv\share\jupyter\lab\static\130.6ae02d05d1662acf.js
.venv\share\jupyter\lab\static\1311.39c4bb0b68584307.js
.venv\share\jupyter\lab\static\1325.1a013842dc2be176.js
.venv\share\jupyter\lab\static\1344.7c0e73be6aeed30b.js
.venv\share\jupyter\lab\static\1410.1d8b2fb31efaebee.js
.venv\share\jupyter\lab\static\1447.0dc5eacf8f731ec8.js
.venv\share\jupyter\lab\static\1460.b9d12dc72e63ec38.js
.venv\share\jupyter\lab\static\1527.6dfbfd27636edb2e.js
.venv\share\jupyter\lab\static\1539.2f9625818a3d1b90.js
.venv\share\jupyter\lab\static\155f8d0926f0bdfc.woff
.venv\share\jupyter\lab\static\1584.f43d421d2384c719.js
.venv\share\jupyter\lab\static\16.6cda5b6d5f0fa449.js
.venv\share\jupyter\lab\static\1601.c443d46d5b6dbb77.js
.venv\share\jupyter\lab\static\1617.cc66edd89898364c.js
.venv\share\jupyter\lab\static\1645.ed332d3fefafaead.js
.venv\share\jupyter\lab\static\170.bf91d89e4b982380.js
.venv\share\jupyter\lab\static\173.0f2f9c4254903e63.js
.venv\share\jupyter\lab\static\1815.b4c56924ee770a55.js
.venv\share\jupyter\lab\static\1873.d0e670bd840a1d49.js
.venv\share\jupyter\lab\static\1917.12a55957e6bd6fd0.js
.venv\share\jupyter\lab\static\1957.84d282100e18cd6c.js
.venv\share\jupyter\lab\static\1984.129e1d8ddca9362f.js
.venv\share\jupyter\lab\static\19bd61dc67f308ba.woff
.venv\share\jupyter\lab\static\1a10595a47bb3cf2.woff
.venv\share\jupyter\lab\static\2001.fcd2209118a7e77d.js
.venv\share\jupyter\lab\static\2004.2f631b96f5439cea.js
.venv\share\jupyter\lab\static\2011.2e10f24e0a331c02.js
.venv\share\jupyter\lab\static\2115.aaf130fb21b64ca1.js
.venv\share\jupyter\lab\static\2121.8dc495824b1f59ce.js
.venv\share\jupyter\lab\static\213.4168e841092fb2f0.js
.venv\share\jupyter\lab\static\2134.a7a5751faf22fd80.js
.venv\share\jupyter\lab\static\2208.ef6ea98c27c7851d.js
.venv\share\jupyter\lab\static\2272.1dd8f8d1ed60185f.js
.venv\share\jupyter\lab\static\2287.a918ef4a3b6b8f66.js
.venv\share\jupyter\lab\static\2292.faf2551abff7e12e.js
.venv\share\jupyter\lab\static\2299.55a1012700ee6259.js
.venv\share\jupyter\lab\static\2323.c7bce40851364fb3.js
.venv\share\jupyter\lab\static\2358.10a325f4d19e3817.js
.venv\share\jupyter\lab\static\2407.41669022954d447f.js
.venv\share\jupyter\lab\static\2461.eb1ea097b2eb54cf.js
.venv\share\jupyter\lab\static\2521.60af3fcdacace00b.js
.venv\share\jupyter\lab\static\2527.c3d675c406bf83b7.js
.venv\share\jupyter\lab\static\2563.bdd3149d69816d76.js
.venv\share\jupyter\lab\static\2600.ca62f75dcd29d303.js
.venv\share\jupyter\lab\static\2692.eee86b8138bc264e.js
.venv\share\jupyter\lab\static\2751.054be16d1de152ed.js
.venv\share\jupyter\lab\static\279.1d87a19f5d7ab5ba.js
.venv\share\jupyter\lab\static\2814.dbb035d0ef740a9d.js
.venv\share\jupyter\lab\static\2841.86506b718eec3c99.js
.venv\share\jupyter\lab\static\2857.ac62be053c711761.js
.venv\share\jupyter\lab\static\2874.ea9bd8ad31b1acb0.js
.venv\share\jupyter\lab\static\29.7a78d733ea4303ef.js
.venv\share\jupyter\lab\static\2914.93ec2ce85349bfcb.js
.venv\share\jupyter\lab\static\293.9e31f21f77925d6d.js
.venv\share\jupyter\lab\static\298.14d454ce4b32b3cb.js
.venv\share\jupyter\lab\static\2985.0927e52ba300a767.js
.venv\share\jupyter\lab\static\2bd574c5c7e65225.woff
.venv\share\jupyter\lab\static\2cfe4f053e829d1b.woff
.venv\share\jupyter\lab\static\2f11494d53a2f4fa.woff
.venv\share\jupyter\lab\static\3048300eb9b40fad.woff
.venv\share\jupyter\lab\static\3058.b4a2fce8c76a0dc7.js
.venv\share\jupyter\lab\static\3071.838fd3a7554dd171.js
.venv\share\jupyter\lab\static\3118.4862a7ce8cd88c72.js
.venv\share\jupyter\lab\static\3221.993c168647fb91ad.js
.venv\share\jupyter\lab\static\3244.fc189622bc1b7623.js
.venv\share\jupyter\lab\static\3288.0379d6d2ee2b1de4.js
.venv\share\jupyter\lab\static\3301.76c0882553a666a0.js
.venv\share\jupyter\lab\static\3312.e5f6edb28463f660.js
.venv\share\jupyter\lab\static\332e07ea2e09856e.woff
.venv\share\jupyter\lab\static\3395.deb605f5e3565fba.js
.venv\share\jupyter\lab\static\3459.387b0b56c73ca3d1.js
.venv\share\jupyter\lab\static\3481.72f0535629efba91.js
.venv\share\jupyter\lab\static\34af45641bcaf1db.woff
.venv\share\jupyter\lab\static\3502.2a088e489938b55f.js
.venv\share\jupyter\lab\static\3508.adc857c378089e63.js
.venv\share\jupyter\lab\static\3588.79c167117ee5e79a.js
.venv\share\jupyter\lab\static\364.bcb9782f2a53ddba.js
.venv\share\jupyter\lab\static\3684.a33054656643494f.js
.venv\share\jupyter\lab\static\3702.bb3bb0b9a9626bd4.js
.venv\share\jupyter\lab\static\3762.bc2173c156f5a1fe.js
.venv\share\jupyter\lab\static\3801.2a49fc8317ea8350.js
.venv\share\jupyter\lab\static\3854.c1914441ea5bae8d.js

In [43]:
from pathlib import Path

raw_path = Path(r"C:\Users\karab\PremierLeagueML\data\raw")

for season_folder in sorted(raw_path.iterdir()):
    if season_folder.is_dir():
        files = list(season_folder.glob("*.xls"))

        print("\n" + "=" * 60)
        print(season_folder.name)
        print("Number of files:", len(files))

        for file in files:
            print(" -", file.name)

============================================================
2022 PL Season
Number of files: 12
 - PL 2022 HomeAway.xls
 - PL 2022 Overall.xls
 - Squad Goalkeeping Opponent.xls
 - Squad Goalkeeping Squad.xls
 - Squad Miscellaneous Stats O.xls
 - Squad Miscellaneous Stats S.xls
 - Squad Playing Time Opponent.xls
 - Squad Playing Time S.xls
 - Squad Shooting Opponent.xls
 - Squad Shooting S.xls
 - Squad Standard Stats Opponent.xls
 - Squad Standard Stats Squad .xls

============================================================
2023 PL Season
Number of files: 12
 - Premier League 2023 HomeAway.xls
 - Premier League 2023 Overall.xls
 - Squad Goalkeeping Opponent Stats.xls
 - Squad Goalkeeping Squad Stats.xls
 - Squad Miscellaneous Stats Opponent Stats.xls
 - Squad Miscellaneous Stats Squad Stats.xls
 - Squad Playing Time Opponent Stats.xls
 - Squad Playing Time Squad Stats.xls
 - Squad Shooting Opponent stats.xls
 - Squad Standard Stats 2023.xls
 - Squad Standard Stats Opponent Stats.xls
 - Squad Sthooting Squad Stats.xls

============================================================
2024 PL Season
Number of files: 12
 - 2024 PL Season Home Away.xls
 - 2024 PL Season overall.xls
 - Squad Goalkeeping 2023-2024 Premier League Opponent Stats.xls
 - Squad Goalkeeping 2023-2024 Premier League Opponents.xls
 - Squad Goalkeeping 2023-2024 Premier League.xls
 - Squad Miscellaneous Stats 2023-2024 Premier League Opponents.xls
 - Squad Miscellaneous Stats 2023-2024 Premier League.xls
 - Squad Playing Time 2023-2024 Premier Leagu Opponents.xls
 - Squad Playing Time 2023-2024 Premier League.xls
 - Squad Shooting 2023-2024 Premier League.xls
 - Squad Standard Stats 2023-2024 Premier League Opponet Stats.xls
 - Squad Standard Stats 2023-2024 Premier League.xls

============================================================
2025 PL Season
Number of files: 12
 - Premier League home and away .xls
 - Premier League Overall.xls
 - Squad Goalkeeping 2024-2025 Premier League.xls
 - Squad Goalkeeping Opponent.xls
 - Squad Miscellaneous Stats 2024-2025 Premier League.xls
 - Squad Miscellaneous Stats Opponent.xls
 - Squad Playing Time 2024-2025 Premier League.xls
 - Squad Playing Time Opponent.xls
 - Squad Shooting 2024-2025 Premier League .xls
 - Squad Shooting Opponent .xls
 - Squad Standard Stats 2024-2025 Premier League opponent stats.xls
 - Squad Standard Stats 2024-2025 Premier League.xls

============================================================
2026 PL Season
Number of files: 12
 - Premier League 2026 Overall.xls
 - Premier League Home,away.xls
 - Squad goalkeeping 2026 PL.xls
 - Squad Goalkeeping Opponent.xls
 - Squad Miscellaneous Stats 2025-2026 Premier Leag.xls
 - Squad Miscellaneous Stats Opponent.xls
 - Squad Playing Time 2025-2026 Premier League.xls
 - Squad Playing Time Opponent.xls
 - Squad Shooting 2025-2026 Premier League.xls
 - Squad Shooting Opponent .xls
 - Squad Standard Stats 2025-2026 Premier League.xls
 - Squad Standard Stats Opponent.xls

In [44]:
from pathlib import Path
import pandas as pd

raw_path = Path(r"C:\Users\karab\PremierLeagueML\data\raw")

season_summary = {}

for season_folder in sorted(raw_path.iterdir()):

    if not season_folder.is_dir():
        continue

    print("\n" + "=" * 70)
    print(season_folder.name)
    print("=" * 70)

    season_summary[season_folder.name] = {}

    for file in sorted(season_folder.glob("*.xls")):

        try:
            tables = pd.read_html(file)

            if not tables:
                print(f"{file.name}: NO TABLE")
                continue

            df = tables[0]

            # Flatten MultiIndex columns
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = [
                    "_".join(
                        str(level).strip()
                        for level in col
                        if str(level).strip() != "nan"
                    )
                    for col in df.columns
                ]

            # Find Squad column
            squad_col = None

            for col in df.columns:
                if str(col).strip() == "Squad":
                    squad_col = col
                    break

            if squad_col:

                teams = (
                    df[squad_col]
                    .astype(str)
                    .str.strip()
                    .tolist()
                )

                season_summary[season_folder.name][file.name] = {
                    "rows": len(df),
                    "columns": len(df.columns),
                    "teams": teams
                }

                print(
                    f"{file.name:<60} "
                    f"Rows: {len(df):<3} "
                    f"Columns: {len(df.columns):<3}"
                )

            else:
                print(f"{file.name}: Squad column not found")

        except Exception as e:
            print(f"{file.name}: ERROR -> {e}")

======================================================================
2022 PL Season
======================================================================
PL 2022 HomeAway.xls: Squad column not found
PL 2022 Overall.xls                                          Rows: 20  Columns: 15
Squad Goalkeeping Opponent.xls: Squad column not found
Squad Goalkeeping Squad.xls: Squad column not found
Squad Miscellaneous Stats O.xls: Squad column not found
Squad Miscellaneous Stats S.xls: Squad column not found
Squad Playing Time Opponent.xls: Squad column not found
Squad Playing Time S.xls: Squad column not found
Squad Shooting Opponent.xls: Squad column not found
Squad Shooting S.xls: Squad column not found
Squad Standard Stats Opponent.xls: Squad column not found
Squad Standard Stats Squad .xls: Squad column not found

======================================================================
2023 PL Season
======================================================================
Premier League 2023 HomeAway.xls: Squad column not found
Premier League 2023 Overall.xls                              Rows: 20  Columns: 15
Squad Goalkeeping Opponent Stats.xls: Squad column not found
Squad Goalkeeping Squad Stats.xls: Squad column not found
Squad Miscellaneous Stats Opponent Stats.xls: Squad column not found
Squad Miscellaneous Stats Squad Stats.xls: Squad column not found
Squad Playing Time Opponent Stats.xls: Squad column not found
Squad Playing Time Squad Stats.xls: Squad column not found
Squad Shooting Opponent stats.xls: Squad column not found
Squad Standard Stats 2023.xls: Squad column not found
Squad Standard Stats Opponent Stats.xls: Squad column not found
Squad Sthooting Squad Stats.xls: Squad column not found

======================================================================
2024 PL Season
======================================================================
2024 PL Season Home Away.xls: Squad column not found
2024 PL Season overall.xls                                   Rows: 20  Columns: 15
Squad Goalkeeping 2023-2024 Premier League Opponent Stats.xls: Squad column not found
Squad Goalkeeping 2023-2024 Premier League Opponents.xls: Squad column not found
Squad Goalkeeping 2023-2024 Premier League.xls: Squad column not found
Squad Miscellaneous Stats 2023-2024 Premier League Opponents.xls: Squad column not found
Squad Miscellaneous Stats 2023-2024 Premier League.xls: Squad column not found
Squad Playing Time 2023-2024 Premier Leagu Opponents.xls: Squad column not found
Squad Playing Time 2023-2024 Premier League.xls: Squad column not found
Squad Shooting 2023-2024 Premier League.xls: Squad column not found
Squad Standard Stats 2023-2024 Premier League Opponet Stats.xls: Squad column not found
Squad Standard Stats 2023-2024 Premier League.xls: Squad column not found

======================================================================
2025 PL Season
======================================================================
Premier League home and away .xls: Squad column not found
Premier League Overall.xls                                   Rows: 20  Columns: 15
Squad Goalkeeping 2024-2025 Premier League.xls: Squad column not found
Squad Goalkeeping Opponent.xls: Squad column not found
Squad Miscellaneous Stats 2024-2025 Premier League.xls: Squad column not found
Squad Miscellaneous Stats Opponent.xls: Squad column not found
Squad Playing Time 2024-2025 Premier League.xls: Squad column not found
Squad Playing Time Opponent.xls: Squad column not found
Squad Shooting 2024-2025 Premier League .xls: Squad column not found
Squad Shooting Opponent .xls: Squad column not found
Squad Standard Stats 2024-2025 Premier League opponent stats.xls: Squad column not found
Squad Standard Stats 2024-2025 Premier League.xls: Squad column not found

======================================================================
2026 PL Season
======================================================================
Premier League 2026 Overall.xls                              Rows: 20  Columns: 15
Premier League Home,away.xls: Squad column not found
Squad goalkeeping 2026 PL.xls: Squad column not found
Squad Goalkeeping Opponent.xls: Squad column not found
Squad Miscellaneous Stats 2025-2026 Premier Leag.xls: Squad column not found
Squad Miscellaneous Stats Opponent.xls: Squad column not found
Squad Playing Time 2025-2026 Premier League.xls: Squad column not found
Squad Playing Time Opponent.xls: Squad column not found
Squad Shooting 2025-2026 Premier League.xls: Squad column not found
Squad Shooting Opponent .xls: Squad column not found
Squad Standard Stats 2025-2026 Premier League.xls: Squad column not found
Squad Standard Stats Opponent.xls: Squad column not found

In [45]:
file = Path(r"C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Standard Stats Squad .xls")

tables = pd.read_html(file)

df = tables[0]

print(df.columns)

MultiIndex([('Unnamed: 0_level_0',  'Squad'),
            ('Unnamed: 1_level_0',   '# Pl'),
            ('Unnamed: 2_level_0',    'Age'),
            ('Unnamed: 3_level_0',   'Poss'),
            (      'Playing Time',     'MP'),
            (      'Playing Time', 'Starts'),
            (      'Playing Time',    'Min'),
            (      'Playing Time',    '90s'),
            (       'Performance',    'Gls'),
            (       'Performance',    'Ast'),
            (       'Performance',    'G+A'),
            (       'Performance',   'G-PK'),
            (       'Performance',     'PK'),
            (       'Performance',  'PKatt'),
            (       'Performance',   'CrdY'),
            (       'Performance',   'CrdR'),
            (    'Per 90 Minutes',    'Gls'),
            (    'Per 90 Minutes',    'Ast'),
            (    'Per 90 Minutes',    'G+A'),
            (    'Per 90 Minutes',   'G-PK'),
            (    'Per 90 Minutes', 'G+A-PK')],
           )

In [46]:
print(type(df.columns))

<class 'pandas.MultiIndex'>

In [47]:
print(df.head())

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
               Squad               # Pl                Age               Poss
0            Arsenal                 27               24.4               52.8
1        Aston Villa                 31               26.1               46.5
2          Brentford                 29               25.4               44.8
3           Brighton                 26               26.2               54.4
4            Burnley                 23               28.5               40.2

  Playing Time                    Performance      ...                     \
            MP Starts   Min   90s         Gls Ast  ... G-PK PK PKatt CrdY
0           38    418  3420  38.0          60  41  ...   55  5     8   67
1           38    418  3420  38.0          50  42  ...   47  3     3   81
2           38    418  3420  38.0          46  33  ...   40  6     6   65
3           38    418  3420  38.0          40  30  ...   36  4     7   72
4           38    418  3420  38.0          32  26  ...   31  1     2   68

       Per 90 Minutes
  CrdR            Gls   Ast   G+A  G-PK G+A-PK
0    4           1.58  1.08  2.66  1.45   2.53
1    2           1.32  1.11  2.42  1.24   2.34
2    3           1.21  0.87  2.08  1.05   1.92
3    2           1.05  0.79  1.84  0.95   1.74
4    2           0.84  0.68  1.53  0.82   1.50

[5 rows x 21 columns]

In [48]:
col == "Squad"

False

In [49]:
("Unnamed: 0_level_0", "Squad")

('Unnamed: 0_level_0', 'Squad')

In [50]:
# Flatten the MultiIndex columns

if isinstance(df.columns, pd.MultiIndex):

    new_columns = []

    for col in df.columns:
        # Take the meaningful part of each header
        levels = [
            str(level).strip()
            for level in col
            if str(level).strip() not in ["", "nan"]
        ]

        # Remove Unnamed levels
        meaningful = [
            level for level in levels
            if not level.startswith("Unnamed:")
        ]

        # If there is a meaningful level, use it
        if meaningful:
            new_columns.append("_".join(meaningful))
        else:
            new_columns.append("_".join(levels))

    df.columns = new_columns

else:
    df.columns = [
        str(col).strip()
        for col in df.columns
    ]

print(df.columns.tolist())

['Squad', '# Pl', 'Age', 'Poss', 'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s', 'Performance_Gls', 'Performance_Ast', 'Performance_G+A', 'Performance_G-PK', 'Performance_PK', 'Performance_PKatt', 'Performance_CrdY', 'Performance_CrdR', 'Per 90 Minutes_Gls', 'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A', 'Per 90 Minutes_G-PK', 'Per 90 Minutes_G+A-PK']

In [51]:
print("Squad" in df.columns)

True

In [52]:
print(df["Squad"].tolist())

['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Norwich City', 'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves']

In [53]:
def flatten_fbref_columns(df):
    df = df.copy()

    if isinstance(df.columns, pd.MultiIndex):

        new_columns = []

        for col in df.columns:

            levels = [
                str(level).strip()
                for level in col
                if str(level).strip() not in ["", "nan"]
            ]

            meaningful = [
                level
                for level in levels
                if not level.startswith("Unnamed:")
            ]

            if meaningful:
                new_columns.append("_".join(meaningful))
            else:
                new_columns.append("_".join(levels))

        df.columns = new_columns

    else:
        df.columns = [
            str(col).strip()
            for col in df.columns
        ]

    return df

In [54]:
from pathlib import Path
import pandas as pd

raw_path = Path(r"C:\Users\karab\PremierLeagueML\data\raw")

for season_folder in sorted(raw_path.iterdir()):

    if not season_folder.is_dir():
        continue

    print("\n" + "=" * 70)
    print(season_folder.name)
    print("=" * 70)

    for file in sorted(season_folder.glob("*.xls")):

        try:
            tables = pd.read_html(file)

            df = flatten_fbref_columns(tables[0])

            if "Squad" not in df.columns:
                print(f"❌ {file.name} → Squad NOT FOUND")
                continue

            teams = (
                df["Squad"]
                .astype(str)
                .str.strip()
            )

            print(
                f"✓ {file.name:<55}"
                f"Rows: {len(df):<3}"
                f"Columns: {len(df.columns):<3}"
                f"Teams: {teams.nunique()}"
            )

        except Exception as e:

            print(
                f"❌ {file.name} → ERROR: {e}"
            )

======================================================================
2022 PL Season
======================================================================
✓ PL 2022 HomeAway.xls                                   Rows: 20 Columns: 20 Teams: 20
✓ PL 2022 Overall.xls                                    Rows: 20 Columns: 15 Teams: 20
✓ Squad Goalkeeping Opponent.xls                         Rows: 20 Columns: 21 Teams: 20
✓ Squad Goalkeeping Squad.xls                            Rows: 20 Columns: 21 Teams: 20
✓ Squad Miscellaneous Stats O.xls                        Rows: 20 Columns: 15 Teams: 20
✓ Squad Miscellaneous Stats S.xls                        Rows: 20 Columns: 15 Teams: 20
✓ Squad Playing Time Opponent.xls                        Rows: 20 Columns: 19 Teams: 20
✓ Squad Playing Time S.xls                               Rows: 20 Columns: 19 Teams: 20
✓ Squad Shooting Opponent.xls                            Rows: 20 Columns: 13 Teams: 20
✓ Squad Shooting S.xls                                   Rows: 20 Columns: 13 Teams: 20
✓ Squad Standard Stats Opponent.xls                      Rows: 20 Columns: 21 Teams: 20
✓ Squad Standard Stats Squad .xls                        Rows: 20 Columns: 21 Teams: 20

======================================================================
2023 PL Season
======================================================================
✓ Premier League 2023 HomeAway.xls                       Rows: 20 Columns: 20 Teams: 20
✓ Premier League 2023 Overall.xls                        Rows: 20 Columns: 15 Teams: 20
✓ Squad Goalkeeping Opponent Stats.xls                   Rows: 20 Columns: 21 Teams: 20
✓ Squad Goalkeeping Squad Stats.xls                      Rows: 20 Columns: 21 Teams: 20
✓ Squad Miscellaneous Stats Opponent Stats.xls           Rows: 20 Columns: 15 Teams: 20
✓ Squad Miscellaneous Stats Squad Stats.xls              Rows: 20 Columns: 15 Teams: 20
✓ Squad Playing Time Opponent Stats.xls                  Rows: 20 Columns: 19 Teams: 20
✓ Squad Playing Time Squad Stats.xls                     Rows: 20 Columns: 19 Teams: 20
✓ Squad Shooting Opponent stats.xls                      Rows: 20 Columns: 13 Teams: 20
✓ Squad Standard Stats 2023.xls                          Rows: 20 Columns: 21 Teams: 20
✓ Squad Standard Stats Opponent Stats.xls                Rows: 20 Columns: 21 Teams: 20
✓ Squad Sthooting Squad Stats.xls                        Rows: 20 Columns: 13 Teams: 20

======================================================================
2024 PL Season
======================================================================
✓ 2024 PL Season Home Away.xls                           Rows: 20 Columns: 20 Teams: 20
✓ 2024 PL Season overall.xls                             Rows: 20 Columns: 15 Teams: 20
✓ Squad Goalkeeping 2023-2024 Premier League Opponent Stats.xlsRows: 20 Columns: 21 Teams: 20
✓ Squad Goalkeeping 2023-2024 Premier League Opponents.xlsRows: 20 Columns: 13 Teams: 20
✓ Squad Goalkeeping 2023-2024 Premier League.xls         Rows: 20 Columns: 21 Teams: 20
✓ Squad Miscellaneous Stats 2023-2024 Premier League Opponents.xlsRows: 20 Columns: 15 Teams: 20
✓ Squad Miscellaneous Stats 2023-2024 Premier League.xls Rows: 20 Columns: 15 Teams: 20
✓ Squad Playing Time 2023-2024 Premier Leagu Opponents.xlsRows: 20 Columns: 19 Teams: 20
✓ Squad Playing Time 2023-2024 Premier League.xls        Rows: 20 Columns: 19 Teams: 20
✓ Squad Shooting 2023-2024 Premier League.xls            Rows: 20 Columns: 13 Teams: 20
✓ Squad Standard Stats 2023-2024 Premier League Opponet Stats.xlsRows: 20 Columns: 21 Teams: 20
✓ Squad Standard Stats 2023-2024 Premier League.xls      Rows: 20 Columns: 21 Teams: 20

======================================================================
2025 PL Season
======================================================================
✓ Premier League home and away .xls                      Rows: 20 Columns: 20 Teams: 20
✓ Premier League Overall.xls                             Rows: 20 Columns: 15 Teams: 20
✓ Squad Goalkeeping 2024-2025 Premier League.xls         Rows: 20 Columns: 21 Teams: 20
✓ Squad Goalkeeping Opponent.xls                         Rows: 20 Columns: 21 Teams: 20
✓ Squad Miscellaneous Stats 2024-2025 Premier League.xls Rows: 20 Columns: 15 Teams: 20
✓ Squad Miscellaneous Stats Opponent.xls                 Rows: 20 Columns: 15 Teams: 20
✓ Squad Playing Time 2024-2025 Premier League.xls        Rows: 20 Columns: 19 Teams: 20
✓ Squad Playing Time Opponent.xls                        Rows: 20 Columns: 19 Teams: 20
✓ Squad Shooting 2024-2025 Premier League .xls           Rows: 20 Columns: 13 Teams: 20
✓ Squad Shooting Opponent .xls                           Rows: 20 Columns: 13 Teams: 20
✓ Squad Standard Stats 2024-2025 Premier League opponent stats.xlsRows: 20 Columns: 21 Teams: 20
✓ Squad Standard Stats 2024-2025 Premier League.xls      Rows: 20 Columns: 21 Teams: 20

======================================================================
2026 PL Season
======================================================================
✓ Premier League 2026 Overall.xls                        Rows: 20 Columns: 15 Teams: 20
✓ Premier League Home,away.xls                           Rows: 20 Columns: 20 Teams: 20
✓ Squad goalkeeping 2026 PL.xls                          Rows: 20 Columns: 21 Teams: 20
✓ Squad Goalkeeping Opponent.xls                         Rows: 20 Columns: 21 Teams: 20
✓ Squad Miscellaneous Stats 2025-2026 Premier Leag.xls   Rows: 20 Columns: 15 Teams: 20
✓ Squad Miscellaneous Stats Opponent.xls                 Rows: 20 Columns: 15 Teams: 20
✓ Squad Playing Time 2025-2026 Premier League.xls        Rows: 20 Columns: 19 Teams: 20
✓ Squad Playing Time Opponent.xls                        Rows: 20 Columns: 19 Teams: 20
✓ Squad Shooting 2025-2026 Premier League.xls            Rows: 20 Columns: 13 Teams: 20
✓ Squad Shooting Opponent .xls                           Rows: 20 Columns: 21 Teams: 20
✓ Squad Standard Stats 2025-2026 Premier League.xls      Rows: 20 Columns: 21 Teams: 20
✓ Squad Standard Stats Opponent.xls                      Rows: 20 Columns: 21 Teams: 20

In [55]:
from pathlib import Path
import pandas as pd

raw_path = Path(r"C:\Users\karab\PremierLeagueML\data\raw")


def flatten_fbref_columns(df):

    df = df.copy()

    if isinstance(df.columns, pd.MultiIndex):

        new_columns = []

        for col in df.columns:

            levels = [
                str(level).strip()
                for level in col
                if str(level).strip() not in ["", "nan"]
            ]

            meaningful = [
                level
                for level in levels
                if not level.startswith("Unnamed:")
            ]

            if meaningful:
                new_columns.append("_".join(meaningful))
            else:
                new_columns.append("_".join(levels))

        df.columns = new_columns

    else:
        df.columns = [
            str(col).strip()
            for col in df.columns
        ]

    return df


for season_folder in sorted(raw_path.iterdir()):

    if not season_folder.is_dir():
        continue

    print("\n" + "=" * 70)
    print(season_folder.name)
    print("=" * 70)

    # Find the Overall file
    overall_file = None

    for file in season_folder.glob("*.xls"):

        if "Overall" in file.name:
            overall_file = file
            break

    if overall_file is None:
        print("❌ Overall file not found")
        continue

    overall = flatten_fbref_columns(
        pd.read_html(overall_file)[0]
    )

    overall_teams = set(
        overall["Squad"]
        .astype(str)
        .str.strip()
    )

    print("Overall teams:", len(overall_teams))

    # Compare every file
    for file in sorted(season_folder.glob("*.xls")):

        df = flatten_fbref_columns(
            pd.read_html(file)[0]
        )

        if "Squad" not in df.columns:
            print(f"❌ {file.name}: no Squad column")
            continue

        teams = set(
            df["Squad"]
            .astype(str)
            .str.strip()
        )

        missing = overall_teams - teams
        extra = teams - overall_teams

        if not missing and not extra:

            print(f"✓ {file.name}")

        else:

            print(f"⚠ {file.name}")

            if missing:
                print("   Missing:", sorted(missing))

            if extra:
                print("   Extra:", sorted(extra))

======================================================================
2022 PL Season
======================================================================
Overall teams: 20
✓ PL 2022 HomeAway.xls
✓ PL 2022 Overall.xls
⚠ Squad Goalkeeping Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Norwich City', 'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Brentford', 'vs Brighton', 'vs Burnley', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Leeds United', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Norwich City', 'vs Southampton', 'vs Tottenham', 'vs Watford', 'vs West Ham', 'vs Wolves']
✓ Squad Goalkeeping Squad.xls
⚠ Squad Miscellaneous Stats O.xls
   Missing: ['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Norwich City', 'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Brentford', 'vs Brighton', 'vs Burnley', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Leeds United', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Norwich City', 'vs Southampton', 'vs Tottenham', 'vs Watford', 'vs West Ham', 'vs Wolves']
✓ Squad Miscellaneous Stats S.xls
⚠ Squad Playing Time Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Norwich City', 'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Brentford', 'vs Brighton', 'vs Burnley', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Leeds United', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Norwich City', 'vs Southampton', 'vs Tottenham', 'vs Watford', 'vs West Ham', 'vs Wolves']
✓ Squad Playing Time S.xls
⚠ Squad Shooting Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Norwich City', 'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Brentford', 'vs Brighton', 'vs Burnley', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Leeds United', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Norwich City', 'vs Southampton', 'vs Tottenham', 'vs Watford', 'vs West Ham', 'vs Wolves']
✓ Squad Shooting S.xls
⚠ Squad Standard Stats Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Norwich City', 'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Brentford', 'vs Brighton', 'vs Burnley', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Leeds United', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Norwich City', 'vs Southampton', 'vs Tottenham', 'vs Watford', 'vs West Ham', 'vs Wolves']
✓ Squad Standard Stats Squad .xls

======================================================================
2023 PL Season
======================================================================
Overall teams: 20
✓ Premier League 2023 HomeAway.xls
✓ Premier League 2023 Overall.xls
⚠ Squad Goalkeeping Opponent Stats.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Leeds United', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Goalkeeping Squad Stats.xls
⚠ Squad Miscellaneous Stats Opponent Stats.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Leeds United', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Miscellaneous Stats Squad Stats.xls
⚠ Squad Playing Time Opponent Stats.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Leeds United', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Playing Time Squad Stats.xls
⚠ Squad Shooting Opponent stats.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Leeds United', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Standard Stats 2023.xls
⚠ Squad Standard Stats Opponent Stats.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds United', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Leeds United', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Sthooting Squad Stats.xls

======================================================================
2024 PL Season
======================================================================
❌ Overall file not found

======================================================================
2025 PL Season
======================================================================
Overall teams: 20
✓ Premier League home and away .xls
✓ Premier League Overall.xls
✓ Squad Goalkeeping 2024-2025 Premier League.xls
⚠ Squad Goalkeeping Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Ipswich Town', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Miscellaneous Stats 2024-2025 Premier League.xls
⚠ Squad Miscellaneous Stats Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Ipswich Town', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Playing Time 2024-2025 Premier League.xls
⚠ Squad Playing Time Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Ipswich Town', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Shooting 2024-2025 Premier League .xls
⚠ Squad Shooting Opponent .xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Ipswich Town', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
⚠ Squad Standard Stats 2024-2025 Premier League opponent stats.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Ipswich Town', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Standard Stats 2024-2025 Premier League.xls

======================================================================
2026 PL Season
======================================================================
Overall teams: 20
✓ Premier League 2026 Overall.xls
✓ Premier League Home,away.xls
✓ Squad goalkeeping 2026 PL.xls
⚠ Squad Goalkeeping Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds United', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Sunderland', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Burnley', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Leeds United', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Sunderland', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Miscellaneous Stats 2025-2026 Premier Leag.xls
⚠ Squad Miscellaneous Stats Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds United', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Sunderland', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Burnley', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Leeds United', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Sunderland', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Playing Time 2025-2026 Premier League.xls
⚠ Squad Playing Time Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds United', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Sunderland', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Burnley', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Leeds United', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Sunderland', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Shooting 2025-2026 Premier League.xls
⚠ Squad Shooting Opponent .xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds United', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Sunderland', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Burnley', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Leeds United', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Sunderland', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ Squad Standard Stats 2025-2026 Premier League.xls
⚠ Squad Standard Stats Opponent.xls
   Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds United', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Sunderland', 'Tottenham', 'West Ham', 'Wolves']
   Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Burnley', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Leeds United', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Sunderland', 'vs Tottenham', 'vs West Ham', 'vs Wolves']

In [56]:
for season_folder in sorted(raw_path.iterdir()):

    if not season_folder.is_dir():
        continue

    print("\n" + "=" * 70)
    print(season_folder.name)
    print("=" * 70)

    # Find Overall file
    overall_file = None

    for file in season_folder.glob("*.xls"):
        if "Overall" in file.name:
            overall_file = file
            break

    if overall_file is None:
        print("❌ Overall file not found")
        continue

    overall = flatten_fbref_columns(
        pd.read_html(overall_file)[0]
    )

    overall_teams = set(
        overall["Squad"]
        .astype(str)
        .str.strip()
    )

    print("Overall teams:", len(overall_teams))

    for file in sorted(season_folder.glob("*.xls")):

        df = flatten_fbref_columns(
            pd.read_html(file)[0]
        )

        if "Squad" not in df.columns:
            print(f"❌ {file.name}: no Squad")
            continue

        teams = set(
            df["Squad"]
            .astype(str)
            .str.strip()
        )

        # Detect opponent tables
        is_opponent = any(
            word in file.name.lower()
            for word in ["opponent", " opp", " o."]
        )

        if is_opponent:

            teams_normalized = {
                team.replace("vs ", "", 1).strip()
                for team in teams
            }

        else:

            teams_normalized = teams

        missing = overall_teams - teams_normalized
        extra = teams_normalized - overall_teams

        if not missing and not extra:

            if is_opponent:
                print(f"✓ {file.name} (Opponent)")
            else:
                print(f"✓ {file.name}")

        else:

            print(f"⚠ {file.name}")

            if missing:
                print("   Missing:", sorted(missing))

            if extra:
                print("   Extra:", sorted(extra))

======================================================================
2022 PL Season
======================================================================
Overall teams: 20
✓ PL 2022 HomeAway.xls
✓ PL 2022 Overall.xls
✓ Squad Goalkeeping Opponent.xls (Opponent)
✓ Squad Goalkeeping Squad.xls
✓ Squad Miscellaneous Stats O.xls (Opponent)
✓ Squad Miscellaneous Stats S.xls
✓ Squad Playing Time Opponent.xls (Opponent)
✓ Squad Playing Time S.xls
✓ Squad Shooting Opponent.xls (Opponent)
✓ Squad Shooting S.xls
✓ Squad Standard Stats Opponent.xls (Opponent)
✓ Squad Standard Stats Squad .xls

======================================================================
2023 PL Season
======================================================================
Overall teams: 20
✓ Premier League 2023 HomeAway.xls
✓ Premier League 2023 Overall.xls
✓ Squad Goalkeeping Opponent Stats.xls (Opponent)
✓ Squad Goalkeeping Squad Stats.xls
✓ Squad Miscellaneous Stats Opponent Stats.xls (Opponent)
✓ Squad Miscellaneous Stats Squad Stats.xls
✓ Squad Playing Time Opponent Stats.xls (Opponent)
✓ Squad Playing Time Squad Stats.xls
✓ Squad Shooting Opponent stats.xls (Opponent)
✓ Squad Standard Stats 2023.xls
✓ Squad Standard Stats Opponent Stats.xls (Opponent)
✓ Squad Sthooting Squad Stats.xls

======================================================================
2024 PL Season
======================================================================
❌ Overall file not found

======================================================================
2025 PL Season
======================================================================
Overall teams: 20
✓ Premier League home and away .xls
✓ Premier League Overall.xls
✓ Squad Goalkeeping 2024-2025 Premier League.xls
✓ Squad Goalkeeping Opponent.xls (Opponent)
✓ Squad Miscellaneous Stats 2024-2025 Premier League.xls
✓ Squad Miscellaneous Stats Opponent.xls (Opponent)
✓ Squad Playing Time 2024-2025 Premier League.xls
✓ Squad Playing Time Opponent.xls (Opponent)
✓ Squad Shooting 2024-2025 Premier League .xls
✓ Squad Shooting Opponent .xls (Opponent)
✓ Squad Standard Stats 2024-2025 Premier League opponent stats.xls (Opponent)
✓ Squad Standard Stats 2024-2025 Premier League.xls

======================================================================
2026 PL Season
======================================================================
Overall teams: 20
✓ Premier League 2026 Overall.xls
✓ Premier League Home,away.xls
✓ Squad goalkeeping 2026 PL.xls
✓ Squad Goalkeeping Opponent.xls (Opponent)
✓ Squad Miscellaneous Stats 2025-2026 Premier Leag.xls
✓ Squad Miscellaneous Stats Opponent.xls (Opponent)
✓ Squad Playing Time 2025-2026 Premier League.xls
✓ Squad Playing Time Opponent.xls (Opponent)
✓ Squad Shooting 2025-2026 Premier League.xls
✓ Squad Shooting Opponent .xls (Opponent)
✓ Squad Standard Stats 2025-2026 Premier League.xls
✓ Squad Standard Stats Opponent.xls (Opponent)

In [57]:
from pathlib import Path
import pandas as pd

raw_path = Path(r"C:\Users\karab\PremierLeagueML\data\raw")


def flatten_fbref_columns(df):

    df = df.copy()

    if isinstance(df.columns, pd.MultiIndex):

        new_columns = []

        for col in df.columns:

            levels = [
                str(level).strip()
                for level in col
                if str(level).strip() not in ["", "nan"]
            ]

            meaningful = [
                level
                for level in levels
                if not level.startswith("Unnamed:")
            ]

            if meaningful:
                new_columns.append("_".join(meaningful))
            else:
                new_columns.append("_".join(levels))

        df.columns = new_columns

    else:
        df.columns = [
            str(col).strip()
            for col in df.columns
        ]

    return df

In [58]:
column_inventory = {}

for season_folder in sorted(raw_path.iterdir()):

    if not season_folder.is_dir():
        continue

    column_inventory[season_folder.name] = {}

    for file in sorted(season_folder.glob("*.xls")):

        df = flatten_fbref_columns(
            pd.read_html(file)[0]
        )

        column_inventory[season_folder.name][file.name] = (
            df.columns.tolist()
        )

In [59]:
for season, files in column_inventory.items():

    print("\n" + "=" * 80)
    print(season)
    print("=" * 80)

    for filename, columns in files.items():

        print(f"\n{filename}")
        print("-" * 80)

        for i, column in enumerate(columns, start=1):

            print(f"{i:>3}. {column}")

================================================================================
2022 PL Season
================================================================================

PL 2022 HomeAway.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. Home_MP
  4. Home_W
  5. Home_D
  6. Home_L
  7. Home_GF
  8. Home_GA
  9. Home_GD
 10. Home_Pts
 11. Home_Pts/MP
 12. Away_MP
 13. Away_W
 14. Away_D
 15. Away_L
 16. Away_GF
 17. Away_GA
 18. Away_GD
 19. Away_Pts
 20. Away_Pts/MP

PL 2022 Overall.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. MP
  4. W
  5. D
  6. L
  7. GF
  8. GA
  9. GD
 10. Pts
 11. Pts/MP
 12. Attendance
 13. Top Team Scorer
 14. Goalkeeper
 15. Notes

Squad Goalkeeping Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

Squad Goalkeeping Squad.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

Squad Miscellaneous Stats O.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

Squad Miscellaneous Stats S.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

Squad Playing Time Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

Squad Playing Time S.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

Squad Shooting Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

Squad Shooting S.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

Squad Standard Stats Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

Squad Standard Stats Squad .xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

================================================================================
2023 PL Season
================================================================================

Premier League 2023 HomeAway.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. Home_MP
  4. Home_W
  5. Home_D
  6. Home_L
  7. Home_GF
  8. Home_GA
  9. Home_GD
 10. Home_Pts
 11. Home_Pts/MP
 12. Away_MP
 13. Away_W
 14. Away_D
 15. Away_L
 16. Away_GF
 17. Away_GA
 18. Away_GD
 19. Away_Pts
 20. Away_Pts/MP

Premier League 2023 Overall.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. MP
  4. W
  5. D
  6. L
  7. GF
  8. GA
  9. GD
 10. Pts
 11. Pts/MP
 12. Attendance
 13. Top Team Scorer
 14. Goalkeeper
 15. Notes

Squad Goalkeeping Opponent Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

Squad Goalkeeping Squad Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

Squad Miscellaneous Stats Opponent Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

Squad Miscellaneous Stats Squad Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

Squad Playing Time Opponent Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

Squad Playing Time Squad Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

Squad Shooting Opponent stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

Squad Standard Stats 2023.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

Squad Standard Stats Opponent Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

Squad Sthooting Squad Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

================================================================================
2024 PL Season
================================================================================

2024 PL Season Home Away.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. Home_MP
  4. Home_W
  5. Home_D
  6. Home_L
  7. Home_GF
  8. Home_GA
  9. Home_GD
 10. Home_Pts
 11. Home_Pts/MP
 12. Away_MP
 13. Away_W
 14. Away_D
 15. Away_L
 16. Away_GF
 17. Away_GA
 18. Away_GD
 19. Away_Pts
 20. Away_Pts/MP

2024 PL Season overall.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. MP
  4. W
  5. D
  6. L
  7. GF
  8. GA
  9. GD
 10. Pts
 11. Pts/MP
 12. Attendance
 13. Top Team Scorer
 14. Goalkeeper
 15. Notes

Squad Goalkeeping 2023-2024 Premier League Opponent Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

Squad Goalkeeping 2023-2024 Premier League Opponents.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

Squad Goalkeeping 2023-2024 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

Squad Miscellaneous Stats 2023-2024 Premier League Opponents.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

Squad Miscellaneous Stats 2023-2024 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

Squad Playing Time 2023-2024 Premier Leagu Opponents.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

Squad Playing Time 2023-2024 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

Squad Shooting 2023-2024 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

Squad Standard Stats 2023-2024 Premier League Opponet Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

Squad Standard Stats 2023-2024 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

================================================================================
2025 PL Season
================================================================================

Premier League home and away .xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. Home_MP
  4. Home_W
  5. Home_D
  6. Home_L
  7. Home_GF
  8. Home_GA
  9. Home_GD
 10. Home_Pts
 11. Home_Pts/MP
 12. Away_MP
 13. Away_W
 14. Away_D
 15. Away_L
 16. Away_GF
 17. Away_GA
 18. Away_GD
 19. Away_Pts
 20. Away_Pts/MP

Premier League Overall.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. MP
  4. W
  5. D
  6. L
  7. GF
  8. GA
  9. GD
 10. Pts
 11. Pts/MP
 12. Attendance
 13. Top Team Scorer
 14. Goalkeeper
 15. Notes

Squad Goalkeeping 2024-2025 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

Squad Goalkeeping Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

Squad Miscellaneous Stats 2024-2025 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

Squad Miscellaneous Stats Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

Squad Playing Time 2024-2025 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

Squad Playing Time Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP

In [60]:
from pathlib import Path
import pandas as pd

raw_path = Path(r"C:\Users\karab\PremierLeagueML\data\raw")


def flatten_fbref_columns(df):
    """
    Convert FBref's MultiIndex columns into simple names.
    Example:
        ('Performance', 'Gls')
    becomes:
        'Performance_Gls'
    """

    df = df.copy()

    if isinstance(df.columns, pd.MultiIndex):

        new_columns = []

        for col in df.columns:

            levels = [
                str(level).strip()
                for level in col
                if str(level).strip() not in ["", "nan"]
            ]

            # Remove meaningless Unnamed levels
            meaningful = [
                level
                for level in levels
                if not level.startswith("Unnamed:")
            ]

            if meaningful:
                new_columns.append("_".join(meaningful))
            else:
                new_columns.append("_".join(levels))

        df.columns = new_columns

    else:

        df.columns = [
            str(col).strip()
            for col in df.columns
        ]

    return df


# ============================================================
# PRINT COLUMN INVENTORY
# ============================================================

for season_folder in sorted(raw_path.iterdir()):

    if not season_folder.is_dir():
        continue

    print("\n")
    print("=" * 100)
    print(f"SEASON: {season_folder.name}")
    print("=" * 100)

    for file in sorted(season_folder.glob("*.xls")):

        try:

            # Read FBref HTML disguised as XLS
            tables = pd.read_html(file)

            if not tables:
                print(f"\n❌ {file.name}: No table found")
                continue

            df = flatten_fbref_columns(tables[0])

            print("\n" + "-" * 100)
            print(file.name)
            print("-" * 100)

            print(f"Rows: {df.shape[0]}")
            print(f"Columns: {df.shape[1]}")

            print("\nCOLUMN LIST:")

            for i, column in enumerate(df.columns, start=1):
                print(f"{i:>3}. {column}")

        except Exception as e:

            print(f"\n❌ ERROR: {file.name}")
            print(f"   {e}")

====================================================================================================
SEASON: 2022 PL Season
====================================================================================================

----------------------------------------------------------------------------------------------------
PL 2022 HomeAway.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 20

COLUMN LIST:
  1. Rk
  2. Squad
  3. Home_MP
  4. Home_W
  5. Home_D
  6. Home_L
  7. Home_GF
  8. Home_GA
  9. Home_GD
 10. Home_Pts
 11. Home_Pts/MP
 12. Away_MP
 13. Away_W
 14. Away_D
 15. Away_L
 16. Away_GF
 17. Away_GA
 18. Away_GD
 19. Away_Pts
 20. Away_Pts/MP

----------------------------------------------------------------------------------------------------
PL 2022 Overall.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 15

COLUMN LIST:
  1. Rk
  2. Squad
  3. MP
  4. W
  5. D
  6. L
  7. GF
  8. GA
  9. GD
 10. Pts
 11. Pts/MP
 12. Attendance
 13. Top Team Scorer
 14. Goalkeeper
 15. Notes

----------------------------------------------------------------------------------------------------
Squad Goalkeeping Opponent.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 21

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

----------------------------------------------------------------------------------------------------
Squad Goalkeeping Squad.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 21

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

----------------------------------------------------------------------------------------------------
Squad Miscellaneous Stats O.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 15

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

----------------------------------------------------------------------------------------------------
Squad Miscellaneous Stats S.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 15

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

----------------------------------------------------------------------------------------------------
Squad Playing Time Opponent.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 19

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

----------------------------------------------------------------------------------------------------
Squad Playing Time S.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 19

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

----------------------------------------------------------------------------------------------------
Squad Shooting Opponent.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 13

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

----------------------------------------------------------------------------------------------------
Squad Shooting S.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 13

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

----------------------------------------------------------------------------------------------------
Squad Standard Stats Opponent.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 21

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

----------------------------------------------------------------------------------------------------
Squad Standard Stats Squad .xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 21

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK


====================================================================================================
SEASON: 2023 PL Season
====================================================================================================

----------------------------------------------------------------------------------------------------
Premier League 2023 HomeAway.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 20

COLUMN LIST:
  1. Rk
  2. Squad
  3. Home_MP
  4. Home_W
  5. Home_D
  6. Home_L
  7. Home_GF
  8. Home_GA
  9. Home_GD
 10. Home_Pts
 11. Home_Pts/MP
 12. Away_MP
 13. Away_W
 14. Away_D
 15. Away_L
 16. Away_GF
 17. Away_GA
 18. Away_GD
 19. Away_Pts
 20. Away_Pts/MP

----------------------------------------------------------------------------------------------------
Premier League 2023 Overall.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 15

COLUMN LIST:
  1. Rk
  2. Squad
  3. MP
  4. W
  5. D
  6. L
  7. GF
  8. GA
  9. GD
 10. Pts
 11. Pts/MP
 12. Attendance
 13. Top Team Scorer
 14. Goalkeeper
 15. Notes

----------------------------------------------------------------------------------------------------
Squad Goalkeeping Opponent Stats.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 21

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

----------------------------------------------------------------------------------------------------
Squad Goalkeeping Squad Stats.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 21

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

----------------------------------------------------------------------------------------------------
Squad Miscellaneous Stats Opponent Stats.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 15

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

----------------------------------------------------------------------------------------------------
Squad Miscellaneous Stats Squad Stats.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 15

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

----------------------------------------------------------------------------------------------------
Squad Playing Time Opponent Stats.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 19

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

----------------------------------------------------------------------------------------------------
Squad Playing Time Squad Stats.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 19

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

----------------------------------------------------------------------------------------------------
Squad Shooting Opponent stats.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 13

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

----------------------------------------------------------------------------------------------------
Squad Standard Stats 2023.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 21

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

----------------------------------------------------------------------------------------------------
Squad Standard Stats Opponent Stats.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 21

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

----------------------------------------------------------------------------------------------------
Squad Sthooting Squad Stats.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 13

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt


====================================================================================================
SEASON: 2024 PL Season
====================================================================================================

----------------------------------------------------------------------------------------------------
2024 PL Season Home Away.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 20

COLUMN LIST:
  1. Rk
  2. Squad
  3. Home_MP
  4. Home_W
  5. Home_D
  6. Home_L
  7. Home_GF
  8. Home_GA
  9. Home_GD
 10. Home_Pts
 11. Home_Pts/MP
 12. Away_MP
 13. Away_W
 14. Away_D
 15. Away_L
 16. Away_GF
 17. Away_GA
 18. Away_GD
 19. Away_Pts
 20. Away_Pts/MP

----------------------------------------------------------------------------------------------------
2024 PL Season overall.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 15

COLUMN LIST:
  1. Rk
  2. Squad
  3. MP
  4. W
  5. D
  6. L
  7. GF
  8. GA
  9. GD
 10. Pts
 11. Pts/MP
 12. Attendance
 13. Top Team Scorer
 14. Goalkeeper
 15. Notes

----------------------------------------------------------------------------------------------------
Squad Goalkeeping 2023-2024 Premier League Opponent Stats.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 21

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

----------------------------------------------------------------------------------------------------
Squad Goalkeeping 2023-2024 Premier League Opponents.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 13

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

----------------------------------------------------------------------------------------------------
Squad Goalkeeping 2023-2024 Premier League.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 21

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

----------------------------------------------------------------------------------------------------
Squad Miscellaneous Stats 2023-2024 Premier League Opponents.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 15

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

----------------------------------------------------------------------------------------------------
Squad Miscellaneous Stats 2023-2024 Premier League.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 15

COLUMN LIST:
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

----------------------------------------------------------------------------------------------------
Squad Playing Time 2023-2024 Premier Leagu Opponents.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 19

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

----------------------------------------------------------------------------------------------------
Squad Playing Time 2023-2024 Premier League.xls
----------------------------------------------------------------------------------------------------
Rows: 20
Columns: 19

COLUMN LIST:
  1. Squad
  2. # Pl
  3. Age

In [61]:
print("\n".join(
    f"{i+1}. {col}"
    for i, col in enumerate(df.columns)
))

1. Squad
2. # Pl
3. Age
4. Poss
5. Playing Time_MP
6. Playing Time_Starts
7. Playing Time_Min
8. Playing Time_90s
9. Performance_Gls
10. Performance_Ast
11. Performance_G+A
12. Performance_G-PK
13. Performance_PK
14. Performance_PKatt
15. Performance_CrdY
16. Performance_CrdR
17. Per 90 Minutes_Gls
18. Per 90 Minutes_Ast
19. Per 90 Minutes_G+A
20. Per 90 Minutes_G-PK
21. Per 90 Minutes_G+A-PK

In [62]:
from pathlib import Path
import pandas as pd

raw_path = Path(r"C:\Users\karab\PremierLeagueML\data\raw")

for season_folder in sorted(raw_path.iterdir()):

    if not season_folder.is_dir():
        continue

    print("\n" + "=" * 100)
    print(season_folder.name)
    print("=" * 100)

    for file in sorted(season_folder.glob("*.xls")):

        # Identify the table
        df = pd.read_html(file)[0]

        # Flatten columns
        if isinstance(df.columns, pd.MultiIndex):

            new_columns = []

            for col in df.columns:

                levels = [
                    str(level).strip()
                    for level in col
                    if str(level).strip() not in ["", "nan"]
                ]

                meaningful = [
                    level
                    for level in levels
                    if not level.startswith("Unnamed:")
                ]

                if meaningful:
                    new_columns.append("_".join(meaningful))
                else:
                    new_columns.append("_".join(levels))

            df.columns = new_columns

        else:

            df.columns = [
                str(col).strip()
                for col in df.columns
            ]

        print("\n" + "-" * 80)
        print(file.name)
        print("-" * 80)

        for i, col in enumerate(df.columns, start=1):
            print(f"{i:>3}. {col}")

====================================================================================================
2022 PL Season
====================================================================================================

--------------------------------------------------------------------------------
PL 2022 HomeAway.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. Home_MP
  4. Home_W
  5. Home_D
  6. Home_L
  7. Home_GF
  8. Home_GA
  9. Home_GD
 10. Home_Pts
 11. Home_Pts/MP
 12. Away_MP
 13. Away_W
 14. Away_D
 15. Away_L
 16. Away_GF
 17. Away_GA
 18. Away_GD
 19. Away_Pts
 20. Away_Pts/MP

--------------------------------------------------------------------------------
PL 2022 Overall.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. MP
  4. W
  5. D
  6. L
  7. GF
  8. GA
  9. GD
 10. Pts
 11. Pts/MP
 12. Attendance
 13. Top Team Scorer
 14. Goalkeeper
 15. Notes

--------------------------------------------------------------------------------
Squad Goalkeeping Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

--------------------------------------------------------------------------------
Squad Goalkeeping Squad.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

--------------------------------------------------------------------------------
Squad Miscellaneous Stats O.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

--------------------------------------------------------------------------------
Squad Miscellaneous Stats S.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

--------------------------------------------------------------------------------
Squad Playing Time Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

--------------------------------------------------------------------------------
Squad Playing Time S.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

--------------------------------------------------------------------------------
Squad Shooting Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

--------------------------------------------------------------------------------
Squad Shooting S.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

--------------------------------------------------------------------------------
Squad Standard Stats Opponent.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

--------------------------------------------------------------------------------
Squad Standard Stats Squad .xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

====================================================================================================
2023 PL Season
====================================================================================================

--------------------------------------------------------------------------------
Premier League 2023 HomeAway.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. Home_MP
  4. Home_W
  5. Home_D
  6. Home_L
  7. Home_GF
  8. Home_GA
  9. Home_GD
 10. Home_Pts
 11. Home_Pts/MP
 12. Away_MP
 13. Away_W
 14. Away_D
 15. Away_L
 16. Away_GF
 17. Away_GA
 18. Away_GD
 19. Away_Pts
 20. Away_Pts/MP

--------------------------------------------------------------------------------
Premier League 2023 Overall.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. MP
  4. W
  5. D
  6. L
  7. GF
  8. GA
  9. GD
 10. Pts
 11. Pts/MP
 12. Attendance
 13. Top Team Scorer
 14. Goalkeeper
 15. Notes

--------------------------------------------------------------------------------
Squad Goalkeeping Opponent Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

--------------------------------------------------------------------------------
Squad Goalkeeping Squad Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

--------------------------------------------------------------------------------
Squad Miscellaneous Stats Opponent Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

--------------------------------------------------------------------------------
Squad Miscellaneous Stats Squad Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

--------------------------------------------------------------------------------
Squad Playing Time Opponent Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

--------------------------------------------------------------------------------
Squad Playing Time Squad Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

--------------------------------------------------------------------------------
Squad Shooting Opponent stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

--------------------------------------------------------------------------------
Squad Standard Stats 2023.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

--------------------------------------------------------------------------------
Squad Standard Stats Opponent Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

--------------------------------------------------------------------------------
Squad Sthooting Squad Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

====================================================================================================
2024 PL Season
====================================================================================================

--------------------------------------------------------------------------------
2024 PL Season Home Away.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. Home_MP
  4. Home_W
  5. Home_D
  6. Home_L
  7. Home_GF
  8. Home_GA
  9. Home_GD
 10. Home_Pts
 11. Home_Pts/MP
 12. Away_MP
 13. Away_W
 14. Away_D
 15. Away_L
 16. Away_GF
 17. Away_GA
 18. Away_GD
 19. Away_Pts
 20. Away_Pts/MP

--------------------------------------------------------------------------------
2024 PL Season overall.xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. MP
  4. W
  5. D
  6. L
  7. GF
  8. GA
  9. GD
 10. Pts
 11. Pts/MP
 12. Attendance
 13. Top Team Scorer
 14. Goalkeeper
 15. Notes

--------------------------------------------------------------------------------
Squad Goalkeeping 2023-2024 Premier League Opponent Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

--------------------------------------------------------------------------------
Squad Goalkeeping 2023-2024 Premier League Opponents.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

--------------------------------------------------------------------------------
Squad Goalkeeping 2023-2024 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Playing Time_MP
  4. Playing Time_Starts
  5. Playing Time_Min
  6. Playing Time_90s
  7. Performance_GA
  8. Performance_GA90
  9. Performance_SoTA
 10. Performance_Saves
 11. Performance_Save%
 12. Performance_W
 13. Performance_D
 14. Performance_L
 15. Performance_CS
 16. Performance_CS%
 17. Penalty Kicks_PKatt
 18. Penalty Kicks_PKA
 19. Penalty Kicks_PKsv
 20. Penalty Kicks_PKm
 21. Penalty Kicks_Save%

--------------------------------------------------------------------------------
Squad Miscellaneous Stats 2023-2024 Premier League Opponents.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

--------------------------------------------------------------------------------
Squad Miscellaneous Stats 2023-2024 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Performance_CrdY
  5. Performance_CrdR
  6. Performance_2CrdY
  7. Performance_Fls
  8. Performance_Fld
  9. Performance_Off
 10. Performance_Crs
 11. Performance_Int
 12. Performance_TklW
 13. Performance_PKwon
 14. Performance_PKcon
 15. Performance_OG

--------------------------------------------------------------------------------
Squad Playing Time 2023-2024 Premier Leagu Opponents.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

--------------------------------------------------------------------------------
Squad Playing Time 2023-2024 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Playing Time_MP
  5. Playing Time_Min
  6. Playing Time_Mn/MP
  7. Playing Time_Min%
  8. Playing Time_90s
  9. Starts_Starts
 10. Starts_Mn/Start
 11. Starts_Compl
 12. Subs_Subs
 13. Subs_Mn/Sub
 14. Subs_unSub
 15. Team Success_PPM
 16. Team Success_onG
 17. Team Success_onGA
 18. Team Success_+/-
 19. Team Success_+/-90

--------------------------------------------------------------------------------
Squad Shooting 2023-2024 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. 90s
  4. Standard_Gls
  5. Standard_Sh
  6. Standard_SoT
  7. Standard_SoT%
  8. Standard_Sh/90
  9. Standard_SoT/90
 10. Standard_G/Sh
 11. Standard_G/SoT
 12. Standard_PK
 13. Standard_PKatt

--------------------------------------------------------------------------------
Squad Standard Stats 2023-2024 Premier League Opponet Stats.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

--------------------------------------------------------------------------------
Squad Standard Stats 2023-2024 Premier League.xls
--------------------------------------------------------------------------------
  1. Squad
  2. # Pl
  3. Age
  4. Poss
  5. Playing Time_MP
  6. Playing Time_Starts
  7. Playing Time_Min
  8. Playing Time_90s
  9. Performance_Gls
 10. Performance_Ast
 11. Performance_G+A
 12. Performance_G-PK
 13. Performance_PK
 14. Performance_PKatt
 15. Performance_CrdY
 16. Performance_CrdR
 17. Per 90 Minutes_Gls
 18. Per 90 Minutes_Ast
 19. Per 90 Minutes_G+A
 20. Per 90 Minutes_G-PK
 21. Per 90 Minutes_G+A-PK

====================================================================================================
2025 PL Season
====================================================================================================

--------------------------------------------------------------------------------
Premier League home and away .xls
--------------------------------------------------------------------------------
  1. Rk
  2. Squad
  3. Home_MP

In [63]:
def classify_table(columns):

    columns = set(columns)

    if "Home_W" in columns and "Away_W" in columns:
        return "HOME_AWAY"

    if "Pts" in columns and "GF" in columns and "GA" in columns:
        return "OVERALL"

    if "Performance_Save%" in columns:
        return "GOALKEEPING"

    if "Standard_SoT" in columns:
        return "SHOOTING"

    if "Performance_Ast" in columns:
        return "STANDARD_STATS"

    if "Team Success_PPM" in columns:
        return "PLAYING_TIME"

    if "Performance_TklW" in columns:
        return "MISCELLANEOUS"

    return "UNKNOWN"

In [64]:
from pathlib import Path
import pandas as pd

raw_path = Path(r"C:\Users\karab\PremierLeagueML\data\raw")

for season_folder in sorted(raw_path.iterdir()):

    if not season_folder.is_dir():
        continue

    print("\n" + "=" * 100)
    print(season_folder.name)
    print("=" * 100)

    for file in sorted(season_folder.glob("*.xls")):

        try:

            df = pd.read_html(file)[0]

            # Flatten MultiIndex
            if isinstance(df.columns, pd.MultiIndex):

                new_columns = []

                for col in df.columns:

                    levels = [
                        str(level).strip()
                        for level in col
                        if str(level).strip() not in ["", "nan"]
                    ]

                    meaningful = [
                        level
                        for level in levels
                        if not level.startswith("Unnamed:")
                    ]

                    if meaningful:
                        new_columns.append("_".join(meaningful))
                    else:
                        new_columns.append("_".join(levels))

                df.columns = new_columns

            else:

                df.columns = [
                    str(col).strip()
                    for col in df.columns
                ]

            actual_type = classify_table(df.columns)

            print(
                f"{file.name:<65} → {actual_type}"
            )

        except Exception as e:

            print(
                f"{file.name:<65} → ERROR: {e}"
            )

====================================================================================================
2022 PL Season
====================================================================================================
PL 2022 HomeAway.xls                                              → HOME_AWAY
PL 2022 Overall.xls                                               → OVERALL
Squad Goalkeeping Opponent.xls                                    → GOALKEEPING
Squad Goalkeeping Squad.xls                                       → GOALKEEPING
Squad Miscellaneous Stats O.xls                                   → MISCELLANEOUS
Squad Miscellaneous Stats S.xls                                   → MISCELLANEOUS
Squad Playing Time Opponent.xls                                   → PLAYING_TIME
Squad Playing Time S.xls                                          → PLAYING_TIME
Squad Shooting Opponent.xls                                       → SHOOTING
Squad Shooting S.xls                                              → SHOOTING
Squad Standard Stats Opponent.xls                                 → STANDARD_STATS
Squad Standard Stats Squad .xls                                   → STANDARD_STATS

====================================================================================================
2023 PL Season
====================================================================================================
Premier League 2023 HomeAway.xls                                  → HOME_AWAY
Premier League 2023 Overall.xls                                   → OVERALL
Squad Goalkeeping Opponent Stats.xls                              → GOALKEEPING
Squad Goalkeeping Squad Stats.xls                                 → GOALKEEPING
Squad Miscellaneous Stats Opponent Stats.xls                      → MISCELLANEOUS
Squad Miscellaneous Stats Squad Stats.xls                         → MISCELLANEOUS
Squad Playing Time Opponent Stats.xls                             → PLAYING_TIME
Squad Playing Time Squad Stats.xls                                → PLAYING_TIME
Squad Shooting Opponent stats.xls                                 → SHOOTING
Squad Standard Stats 2023.xls                                     → STANDARD_STATS
Squad Standard Stats Opponent Stats.xls                           → STANDARD_STATS
Squad Sthooting Squad Stats.xls                                   → SHOOTING

====================================================================================================
2024 PL Season
====================================================================================================
2024 PL Season Home Away.xls                                      → HOME_AWAY
2024 PL Season overall.xls                                        → OVERALL
Squad Goalkeeping 2023-2024 Premier League Opponent Stats.xls     → GOALKEEPING
Squad Goalkeeping 2023-2024 Premier League Opponents.xls          → SHOOTING
Squad Goalkeeping 2023-2024 Premier League.xls                    → GOALKEEPING
Squad Miscellaneous Stats 2023-2024 Premier League Opponents.xls  → MISCELLANEOUS
Squad Miscellaneous Stats 2023-2024 Premier League.xls            → MISCELLANEOUS
Squad Playing Time 2023-2024 Premier Leagu Opponents.xls          → PLAYING_TIME
Squad Playing Time 2023-2024 Premier League.xls                   → PLAYING_TIME
Squad Shooting 2023-2024 Premier League.xls                       → SHOOTING
Squad Standard Stats 2023-2024 Premier League Opponet Stats.xls   → STANDARD_STATS
Squad Standard Stats 2023-2024 Premier League.xls                 → STANDARD_STATS

====================================================================================================
2025 PL Season
====================================================================================================
Premier League home and away .xls                                 → HOME_AWAY
Premier League Overall.xls                                        → OVERALL
Squad Goalkeeping 2024-2025 Premier League.xls                    → GOALKEEPING
Squad Goalkeeping Opponent.xls                                    → GOALKEEPING
Squad Miscellaneous Stats 2024-2025 Premier League.xls            → MISCELLANEOUS
Squad Miscellaneous Stats Opponent.xls                            → MISCELLANEOUS
Squad Playing Time 2024-2025 Premier League.xls                   → PLAYING_TIME
Squad Playing Time Opponent.xls                                   → PLAYING_TIME
Squad Shooting 2024-2025 Premier League .xls                      → SHOOTING
Squad Shooting Opponent .xls                                      → SHOOTING
Squad Standard Stats 2024-2025 Premier League opponent stats.xls  → STANDARD_STATS
Squad Standard Stats 2024-2025 Premier League.xls                 → STANDARD_STATS

====================================================================================================
2026 PL Season
====================================================================================================
Premier League 2026 Overall.xls                                   → OVERALL
Premier League Home,away.xls                                      → HOME_AWAY
Squad goalkeeping 2026 PL.xls                                     → GOALKEEPING
Squad Goalkeeping Opponent.xls                                    → GOALKEEPING
Squad Miscellaneous Stats 2025-2026 Premier Leag.xls              → MISCELLANEOUS
Squad Miscellaneous Stats Opponent.xls                            → MISCELLANEOUS
Squad Playing Time 2025-2026 Premier League.xls                   → PLAYING_TIME
Squad Playing Time Opponent.xls                                   → PLAYING_TIME
Squad Shooting 2025-2026 Premier League.xls                       → SHOOTING
Squad Shooting Opponent .xls                                      → GOALKEEPING
Squad Standard Stats 2025-2026 Premier League.xls                 → STANDARD_STATS
Squad Standard Stats Opponent.xls                                 → STANDARD_STATS

In [65]:
file = raw_path / "2024 PL Season" / "Squad Goalkeeping 2023-2024 Premier League Opponents.xls"

df = pd.read_html(file)[0]

print(df.shape)
print(df.columns)
print(df.head())

(20, 13)
MultiIndex([('Unnamed: 0_level_0',  'Squad'),
            ('Unnamed: 1_level_0',   '# Pl'),
            ('Unnamed: 2_level_0',    '90s'),
            (          'Standard',    'Gls'),
            (          'Standard',     'Sh'),
            (          'Standard',    'SoT'),
            (          'Standard',   'SoT%'),
            (          'Standard',  'Sh/90'),
            (          'Standard', 'SoT/90'),
            (          'Standard',   'G/Sh'),
            (          'Standard',  'G/SoT'),
            (          'Standard',     'PK'),
            (          'Standard',  'PKatt')],
           )
  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Standard            \
               Squad               # Pl                90s      Gls   Sh  SoT
0         vs Arsenal                 25               38.0       28  320   80
1     vs Aston Villa                 31               38.0       57  453  171
2     vs Bournemouth                 30               38.0       66  527  187
3       vs Brentford                 28               38.0       65  546  182
4        vs Brighton                 30               38.0       60  462  159


   SoT%  Sh/90 SoT/90  G/Sh G/SoT PK PKatt
0  25.0   8.42   2.11  0.08  0.33  2     3
1  37.7  11.92   4.50  0.12  0.33  1     2
2  35.5  13.87   4.92  0.11  0.32  6     7
3  33.3  14.37   4.79  0.12  0.35  2     2
4  34.4  12.16   4.18  0.12  0.34  6     6

In [66]:
file = raw_path / "2026 PL Season" / "Squad Shooting Opponent .xls"

df = pd.read_html(file)[0]

print(df.shape)
print(df.columns)
print(df.head())

(20, 21)
MultiIndex([('Unnamed: 0_level_0',  'Squad'),
            ('Unnamed: 1_level_0',   '# Pl'),
            (      'Playing Time',     'MP'),
            (      'Playing Time', 'Starts'),
            (      'Playing Time',    'Min'),
            (      'Playing Time',    '90s'),
            (       'Performance',     'GA'),
            (       'Performance',   'GA90'),
            (       'Performance',   'SoTA'),
            (       'Performance',  'Saves'),
            (       'Performance',  'Save%'),
            (       'Performance',      'W'),
            (       'Performance',      'D'),
            (       'Performance',      'L'),
            (       'Performance',     'CS'),
            (       'Performance',    'CS%'),
            (     'Penalty Kicks',  'PKatt'),
            (     'Penalty Kicks',    'PKA'),
            (     'Penalty Kicks',   'PKsv'),
            (     'Penalty Kicks',    'PKm'),
            (     'Penalty Kicks',  'Save%')],
           )
  Unnamed: 0_level_0 Unnamed: 1_level_0 Playing Time                     \
               Squad               # Pl           MP Starts   Min   90s
0         vs Arsenal                  2           38     38  3420  38.0
1     vs Aston Villa                  2           38     38  3420  38.0
2     vs Bournemouth                  1           38     38  3420  38.0
3       vs Brentford                  2           38     38  3420  38.0
4        vs Brighton                  1           38     38  3420  38.0

  Performance                   ...                       Penalty Kicks      \
           GA  GA90 SoTA Saves  ...   W   D   L  CS   CS%         PKatt PKA
0          71  1.87  182   111  ...   5   7  26   3   7.9             4   4
1          56  1.47  174   116  ...  11   8  19  10  26.3             0   0
2          58  1.53  177   119  ...   7  18  13   7  18.4             6   5
3          55  1.45  150    92  ...  13  11  14  12  31.6            10   8
4          52  1.37  169   117  ...  13  11  14   9  23.7             5   3


  PKsv PKm Save%
0    0   0   0.0
1    0   0   NaN
2    1   0  16.7
3    2   0  20.0
4    1   1  25.0

[5 rows x 21 columns]

In [67]:
# ============================================================
# COMPLETE DATA INVENTORY
# ============================================================

for season, tables in season_tables.items():

    print("\n" + "=" * 100)
    print(f"{season} DATA INVENTORY")
    print("=" * 100)

    for table_name, df in tables.items():

        print(f"\n--- {table_name} ---")
        print(f"Shape: {df.shape}")

        print("Columns:")
        for col in df.columns:
            print(f"  - {col}")

        print("Missing values:")
        missing = df.isna().sum()
        missing = missing[missing > 0]

        if len(missing) == 0:
            print("  None")
        else:
            print(missing.to_string())

NameError: name 'season_tables' is not defined

In [68]:
# Show variables currently available in the notebook

for name in sorted(globals()):
    if not name.startswith("_"):
        obj = globals()[name]
        
        if isinstance(obj, dict):
            print(f"{name:<25} → dict ({len(obj)} items)")
        elif isinstance(obj, list):
            print(f"{name:<25} → list ({len(obj)} items)")
        else:
            print(f"{name:<25} → {type(obj).__name__}")

In                        → list (69 items)
Out                       → dict (5 items)
Path                      → type
actual_type               → str
all_tables                → dict (12 items)
classify_table            → function
clean_fbref_columns       → function
cleaned_tables            → dict (12 items)
col                       → tuple
column                    → str
column_inventory          → dict (5 items)
columns                   → list (21 items)
df                        → DataFrame
duplicate_teams           → DataFrame
duplicates                → Index
exit                      → ZMQExitAutocall
extra                     → set
file                      → WindowsPath
filename                  → str
files                     → dict (12 items)
flatten_fbref_columns     → function
get_ipython               → method
i                         → int
is_opponent               → bool
levels                    → list (2 items)
master_df                 → DataFrame
meaningful                → list (2 items)
merge_team_table          → function
missing                   → set
name                      → str
new_columns               → list (21 items)
open                      → function
opponent_tables           → dict (4 items)
overall                   → DataFrame
overall_file              → WindowsPath
overall_teams             → set
path                      → WindowsPath
pd                        → module
project_path              → WindowsPath
quit                      → ZMQExitAutocall
raw_path                  → WindowsPath
season                    → str
season_folder             → WindowsPath
season_path               → WindowsPath
season_summary            → dict (5 items)
squad_col                 → NoneType
standard_df               → DataFrame
tables                    → list (1 items)
teams                     → set
teams_normalized          → set

In [69]:
print("all_tables keys:")
print(list(all_tables.keys()))

print("\ncleaned_tables keys:")
print(list(cleaned_tables.keys()))

print("\nOut keys:")
print(list(Out.keys()))

all_tables keys:
['Premier League home and away', 'Premier League Overall', 'Squad Goalkeeping 2024-2025 Premier League', 'Squad Goalkeeping Opponent', 'Squad Miscellaneous Stats 2024-2025 Premier League', 'Squad Miscellaneous Stats Opponent', 'Squad Playing Time 2024-2025 Premier League', 'Squad Playing Time Opponent', 'Squad Shooting 2024-2025 Premier League', 'Squad Shooting Opponent', 'Squad Standard Stats 2024-2025 Premier League opponent stats', 'Squad Standard Stats 2024-2025 Premier League']

cleaned_tables keys:
['Premier League home and away', 'Premier League Overall', 'Squad Goalkeeping 2024-2025 Premier League', 'Squad Goalkeeping Opponent', 'Squad Miscellaneous Stats 2024-2025 Premier League', 'Squad Miscellaneous Stats Opponent', 'Squad Playing Time 2024-2025 Premier League', 'Squad Playing Time Opponent', 'Squad Shooting 2024-2025 Premier League', 'Squad Shooting Opponent', 'Squad Standard Stats 2024-2025 Premier League opponent stats', 'Squad Standard Stats 2024-2025 Premier League']

Out keys:
[14, 15, 24, 48, 49]

In [70]:
print("\ncolumn_inventory keys:")
print(list(column_inventory.keys()))

column_inventory keys:
['2022 PL Season', '2023 PL Season', '2024 PL Season', '2025 PL Season', '2026 PL Season']

In [71]:
canonical_tables = {}

for table_name, df in cleaned_tables.items():

    name = table_name.lower()

    # Overall
    if "overall" in name:
        canonical_name = "OVERALL"

    # Home / Away
    elif "home" in name and "away" in name:
        canonical_name = "HOME_AWAY"

    # Goalkeeping
    elif "goalkeeping" in name:
        if "opponent" in name:
            canonical_name = "GOALKEEPING_OPPONENT"
        else:
            canonical_name = "GOALKEEPING_SQUAD"

    # Miscellaneous
    elif "miscellaneous" in name:
        if "opponent" in name:
            canonical_name = "MISCELLANEOUS_OPPONENT"
        else:
            canonical_name = "MISCELLANEOUS_SQUAD"

    # Playing Time
    elif "playing time" in name:
        if "opponent" in name:
            canonical_name = "PLAYING_TIME_OPPONENT"
        else:
            canonical_name = "PLAYING_TIME_SQUAD"

    # Shooting
    elif "shooting" in name:
        if "opponent" in name:
            canonical_name = "SHOOTING_OPPONENT"
        else:
            canonical_name = "SHOOTING_SQUAD"

    # Standard Stats
    elif "standard stats" in name:
        if "opponent" in name:
            canonical_name = "STANDARD_STATS_OPPONENT"
        else:
            canonical_name = "STANDARD_STATS_SQUAD"

    else:
        canonical_name = None

    if canonical_name is not None:
        canonical_tables[canonical_name] = df

In [72]:
print("=" * 80)
print("CANONICAL TABLES")
print("=" * 80)

for name, df in canonical_tables.items():
    print(f"{name:<30} {df.shape}")

================================================================================
CANONICAL TABLES
================================================================================
HOME_AWAY                      (20, 20)
OVERALL                        (20, 15)
GOALKEEPING_SQUAD              (20, 21)
GOALKEEPING_OPPONENT           (20, 21)
MISCELLANEOUS_SQUAD            (20, 15)
MISCELLANEOUS_OPPONENT         (20, 15)
PLAYING_TIME_SQUAD             (20, 19)
PLAYING_TIME_OPPONENT          (20, 19)
SHOOTING_SQUAD                 (20, 13)
SHOOTING_OPPONENT              (20, 13)
STANDARD_STATS_OPPONENT        (20, 21)
STANDARD_STATS_SQUAD           (20, 21)

In [73]:
# ============================================================
# VERIFY TEAM ALIGNMENT
# ============================================================

overall_teams = set(canonical_tables["OVERALL"]["Squad"])

print("Overall teams:", len(overall_teams))
print(sorted(overall_teams))

print("\n" + "=" * 80)
print("TEAM ALIGNMENT CHECK")
print("=" * 80)

for table_name, df in canonical_tables.items():

    teams = set(df["Squad"])

    missing = overall_teams - teams
    extra = teams - overall_teams

    if not missing and not extra:
        print(f"✓ {table_name:<30} 20/20 teams match")

    else:
        print(f"⚠ {table_name}")

        if missing:
            print("  Missing:", sorted(missing))

        if extra:
            print("  Extra:", sorted(extra))

Overall teams: 20
['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']

================================================================================
TEAM ALIGNMENT CHECK
================================================================================
✓ HOME_AWAY                      20/20 teams match
✓ OVERALL                        20/20 teams match
✓ GOALKEEPING_SQUAD              20/20 teams match
⚠ GOALKEEPING_OPPONENT
  Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
  Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Ipswich Town', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ MISCELLANEOUS_SQUAD            20/20 teams match
⚠ MISCELLANEOUS_OPPONENT
  Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
  Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Ipswich Town', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ PLAYING_TIME_SQUAD             20/20 teams match
⚠ PLAYING_TIME_OPPONENT
  Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
  Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Ipswich Town', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ SHOOTING_SQUAD                 20/20 teams match
⚠ SHOOTING_OPPONENT
  Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
  Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Ipswich Town', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
⚠ STANDARD_STATS_OPPONENT
  Missing: ['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town', 'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd', 'Newcastle', 'Nottingham', 'Southampton', 'Tottenham', 'West Ham', 'Wolves']
  Extra: ['vs Arsenal', 'vs Aston Villa', 'vs Bournemouth', 'vs Brentford', 'vs Brighton', 'vs Chelsea', 'vs Crystal Palace', 'vs Everton', 'vs Fulham', 'vs Ipswich Town', 'vs Leicester City', 'vs Liverpool', 'vs Manchester City', 'vs Manchester Utd', 'vs Newcastle', 'vs Nottingham', 'vs Southampton', 'vs Tottenham', 'vs West Ham', 'vs Wolves']
✓ STANDARD_STATS_SQUAD           20/20 teams match

In [74]:
# ============================================================
# CHECK DUPLICATE TEAMS
# ============================================================

print("=" * 80)
print("DUPLICATE TEAM CHECK")
print("=" * 80)

for table_name, df in canonical_tables.items():

    duplicate_mask = df["Squad"].duplicated(keep=False)
    duplicates = df.loc[duplicate_mask, "Squad"].tolist()

    if not duplicates:
        print(f"✓ {table_name:<30} No duplicate teams")
    else:
        print(f"⚠ {table_name:<30} Duplicates: {duplicates}")

================================================================================
DUPLICATE TEAM CHECK
================================================================================
✓ HOME_AWAY                      No duplicate teams
✓ OVERALL                        No duplicate teams
✓ GOALKEEPING_SQUAD              No duplicate teams
✓ GOALKEEPING_OPPONENT           No duplicate teams
✓ MISCELLANEOUS_SQUAD            No duplicate teams
✓ MISCELLANEOUS_OPPONENT         No duplicate teams
✓ PLAYING_TIME_SQUAD             No duplicate teams
✓ PLAYING_TIME_OPPONENT          No duplicate teams
✓ SHOOTING_SQUAD                 No duplicate teams
✓ SHOOTING_OPPONENT              No duplicate teams
✓ STANDARD_STATS_OPPONENT        No duplicate teams
✓ STANDARD_STATS_SQUAD           No duplicate teams

In [75]:
# ============================================================
# ROW COUNT CHECK
# ============================================================

print("=" * 80)
print("ROW COUNT CHECK")
print("=" * 80)

for table_name, df in canonical_tables.items():

    if len(df) == 20:
        print(f"✓ {table_name:<30} 20 rows")
    else:
        print(f"⚠ {table_name:<30} {len(df)} rows")

================================================================================
ROW COUNT CHECK
================================================================================
✓ HOME_AWAY                      20 rows
✓ OVERALL                        20 rows
✓ GOALKEEPING_SQUAD              20 rows
✓ GOALKEEPING_OPPONENT           20 rows
✓ MISCELLANEOUS_SQUAD            20 rows
✓ MISCELLANEOUS_OPPONENT         20 rows
✓ PLAYING_TIME_SQUAD             20 rows
✓ PLAYING_TIME_OPPONENT          20 rows
✓ SHOOTING_SQUAD                 20 rows
✓ SHOOTING_OPPONENT              20 rows
✓ STANDARD_STATS_OPPONENT        20 rows
✓ STANDARD_STATS_SQUAD           20 rows

In [76]:
# ============================================================
# CREATE NORMALIZED TEAM KEY
# WITHOUT CHANGING ORIGINAL SQUAD COLUMN
# ============================================================

for table_name, df in canonical_tables.items():

    df = df.copy()

    if table_name in OPPONENT_TABLES:

        df["Team_Key"] = (
            df["Squad"]
            .astype(str)
            .str.strip()
            .str.replace(r"^vs\s+", "", regex=True)
            .str.strip()
        )

    else:

        df["Team_Key"] = (
            df["Squad"]
            .astype(str)
            .str.strip()
        )

    canonical_tables[table_name] = df

NameError: name 'OPPONENT_TABLES' is not defined

In [77]:
overall_keys = set(
    canonical_tables["OVERALL"]["Team_Key"]
)

for table_name, df in canonical_tables.items():

    table_keys = set(df["Team_Key"])

    missing = overall_keys - table_keys
    extra = table_keys - overall_keys

    if not missing and not extra:
        print(f"✓ {table_name:<30} 20/20 Team_Key match")
    else:
        print(f"⚠ {table_name}")

        if missing:
            print("  Missing:", sorted(missing))

        if extra:
            print("  Extra:", sorted(extra))

KeyError: 'Team_Key'

In [78]:
print(
    canonical_tables["SHOOTING_OPPONENT"]
    [["Squad", "Team_Key"]]
    .head(10)
)

KeyError: "['Team_Key'] not in index"

In [79]:
print(canonical_tables["SHOOTING_OPPONENT"].columns.tolist())

['Squad', '# Pl', '90s', 'Standard_Gls', 'Standard_Sh', 'Standard_SoT', 'Standard_SoT%', 'Standard_Sh/90', 'Standard_SoT/90', 'Standard_G/Sh', 'Standard_G/SoT', 'Standard_PK', 'Standard_PKatt']

In [80]:
print(canonical_tables.keys())

dict_keys(['HOME_AWAY', 'OVERALL', 'GOALKEEPING_SQUAD', 'GOALKEEPING_OPPONENT', 'MISCELLANEOUS_SQUAD', 'MISCELLANEOUS_OPPONENT', 'PLAYING_TIME_SQUAD', 'PLAYING_TIME_OPPONENT', 'SHOOTING_SQUAD', 'SHOOTING_OPPONENT', 'STANDARD_STATS_OPPONENT', 'STANDARD_STATS_SQUAD'])

In [81]:
# ============================================================
# CREATE TEAM_KEY FOR ALL CANONICAL TABLES
# ============================================================

for table_name, df in canonical_tables.items():

    df = df.copy()

    # Opponent tables have values like "vs Arsenal"
    if "OPPONENT" in table_name:

        df["Team_Key"] = (
            df["Squad"]
            .astype(str)
            .str.strip()
            .str.replace(r"^vs\s+", "", regex=True)
            .str.strip()
        )

    # Normal squad/team tables
    else:

        df["Team_Key"] = (
            df["Squad"]
            .astype(str)
            .str.strip()
        )

    canonical_tables[table_name] = df

print("✓ Team_Key created for all canonical tables")

✓ Team_Key created for all canonical tables

In [82]:
print(
    canonical_tables["SHOOTING_OPPONENT"]
    [["Squad", "Team_Key"]]
    .head(10)
)

               Squad        Team_Key
0         vs Arsenal         Arsenal
1     vs Aston Villa     Aston Villa
2     vs Bournemouth     Bournemouth
3       vs Brentford       Brentford
4        vs Brighton        Brighton
5         vs Chelsea         Chelsea
6  vs Crystal Palace  Crystal Palace
7         vs Everton         Everton
8          vs Fulham          Fulham
9    vs Ipswich Town    Ipswich Town

In [1]:
# ============================================================
# FIXTURE DATA INVENTORY
# ============================================================

from pathlib import Path
import pandas as pd

FIXTURES_PATH = Path(
    r"C:\Users\karab\PremierLeagueML\data\raw\Fixtures"
)

print("=" * 100)
print("FIXTURE DATA INVENTORY")
print("=" * 100)

fixture_files = sorted(FIXTURES_PATH.glob("*"))

print(f"\nFixture files found: {len(fixture_files)}\n")

for file in fixture_files:
    print(f"- {file.name}")

====================================================================================================
FIXTURE DATA INVENTORY
====================================================================================================

Fixture files found: 5

- 2021-2022 PL Season.xls
- 2022-2023 PL Season.xls
- 2023-2024 PL Season.xls
- 2024-2025 PL Season.xls
- 2025-2026 PL Season.xls

In [2]:
# ============================================================
# INSPECT FIRST FIXTURE FILE
# ============================================================

file = fixture_files[0]

print("=" * 100)
print("FILE:", file.name)
print("=" * 100)

tables = pd.read_html(file)

print(f"\nNumber of tables found: {len(tables)}")

for i, table in enumerate(tables):
    print(f"\nTable {i}")
    print("Shape:", table.shape)
    print("Columns:")
    print(table.columns.tolist())
    print("\nFirst 5 rows:")
    display(table.head())

====================================================================================================
FILE: 2021-2022 PL Season.xls
====================================================================================================

Number of tables found: 1

Table 0
Shape: (448, 12)
Columns:
['Wk', 'Day', 'Date', 'Time', 'Home', 'Score', 'Away', 'Attendance', 'Venue', 'Referee', 'Match Report', 'Notes']

First 5 rows:

,Wk,Day,Date,Time,Home,Score,Away,Attendance,Venue,Referee,Match Report,Notes
0,1.0,Fri,2021-08-13,20:00 (21:00),Brentford,2â0,Arsenal,16479.0,Brentford Community Stadium,Michael Oliver,Match Report,NaN
1,1.0,Sat,2021-08-14,12:30 (13:30),Manchester Utd,5â1,Leeds United,72732.0,Old Trafford,Paul Tierney,Match Report,NaN
2,1.0,Sat,2021-08-14,15:00 (16:00),Leicester City,1â0,Wolves,31983.0,King Power Stadium,Craig Pawson,Match Report,NaN
3,1.0,Sat,2021-08-14,15:00 (16:00),Burnley,1â2,Brighton,16910.0,Turf Moor,David Coote,Match Report,NaN
4,1.0,Sat,2021-08-14,15:00 (16:00),Chelsea,3â0,Crystal Palace,38965.0,Stamford Bridge,Jonathan Moss,Match Report,NaN

In [3]:
# ============================================================
# INSPECT FIXTURE STATUS
# ============================================================

fixture_df = pd.read_html(fixture_files[0])[0]

print("Total rows:", len(fixture_df))

print("\nRows with a score:")
print(fixture_df["Score"].notna().sum())

print("\nRows without a score:")
print(fixture_df["Score"].isna().sum())

print("\nScore examples:")
print(fixture_df["Score"].dropna().head(20).tolist())

print("\nRows without Home team:")
print(fixture_df["Home"].isna().sum())

print("\nRows without Away team:")
print(fixture_df["Away"].isna().sum())

Total rows: 448

Rows with a score:
380

Rows without a score:
68

Score examples:
['2â\x80\x930', '5â\x80\x931', '1â\x80\x930', '1â\x80\x932', '3â\x80\x930', '3â\x80\x932', '3â\x80\x931', '0â\x80\x933', '2â\x80\x934', '1â\x80\x930', '2â\x80\x930', '2â\x80\x930', '5â\x80\x930', '2â\x80\x932', '0â\x80\x930', '2â\x80\x930', '0â\x80\x931', '1â\x80\x931', '0â\x80\x932', '4â\x80\x931']

Rows without Home team:
68

Rows without Away team:
68

In [4]:
# ============================================================
# CHECK ROWS WITHOUT SCORES
# ============================================================

print(
    fixture_df[
        fixture_df["Score"].isna()
    ][
        ["Wk", "Day", "Date", "Home", "Score", "Away", "Notes"]
    ].to_string(index=False)
)

 Wk Day Date Home Score Away  Notes
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN
NaN NaN  NaN  NaN   NaN  NaN    NaN

In [5]:
# ============================================================
# CLEAN FIXTURE DATA
# ============================================================

# Keep only rows that have both teams and a score
fixtures = fixture_df.dropna(subset=["Home", "Away", "Score"]).copy()

print("Rows after removing incomplete fixtures:", len(fixtures))


# ------------------------------------------------------------
# Fix score encoding
# ------------------------------------------------------------

fixtures["Score"] = (
    fixtures["Score"]
    .astype(str)
    .str.replace("â\x80\x93", "-", regex=False)
    .str.replace("–", "-", regex=False)
)


# ------------------------------------------------------------
# Split score into Home Goals and Away Goals
# ------------------------------------------------------------

fixtures[["HomeGoals", "AwayGoals"]] = (
    fixtures["Score"]
    .str.split("-", expand=True)
)


# Convert goals to numbers
fixtures["HomeGoals"] = pd.to_numeric(fixtures["HomeGoals"], errors="coerce")
fixtures["AwayGoals"] = pd.to_numeric(fixtures["AwayGoals"], errors="coerce")


# ------------------------------------------------------------
# Create match result
# ------------------------------------------------------------

def get_result(row):
    if row["HomeGoals"] > row["AwayGoals"]:
        return "H"
    elif row["HomeGoals"] < row["AwayGoals"]:
        return "A"
    else:
        return "D"


fixtures["Result"] = fixtures.apply(get_result, axis=1)


# ------------------------------------------------------------
# Inspect the cleaned dataset
# ------------------------------------------------------------

print("\nCleaned fixture shape:", fixtures.shape)

print("\nFirst 10 fixtures:")
print(
    fixtures[
        ["Home", "Away", "Score", "HomeGoals", "AwayGoals", "Result"]
    ].head(10)
)

print("\nResult counts:")
print(fixtures["Result"].value_counts())

print("\nMissing values:")
print(
    fixtures[
        ["Home", "Away", "Score", "HomeGoals", "AwayGoals", "Result"]
    ].isna().sum()
)

Rows after removing incomplete fixtures: 380

Cleaned fixture shape: (380, 15)

First 10 fixtures:
             Home             Away Score  HomeGoals  AwayGoals Result
0       Brentford          Arsenal   2-0          2          0      H
1  Manchester Utd     Leeds United   5-1          5          1      H
2  Leicester City           Wolves   1-0          1          0      H
3         Burnley         Brighton   1-2          1          2      A
4         Chelsea   Crystal Palace   3-0          3          0      H
5         Watford      Aston Villa   3-2          3          2      H
6         Everton      Southampton   3-1          3          1      H
7    Norwich City        Liverpool   0-3          0          3      A
8       Newcastle         West Ham   2-4          2          4      A
9       Tottenham  Manchester City   1-0          1          0      H

Result counts:
Result
H    163
A    129
D     88
Name: count, dtype: int64

Missing values:
Home         0
Away         0
Score        0
HomeGoals    0
AwayGoals    0
Result       0
dtype: int64

In [6]:
# ============================================================
# INSPECT FIXTURE DATES
# ============================================================

print("Columns:")
print(fixtures.columns.tolist())

print("\nFirst 10 dates:")
print(fixtures["Date"].head(10))

print("\nLast 10 dates:")
print(fixtures["Date"].tail(10))

print("\nDate data type:")
print(fixtures["Date"].dtype)

Columns:
['Wk', 'Day', 'Date', 'Time', 'Home', 'Score', 'Away', 'Attendance', 'Venue', 'Referee', 'Match Report', 'Notes', 'HomeGoals', 'AwayGoals', 'Result']

First 10 dates:
0    2021-08-13
1    2021-08-14
2    2021-08-14
3    2021-08-14
4    2021-08-14
5    2021-08-14
6    2021-08-14
7    2021-08-14
8    2021-08-15
9    2021-08-15
Name: Date, dtype: str

Last 10 dates:
438    2022-05-22
439    2022-05-22
440    2022-05-22
441    2022-05-22
442    2022-05-22
443    2022-05-22
444    2022-05-22
445    2022-05-22
446    2022-05-22
447    2022-05-22
Name: Date, dtype: str

Date data type:
str

In [7]:
# Convert Date to datetime
fixtures["Date"] = pd.to_datetime(
    fixtures["Date"],
    errors="coerce"
)

print("\nMissing dates:", fixtures["Date"].isna().sum())

print("\nDate range:")
print(fixtures["Date"].min(), "to", fixtures["Date"].max())

print("\nChronological order:")
print(fixtures["Date"].is_monotonic_increasing)

Missing dates: 0

Date range:
2021-08-13 00:00:00 to 2022-05-22 00:00:00

Chronological order:
True

In [8]:
# ============================================================
# CONVERT DATE TO DATETIME
# ============================================================

fixtures["Date"] = pd.to_datetime(fixtures["Date"], errors="coerce")

print("Date data type:", fixtures["Date"].dtype)
print("Missing dates:", fixtures["Date"].isna().sum())

Date data type: datetime64[us]
Missing dates: 0

In [9]:
# ============================================================
# INSPECT MATCHWEEKS
# ============================================================

print("Number of matchweeks:", fixtures["Wk"].nunique())

print("\nMatchweeks:")
print(sorted(fixtures["Wk"].dropna().unique()))

print("\nMatches per matchweek:")
print(fixtures.groupby("Wk").size())

Number of matchweeks: 38

Matchweeks:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0), np.float64(13.0), np.float64(14.0), np.float64(15.0), np.float64(16.0), np.float64(17.0), np.float64(18.0), np.float64(19.0), np.float64(20.0), np.float64(21.0), np.float64(22.0), np.float64(23.0), np.float64(24.0), np.float64(25.0), np.float64(26.0), np.float64(27.0), np.float64(28.0), np.float64(29.0), np.float64(30.0), np.float64(31.0), np.float64(32.0), np.float64(33.0), np.float64(34.0), np.float64(35.0), np.float64(36.0), np.float64(37.0), np.float64(38.0)]

Matches per matchweek:
Wk
1.0     10
2.0     10
3.0     10
4.0     10
5.0     10
6.0     10
7.0     10
8.0     10
9.0     10
10.0    10
11.0    10
12.0    10
13.0    10
14.0    10
15.0    10
16.0    10
17.0    10
18.0    10
19.0    10
20.0    10
21.0    10
22.0    10
23.0    10
24.0    10
25.0    10
26.0    10
27.0    10
28.0    10
29.0    10
30.0    10
31.0    10
32.0    10
33.0    10
34.0    10
35.0    10
36.0    10
37.0    10
38.0    10
dtype: int64

In [10]:
# ============================================================
# CHECK TEAMS
# ============================================================

home_teams = set(fixtures["Home"].unique())
away_teams = set(fixtures["Away"].unique())

all_teams = sorted(home_teams | away_teams)

print("Number of teams:", len(all_teams))

print("\nTeams:")
for team in all_teams:
    print(team)

Number of teams: 20

Teams:
Arsenal
Aston Villa
Brentford
Brighton
Burnley
Chelsea
Crystal Palace
Everton
Leeds United
Leicester City
Liverpool
Manchester City
Manchester Utd
Newcastle
Norwich City
Southampton
Tottenham
Watford
West Ham
Wolves

In [11]:
fixtures["Wk"] = fixtures["Wk"].astype(int)

print(fixtures[["Wk", "Date", "Home", "Away", "HomeGoals", "AwayGoals", "Result"]].head())

   Wk       Date            Home            Away  HomeGoals  AwayGoals Result
0   1 2021-08-13       Brentford         Arsenal          2          0      H
1   1 2021-08-14  Manchester Utd    Leeds United          5          1      H
2   1 2021-08-14  Leicester City          Wolves          1          0      H
3   1 2021-08-14         Burnley        Brighton          1          2      A
4   1 2021-08-14         Chelsea  Crystal Palace          3          0      H

In [12]:
# ============================================================
# BUILD PRE-MATCH TEAM STATE
# ============================================================

# Make a copy so we don't accidentally alter our clean dataset
fixture_ml = fixtures.copy()

# Store each team's statistics as the season progresses
team_stats = {}

# Columns we will create
state_columns = [
    "Home_Points_Before",
    "Away_Points_Before",
    "Home_GF_Before",
    "Away_GF_Before",
    "Home_GA_Before",
    "Away_GA_Before",
    "Home_Games_Before",
    "Away_Games_Before"
]

for col in state_columns:
    fixture_ml[col] = 0


# ------------------------------------------------------------
# Process fixtures chronologically
# ------------------------------------------------------------

for index, row in fixture_ml.iterrows():

    home = row["Home"]
    away = row["Away"]

    # Create team records if they don't exist yet
    if home not in team_stats:
        team_stats[home] = {
            "points": 0,
            "gf": 0,
            "ga": 0,
            "games": 0
        }

    if away not in team_stats:
        team_stats[away] = {
            "points": 0,
            "gf": 0,
            "ga": 0,
            "games": 0
        }


    # --------------------------------------------------------
    # RECORD STATE BEFORE THE MATCH
    # --------------------------------------------------------

    fixture_ml.at[index, "Home_Points_Before"] = team_stats[home]["points"]
    fixture_ml.at[index, "Away_Points_Before"] = team_stats[away]["points"]

    fixture_ml.at[index, "Home_GF_Before"] = team_stats[home]["gf"]
    fixture_ml.at[index, "Away_GF_Before"] = team_stats[away]["gf"]

    fixture_ml.at[index, "Home_GA_Before"] = team_stats[home]["ga"]
    fixture_ml.at[index, "Away_GA_Before"] = team_stats[away]["ga"]

    fixture_ml.at[index, "Home_Games_Before"] = team_stats[home]["games"]
    fixture_ml.at[index, "Away_Games_Before"] = team_stats[away]["games"]


    # --------------------------------------------------------
    # UPDATE TEAM STATISTICS AFTER THE MATCH
    # --------------------------------------------------------

    home_goals = row["HomeGoals"]
    away_goals = row["AwayGoals"]

    # Goals
    team_stats[home]["gf"] += home_goals
    team_stats[home]["ga"] += away_goals

    team_stats[away]["gf"] += away_goals
    team_stats[away]["ga"] += home_goals

    # Games played
    team_stats[home]["games"] += 1
    team_stats[away]["games"] += 1

    # Points
    if home_goals > away_goals:

        # Home win
        team_stats[home]["points"] += 3

    elif home_goals < away_goals:

        # Away win
        team_stats[away]["points"] += 3

    else:

        # Draw
        team_stats[home]["points"] += 1
        team_stats[away]["points"] += 1

In [13]:
print(
    fixture_ml[
        [
            "Wk",
            "Home",
            "Away",
            "HomeGoals",
            "AwayGoals",
            "Result",
            "Home_Points_Before",
            "Away_Points_Before",
            "Home_GF_Before",
            "Away_GF_Before",
            "Home_GA_Before",
            "Away_GA_Before",
            "Home_Games_Before",
            "Away_Games_Before"
        ]
    ].head(10)
)

   Wk            Home             Away  HomeGoals  AwayGoals Result  \
0   1       Brentford          Arsenal          2          0      H
1   1  Manchester Utd     Leeds United          5          1      H
2   1  Leicester City           Wolves          1          0      H
3   1         Burnley         Brighton          1          2      A
4   1         Chelsea   Crystal Palace          3          0      H
5   1         Watford      Aston Villa          3          2      H
6   1         Everton      Southampton          3          1      H
7   1    Norwich City        Liverpool          0          3      A
8   1       Newcastle         West Ham          2          4      A
9   1       Tottenham  Manchester City          1          0      H

   Home_Points_Before  Away_Points_Before  Home_GF_Before  Away_GF_Before  \
0                   0                   0               0               0
1                   0                   0               0               0
2                   0                   0               0               0
3                   0                   0               0               0
4                   0                   0               0               0
5                   0                   0               0               0
6                   0                   0               0               0
7                   0                   0               0               0
8                   0                   0               0               0
9                   0                   0               0               0

   Home_GA_Before  Away_GA_Before  Home_Games_Before  Away_Games_Before
0               0               0                  0                  0
1               0               0                  0                  0
2               0               0                  0                  0
3               0               0                  0                  0
4               0               0                  0                  0
5               0               0                  0                  0
6               0               0                  0                  0
7               0               0                  0                  0
8               0               0                  0                  0
9               0               0                  0                  0

In [14]:
print("\nFirst fixture:")
print(
    fixture_ml[
        [
            "Home",
            "Away",
            "HomeGoals",
            "AwayGoals",
            "Home_Points_Before",
            "Away_Points_Before"
        ]
    ].iloc[0]
)

print("\nLast fixture:")
print(
    fixture_ml[
        [
            "Home",
            "Away",
            "HomeGoals",
            "AwayGoals",
            "Home_Points_Before",
            "Away_Points_Before"
        ]
    ].iloc[-1]
)

First fixture:
Home                  Brentford
Away                    Arsenal
HomeGoals                     2
AwayGoals                     0
Home_Points_Before            0
Away_Points_Before            0
Name: 0, dtype: object

Last fixture:
Home                  Chelsea
Away                  Watford
HomeGoals                   2
AwayGoals                   1
Home_Points_Before         71
Away_Points_Before         23
Name: 447, dtype: object

In [15]:
# ============================================================
# BUILD LAST-5 FORM
# ============================================================

from collections import defaultdict, deque

# Store previous match results for every team
team_form = defaultdict(lambda: deque(maxlen=5))

# Create columns
form_columns = [
    "Home_Points_Last5",
    "Away_Points_Last5",
    "Home_Wins_Last5",
    "Away_Wins_Last5",
    "Home_Draws_Last5",
    "Away_Draws_Last5",
    "Home_Losses_Last5",
    "Away_Losses_Last5",
    "Home_GF_Last5",
    "Away_GF_Last5",
    "Home_GA_Last5",
    "Away_GA_Last5"
]

for col in form_columns:
    fixture_ml[col] = 0


# ------------------------------------------------------------
# Process matches chronologically
# ------------------------------------------------------------

for index, row in fixture_ml.iterrows():

    home = row["Home"]
    away = row["Away"]

    # Get the previous five matches BEFORE this fixture
    home_previous = list(team_form[home])
    away_previous = list(team_form[away])


    # --------------------------------------------------------
    # HOME FORM
    # --------------------------------------------------------

    fixture_ml.at[index, "Home_Points_Last5"] = sum(
        match["points"] for match in home_previous
    )

    fixture_ml.at[index, "Home_Wins_Last5"] = sum(
        match["result"] == "W" for match in home_previous
    )

    fixture_ml.at[index, "Home_Draws_Last5"] = sum(
        match["result"] == "D" for match in home_previous
    )

    fixture_ml.at[index, "Home_Losses_Last5"] = sum(
        match["result"] == "L" for match in home_previous
    )

    fixture_ml.at[index, "Home_GF_Last5"] = sum(
        match["gf"] for match in home_previous
    )

    fixture_ml.at[index, "Home_GA_Last5"] = sum(
        match["ga"] for match in home_previous
    )


    # --------------------------------------------------------
    # AWAY FORM
    # --------------------------------------------------------

    fixture_ml.at[index, "Away_Points_Last5"] = sum(
        match["points"] for match in away_previous
    )

    fixture_ml.at[index, "Away_Wins_Last5"] = sum(
        match["result"] == "W" for match in away_previous
    )

    fixture_ml.at[index, "Away_Draws_Last5"] = sum(
        match["result"] == "D" for match in away_previous
    )

    fixture_ml.at[index, "Away_Losses_Last5"] = sum(
        match["result"] == "L" for match in away_previous
    )

    fixture_ml.at[index, "Away_GF_Last5"] = sum(
        match["gf"] for match in away_previous
    )

    fixture_ml.at[index, "Away_GA_Last5"] = sum(
        match["ga"] for match in away_previous
    )


    # --------------------------------------------------------
    # DETERMINE RESULT FOR EACH TEAM
    # --------------------------------------------------------

    home_goals = row["HomeGoals"]
    away_goals = row["AwayGoals"]

    if home_goals > away_goals:

        home_result = "W"
        away_result = "L"

        home_points = 3
        away_points = 0

    elif home_goals < away_goals:

        home_result = "L"
        away_result = "W"

        home_points = 0
        away_points = 3

    else:

        home_result = "D"
        away_result = "D"

        home_points = 1
        away_points = 1


    # --------------------------------------------------------
    # ADD THIS MATCH TO EACH TEAM'S HISTORY
    # --------------------------------------------------------

    team_form[home].append({
        "result": home_result,
        "points": home_points,
        "gf": home_goals,
        "ga": away_goals
    })

    team_form[away].append({
        "result": away_result,
        "points": away_points,
        "gf": away_goals,
        "ga": home_goals
    })

In [16]:
print(
    fixture_ml[
        [
            "Wk",
            "Home",
            "Away",
            "Result",
            "Home_Points_Last5",
            "Away_Points_Last5",
            "Home_Wins_Last5",
            "Away_Wins_Last5",
            "Home_GF_Last5",
            "Away_GF_Last5"
        ]
    ].head(20)
)

    Wk             Home             Away Result  Home_Points_Last5  \
0    1        Brentford          Arsenal      H                  0
1    1   Manchester Utd     Leeds United      H                  0
2    1   Leicester City           Wolves      H                  0
3    1          Burnley         Brighton      A                  0
4    1          Chelsea   Crystal Palace      H                  0
5    1          Watford      Aston Villa      H                  0
6    1          Everton      Southampton      H                  0
7    1     Norwich City        Liverpool      A                  0
8    1        Newcastle         West Ham      A                  0
9    1        Tottenham  Manchester City      H                  0
11   2        Liverpool          Burnley      H                  3
12   2      Aston Villa        Newcastle      H                  0
13   2  Manchester City     Norwich City      H                  0
14   2     Leeds United          Everton      D                  0
15   2   Crystal Palace        Brentford      D                  0
16   2         Brighton          Watford      H                  3
17   2           Wolves        Tottenham      A                  0
18   2      Southampton   Manchester Utd      D                  0
19   2          Arsenal          Chelsea      A                  0
20   2         West Ham   Leicester City      H                  3

    Away_Points_Last5  Home_Wins_Last5  Away_Wins_Last5  Home_GF_Last5  \
0                   0                0                0              0
1                   0                0                0              0
2                   0                0                0              0
3                   0                0                0              0
4                   0                0                0              0
5                   0                0                0              0
6                   0                0                0              0
7                   0                0                0              0
8                   0                0                0              0
9                   0                0                0              0
11                  0                1                0              3
12                  0                0                0              2
13                  0                0                0              0
14                  3                0                1              1
15                  3                0                1              0
16                  3                1                1              2
17                  3                0                1              0
18                  3                0                1              1
19                  3                0                1              0
20                  3                1                1              4

    Away_GF_Last5
0               0
1               0
2               0
3               0
4               0
5               0
6               0
7               0
8               0
9               0
11              1
12              2
13              0
14              3
15              2
16              3
17              1
18              5
19              3
20              1

In [17]:
# Reset the fixture index
fixture_ml = fixture_ml.reset_index(drop=True)

print(fixture_ml.index[:15].tolist())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [18]:
# ============================================================
# CHECK LAST-5 FORM FOR A SPECIFIC TEAM
# ============================================================

team = "Liverpool"

liverpool_matches = fixture_ml[
    (fixture_ml["Home"] == team) |
    (fixture_ml["Away"] == team)
]

print(
    liverpool_matches[
        [
            "Wk",
            "Date",
            "Home",
            "Away",
            "Result",
            "Home_Points_Last5",
            "Away_Points_Last5"
        ]
    ].head(10)
)

    Wk       Date            Home             Away Result  Home_Points_Last5  \
7    1 2021-08-14    Norwich City        Liverpool      A                  0
10   2 2021-08-21       Liverpool          Burnley      H                  3
26   3 2021-08-28       Liverpool          Chelsea      D                  6
38   4 2021-09-12    Leeds United        Liverpool      A                  2
43   5 2021-09-18       Liverpool   Crystal Palace      H                 10
56   6 2021-09-25       Brentford        Liverpool      D                  8
69   7 2021-10-03       Liverpool  Manchester City      D                 11
70   8 2021-10-16         Watford        Liverpool      A                  4
89   9 2021-10-24  Manchester Utd        Liverpool      A                  7
92  10 2021-10-30       Liverpool         Brighton      D                 11

    Away_Points_Last5
7                   0
10                  0
26                  6
38                  7
43                  5
56                 13
69                 13
70                  9
89                 11
92                  6

In [19]:
# ============================================================
# BUILD HOME/AWAY SPECIFIC FORM
# ============================================================

from collections import defaultdict, deque

# Reset venue-specific histories
home_history = defaultdict(lambda: deque(maxlen=5))
away_history = defaultdict(lambda: deque(maxlen=5))


# Create columns
venue_columns = [
    "HomeTeam_HomePoints_Last5",
    "AwayTeam_AwayPoints_Last5",
    "HomeTeam_HomeWins_Last5",
    "AwayTeam_AwayWins_Last5",
    "HomeTeam_HomeDraws_Last5",
    "AwayTeam_AwayDraws_Last5",
    "HomeTeam_HomeLosses_Last5",
    "AwayTeam_AwayLosses_Last5",
    "HomeTeam_HomeGF_Last5",
    "AwayTeam_AwayGF_Last5",
    "HomeTeam_HomeGA_Last5",
    "AwayTeam_AwayGA_Last5"
]

for col in venue_columns:
    fixture_ml[col] = 0


# ============================================================
# PROCESS MATCHES CHRONOLOGICALLY
# ============================================================

for index, row in fixture_ml.iterrows():

    home = row["Home"]
    away = row["Away"]

    # --------------------------------------------------------
    # GET PREVIOUS HOME FORM
    # --------------------------------------------------------

    previous_home_matches = list(home_history[home])

    fixture_ml.at[index, "HomeTeam_HomePoints_Last5"] = sum(
        match["points"] for match in previous_home_matches
    )

    fixture_ml.at[index, "HomeTeam_HomeWins_Last5"] = sum(
        match["result"] == "W"
        for match in previous_home_matches
    )

    fixture_ml.at[index, "HomeTeam_HomeDraws_Last5"] = sum(
        match["result"] == "D"
        for match in previous_home_matches
    )

    fixture_ml.at[index, "HomeTeam_HomeLosses_Last5"] = sum(
        match["result"] == "L"
        for match in previous_home_matches
    )

    fixture_ml.at[index, "HomeTeam_HomeGF_Last5"] = sum(
        match["gf"] for match in previous_home_matches
    )

    fixture_ml.at[index, "HomeTeam_HomeGA_Last5"] = sum(
        match["ga"] for match in previous_home_matches
    )


    # --------------------------------------------------------
    # GET PREVIOUS AWAY FORM
    # --------------------------------------------------------

    previous_away_matches = list(away_history[away])

    fixture_ml.at[index, "AwayTeam_AwayPoints_Last5"] = sum(
        match["points"] for match in previous_away_matches
    )

    fixture_ml.at[index, "AwayTeam_AwayWins_Last5"] = sum(
        match["result"] == "W"
        for match in previous_away_matches
    )

    fixture_ml.at[index, "AwayTeam_AwayDraws_Last5"] = sum(
        match["result"] == "D"
        for match in previous_away_matches
    )

    fixture_ml.at[index, "AwayTeam_AwayLosses_Last5"] = sum(
        match["result"] == "L"
        for match in previous_away_matches
    )

    fixture_ml.at[index, "AwayTeam_AwayGF_Last5"] = sum(
        match["gf"] for match in previous_away_matches
    )

    fixture_ml.at[index, "AwayTeam_AwayGA_Last5"] = sum(
        match["ga"] for match in previous_away_matches
    )


    # --------------------------------------------------------
    # DETERMINE CURRENT MATCH RESULT FOR EACH TEAM
    # --------------------------------------------------------

    home_goals = row["HomeGoals"]
    away_goals = row["AwayGoals"]

    if home_goals > away_goals:

        home_result = "W"
        away_result = "L"

        home_points = 3
        away_points = 0

    elif home_goals < away_goals:

        home_result = "L"
        away_result = "W"

        home_points = 0
        away_points = 3

    else:

        home_result = "D"
        away_result = "D"

        home_points = 1
        away_points = 1


    # --------------------------------------------------------
    # ADD CURRENT MATCH TO VENUE HISTORY
    # --------------------------------------------------------

    home_history[home].append({
        "result": home_result,
        "points": home_points,
        "gf": home_goals,
        "ga": away_goals
    })

    away_history[away].append({
        "result": away_result,
        "points": away_points,
        "gf": away_goals,
        "ga": home_goals
    })

In [20]:
print(
    fixture_ml[
        [
            "Wk",
            "Home",
            "Away",
            "Result",
            "HomeTeam_HomePoints_Last5",
            "AwayTeam_AwayPoints_Last5",
            "HomeTeam_HomeWins_Last5",
            "AwayTeam_AwayWins_Last5",
            "HomeTeam_HomeGF_Last5",
            "AwayTeam_AwayGF_Last5"
        ]
    ].head(30)
)

    Wk             Home             Away Result  HomeTeam_HomePoints_Last5  \
0    1        Brentford          Arsenal      H                          0
1    1   Manchester Utd     Leeds United      H                          0
2    1   Leicester City           Wolves      H                          0
3    1          Burnley         Brighton      A                          0
4    1          Chelsea   Crystal Palace      H                          0
5    1          Watford      Aston Villa      H                          0
6    1          Everton      Southampton      H                          0
7    1     Norwich City        Liverpool      A                          0
8    1        Newcastle         West Ham      A                          0
9    1        Tottenham  Manchester City      H                          0
10   2        Liverpool          Burnley      H                          0
11   2      Aston Villa        Newcastle      H                          0
12   2  Manchester City     Norwich City      H                          0
13   2     Leeds United          Everton      D                          0
14   2   Crystal Palace        Brentford      D                          0
15   2         Brighton          Watford      H                          0
16   2           Wolves        Tottenham      A                          0
17   2      Southampton   Manchester Utd      D                          0
18   2          Arsenal          Chelsea      A                          0
19   2         West Ham   Leicester City      H                          0
20   3  Manchester City          Arsenal      H                          3
21   3     Norwich City   Leicester City      A                          0
22   3         West Ham   Crystal Palace      D                          3
23   3      Aston Villa        Brentford      D                          3
24   3        Newcastle      Southampton      D                          0
25   3         Brighton          Everton      A                          3
26   3        Liverpool          Chelsea      D                          3
27   3          Burnley     Leeds United      D                          0
28   3        Tottenham          Watford      H                          3
29   3           Wolves   Manchester Utd      A                          0

    AwayTeam_AwayPoints_Last5  HomeTeam_HomeWins_Last5  \
0                           0                        0
1                           0                        0
2                           0                        0
3                           0                        0
4                           0                        0
5                           0                        0
6                           0                        0
7                           0                        0
8                           0                        0
9                           0                        0
10                          0                        0
11                          0                        0
12                          0                        0
13                          0                        0
14                          0                        0
15                          0                        0
16                          0                        0
17                          0                        0
18                          0                        0
19                          0                        0
20                          0                        1
21                          0                        0
22                          0                        1
23                          1                        1
24                          0                        0
25                          1                        1
26                          3                        1
27                          0                        0
28                          0                        1
29                          1                        0

    AwayTeam_AwayWins_Last5  HomeTeam_HomeGF_Last5  AwayTeam_AwayGF_Last5
0                         0                      0                      0
1                         0                      0                      0
2                         0                      0                      0
3                         0                      0                      0
4                         0                      0                      0
5                         0                      0                      0
6                         0                      0                      0
7                         0                      0                      0
8                         0                      0                      0
9                         0                      0                      0
10                        0                      0                      0
11                        0                      0                      0
12                        0                      0                      0
13                        0                      0                      0
14                        0                      0                      0
15                        0                      0                      0
16                        0                      0                      0
17                        0                      0                      0
18                        0                      0                      0
19                        0                      0                      0
20                        0                      5                      0
21                        0                      0                      1
22                        0                      4                      0
23                        0                      2                      0
24                        0                      2                      1
25                        0                      2                      2
26                        1                      2                      2
27                        0                      1                      1
28                        0                      1                      0
29                        0                      0                      1

In [21]:
# ============================================================
# CREATE HOME VS AWAY DIFFERENCE FEATURES
# ============================================================

fixture_ml["Points_Difference"] = (
    fixture_ml["Home_Points_Before"]
    - fixture_ml["Away_Points_Before"]
)

fixture_ml["GF_Difference"] = (
    fixture_ml["Home_GF_Before"]
    - fixture_ml["Away_GF_Before"]
)

fixture_ml["GA_Difference"] = (
    fixture_ml["Home_GA_Before"]
    - fixture_ml["Away_GA_Before"]
)

fixture_ml["Games_Difference"] = (
    fixture_ml["Home_Games_Before"]
    - fixture_ml["Away_Games_Before"]
)


# ------------------------------------------------------------
# Last 5 differences
# ------------------------------------------------------------

fixture_ml["Last5_Points_Difference"] = (
    fixture_ml["Home_Points_Last5"]
    - fixture_ml["Away_Points_Last5"]
)

fixture_ml["Last5_Wins_Difference"] = (
    fixture_ml["Home_Wins_Last5"]
    - fixture_ml["Away_Wins_Last5"]
)

fixture_ml["Last5_GF_Difference"] = (
    fixture_ml["Home_GF_Last5"]
    - fixture_ml["Away_GF_Last5"]
)

fixture_ml["Last5_GA_Difference"] = (
    fixture_ml["Home_GA_Last5"]
    - fixture_ml["Away_GA_Last5"]
)


# ------------------------------------------------------------
# Home vs Away venue form
# ------------------------------------------------------------

fixture_ml["Venue_Points_Difference"] = (
    fixture_ml["HomeTeam_HomePoints_Last5"]
    - fixture_ml["AwayTeam_AwayPoints_Last5"]
)

fixture_ml["Venue_Wins_Difference"] = (
    fixture_ml["HomeTeam_HomeWins_Last5"]
    - fixture_ml["AwayTeam_AwayWins_Last5"]
)

fixture_ml["Venue_GF_Difference"] = (
    fixture_ml["HomeTeam_HomeGF_Last5"]
    - fixture_ml["AwayTeam_AwayGF_Last5"]
)

fixture_ml["Venue_GA_Difference"] = (
    fixture_ml["HomeTeam_HomeGA_Last5"]
    - fixture_ml["AwayTeam_AwayGA_Last5"]
)

In [22]:
difference_columns = [
    "Home",
    "Away",
    "Result",
    "Points_Difference",
    "GF_Difference",
    "GA_Difference",
    "Last5_Points_Difference",
    "Last5_Wins_Difference",
    "Last5_GF_Difference",
    "Last5_GA_Difference",
    "Venue_Points_Difference",
    "Venue_Wins_Difference",
    "Venue_GF_Difference",
    "Venue_GA_Difference"
]

print(fixture_ml[difference_columns].head(30))

               Home             Away Result  Points_Difference  GF_Difference  \
0         Brentford          Arsenal      H                  0              0
1    Manchester Utd     Leeds United      H                  0              0
2    Leicester City           Wolves      H                  0              0
3           Burnley         Brighton      A                  0              0
4           Chelsea   Crystal Palace      H                  0              0
5           Watford      Aston Villa      H                  0              0
6           Everton      Southampton      H                  0              0
7      Norwich City        Liverpool      A                  0              0
8         Newcastle         West Ham      A                  0              0
9         Tottenham  Manchester City      H                  0              0
10        Liverpool          Burnley      H                  3              2
11      Aston Villa        Newcastle      H                  0              0
12  Manchester City     Norwich City      H                  0              0
13     Leeds United          Everton      D                 -3             -2
14   Crystal Palace        Brentford      D                 -3             -2
15         Brighton          Watford      H                  0             -1
16           Wolves        Tottenham      A                 -3             -1
17      Southampton   Manchester Utd      D                 -3             -4
18          Arsenal          Chelsea      A                 -3             -3
19         West Ham   Leicester City      H                  0              3
20  Manchester City          Arsenal      H                  3              5
21     Norwich City   Leicester City      A                 -3             -2
22         West Ham   Crystal Palace      D                  5              8
23      Aston Villa        Brentford      D                 -1              2
24        Newcastle      Southampton      D                 -1              0
25         Brighton          Everton      A                  2             -1
26        Liverpool          Chelsea      D                  0              0
27          Burnley     Leeds United      D                 -1             -2
28        Tottenham          Watford      H                  3             -1
29           Wolves   Manchester Utd      A                 -4             -6

    GA_Difference  Last5_Points_Difference  Last5_Wins_Difference  \
0               0                        0                      0
1               0                        0                      0
2               0                        0                      0
3               0                        0                      0
4               0                        0                      0
5               0                        0                      0
6               0                        0                      0
7               0                        0                      0
8               0                        0                      0
9               0                        0                      0
10             -2                        3                      1
11             -1                        0                      0
12             -2                        0                      0
13              4                       -3                     -1
14              3                       -3                     -1
15             -1                        0                      0
16              1                       -3                     -1
17              2                       -3                     -1
18              2                       -3                     -1
19              2                        0                      0
20             -3                        3                      1
21              4                       -3                     -1
22              0                        5                      2
23              3                       -1                      0
24              2                       -1                      0
25             -2                        2                      1
26              0                        0                      0
27             -3                       -1                      0
28             -4                        3                      1
29              0                       -4                     -1

    Last5_GF_Difference  Last5_GA_Difference  Venue_Points_Difference  \
0                     0                    0                        0
1                     0                    0                        0
2                     0                    0                        0
3                     0                    0                        0
4                     0                    0                        0
5                     0                    0                        0
6                     0                    0                        0
7                     0                    0                        0
8                     0                    0                        0
9                     0                    0                        0
10                    2                   -2                        0
11                    0                   -1                        0
12                    0                   -2                        0
13                   -2                    4                        0
14                   -2                    3                        0
15                   -1                   -1                        0
16                   -1                    1                        0
17                   -4                    2                        0
18                   -3                    2                        0
19                    3                    2                        0
20                    5                   -3                        3
21                   -2                    4                        0
22                    8                    0                        3
23                    2                    3                        2
24                    0                    2                        0
25                   -1                   -2                        2
26                    0                    0                        0
27                   -2                   -3                        0
28                   -1                   -4                        3
29                   -6                    0                       -1

    Venue_Wins_Difference  Venue_GF_Difference  Venue_GA_Difference
0                       0                    0                    0
1                       0                    0                    0
2                       0                    0                    0
3                       0                    0                    0
4                       0                    0                    0
5                       0                    0                    0
6                       0                    0                    0
7                       0                    0                    0
8                       0                    0                    0
9                       0                    0                    0
10                      0                    0                    0
11                      0                    0                    0
12                      0                    0                    0
13                      0                    0                    0
14                      0                    0                    0
15                      0                    0                    0
16                      0                    0                    0
17                      0                    0                    0
18                      0                    0                    0
19                      0                    0                    0
20                      1                    5                   -2
21                      0                   -1                   -1
22                      1                    4                   -2
23                      1                    2                    0
24                      0                    1                    1
25                      1                    0                   -2
26                      0                    0                    0
27                      0                    0                   -3
28                      1                    1                   -2
29                      0                   -1                    0

In [23]:
# ============================================================
# STEP 1 — CREATE RATE-BASED PRE-MATCH FEATURES
# ============================================================

import numpy as np

# Points per game
fixture_ml["Home_PPG_Before"] = np.where(
    fixture_ml["Home_Games_Before"] > 0,
    fixture_ml["Home_Points_Before"] / fixture_ml["Home_Games_Before"],
    np.nan
)

fixture_ml["Away_PPG_Before"] = np.where(
    fixture_ml["Away_Games_Before"] > 0,
    fixture_ml["Away_Points_Before"] / fixture_ml["Away_Games_Before"],
    np.nan
)


# Goals scored per game
fixture_ml["Home_GF_PerGame_Before"] = np.where(
    fixture_ml["Home_Games_Before"] > 0,
    fixture_ml["Home_GF_Before"] / fixture_ml["Home_Games_Before"],
    np.nan
)

fixture_ml["Away_GF_PerGame_Before"] = np.where(
    fixture_ml["Away_Games_Before"] > 0,
    fixture_ml["Away_GF_Before"] / fixture_ml["Away_Games_Before"],
    np.nan
)


# Goals conceded per game
fixture_ml["Home_GA_PerGame_Before"] = np.where(
    fixture_ml["Home_Games_Before"] > 0,
    fixture_ml["Home_GA_Before"] / fixture_ml["Home_Games_Before"],
    np.nan
)

fixture_ml["Away_GA_PerGame_Before"] = np.where(
    fixture_ml["Away_Games_Before"] > 0,
    fixture_ml["Away_GA_Before"] / fixture_ml["Away_Games_Before"],
    np.nan
)


# ------------------------------------------------------------
# Difference features
# ------------------------------------------------------------

fixture_ml["PPG_Difference"] = (
    fixture_ml["Home_PPG_Before"]
    - fixture_ml["Away_PPG_Before"]
)

fixture_ml["GF_Rate_Difference"] = (
    fixture_ml["Home_GF_PerGame_Before"]
    - fixture_ml["Away_GF_PerGame_Before"]
)

fixture_ml["GA_Rate_Difference"] = (
    fixture_ml["Home_GA_PerGame_Before"]
    - fixture_ml["Away_GA_PerGame_Before"]
)


# ------------------------------------------------------------
# Inspect
# ------------------------------------------------------------

rate_columns = [
    "Wk",
    "Home",
    "Away",
    "Result",
    "Home_PPG_Before",
    "Away_PPG_Before",
    "Home_GF_PerGame_Before",
    "Away_GF_PerGame_Before",
    "Home_GA_PerGame_Before",
    "Away_GA_PerGame_Before",
    "PPG_Difference",
    "GF_Rate_Difference",
    "GA_Rate_Difference"
]

print(fixture_ml[rate_columns].head(20))

    Wk             Home             Away Result  Home_PPG_Before  \
0    1        Brentford          Arsenal      H              NaN
1    1   Manchester Utd     Leeds United      H              NaN
2    1   Leicester City           Wolves      H              NaN
3    1          Burnley         Brighton      A              NaN
4    1          Chelsea   Crystal Palace      H              NaN
5    1          Watford      Aston Villa      H              NaN
6    1          Everton      Southampton      H              NaN
7    1     Norwich City        Liverpool      A              NaN
8    1        Newcastle         West Ham      A              NaN
9    1        Tottenham  Manchester City      H              NaN
10   2        Liverpool          Burnley      H              3.0
11   2      Aston Villa        Newcastle      H              0.0
12   2  Manchester City     Norwich City      H              0.0
13   2     Leeds United          Everton      D              0.0
14   2   Crystal Palace        Brentford      D              0.0
15   2         Brighton          Watford      H              3.0
16   2           Wolves        Tottenham      A              0.0
17   2      Southampton   Manchester Utd      D              0.0
18   2          Arsenal          Chelsea      A              0.0
19   2         West Ham   Leicester City      H              3.0

    Away_PPG_Before  Home_GF_PerGame_Before  Away_GF_PerGame_Before  \
0               NaN                     NaN                     NaN
1               NaN                     NaN                     NaN
2               NaN                     NaN                     NaN
3               NaN                     NaN                     NaN
4               NaN                     NaN                     NaN
5               NaN                     NaN                     NaN
6               NaN                     NaN                     NaN
7               NaN                     NaN                     NaN
8               NaN                     NaN                     NaN
9               NaN                     NaN                     NaN
10              0.0                     3.0                     1.0
11              0.0                     2.0                     2.0
12              0.0                     0.0                     0.0
13              3.0                     1.0                     3.0
14              3.0                     0.0                     2.0
15              3.0                     2.0                     3.0
16              3.0                     0.0                     1.0
17              3.0                     1.0                     5.0
18              3.0                     0.0                     3.0
19              3.0                     4.0                     1.0

    Home_GA_PerGame_Before  Away_GA_PerGame_Before  PPG_Difference  \
0                      NaN                     NaN             NaN
1                      NaN                     NaN             NaN
2                      NaN                     NaN             NaN
3                      NaN                     NaN             NaN
4                      NaN                     NaN             NaN
5                      NaN                     NaN             NaN
6                      NaN                     NaN             NaN
7                      NaN                     NaN             NaN
8                      NaN                     NaN             NaN
9                      NaN                     NaN             NaN
10                     0.0                     2.0             3.0
11                     3.0                     4.0             0.0
12                     1.0                     3.0             0.0
13                     5.0                     1.0            -3.0
14                     3.0                     0.0            -3.0
15                     1.0                     2.0             0.0
16                     1.0                     0.0            -3.0
17                     3.0                     1.0            -3.0
18                     2.0                     0.0            -3.0
19                     2.0                     0.0             0.0

    GF_Rate_Difference  GA_Rate_Difference
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 2.0                -2.0
11                 0.0                -1.0
12                 0.0                -2.0
13                -2.0                 4.0
14                -2.0                 3.0
15                -1.0                -1.0
16                -1.0                 1.0
17                -4.0                 2.0
18                -3.0                 2.0
19                 3.0                 2.0

In [1]:
# ============================================================
# STEP 2A — INSPECT AVAILABLE SEASON DATA
# ============================================================

print("Variables containing 'fixture':")
print([x for x in globals() if "fixture" in x.lower()])

print("\nVariables containing 'season':")
print([x for x in globals() if "season" in x.lower()])

Variables containing 'fixture':
[]

Variables containing 'season':
[]

In [3]:
print("\nfixture_ml shape:", fixture_ml.shape)

print("\nfixture_ml columns:")
print(fixture_ml.columns.tolist())

NameError: name 'fixture_ml' is not defined

In [4]:
# ============================================================
# CHECK CURRENT DATAFRAME VARIABLES
# ============================================================

print("DataFrame variables currently in memory:\n")

for name, value in globals().items():
    if hasattr(value, "shape") and hasattr(value, "columns"):
        print(f"{name}: shape={value.shape}")

DataFrame variables currently in memory:

RuntimeError: dictionary changed size during iteration

In [5]:
print("DataFrames currently in memory:\n")

for name, value in list(globals().items()):
    if hasattr(value, "shape") and hasattr(value, "columns"):
        print(f"{name}: shape={value.shape}")

DataFrames currently in memory:

In [6]:
# ============================================================
# STEP 2 — LOAD FIXTURE DATA FOR ALL 5 SEASONS
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path


# ============================================================
# 1. PROJECT PATH
# ============================================================

project_path = Path(r"C:\Users\karab\PremierLeagueML")

data_path = project_path / "data"

print("Project path:", project_path)
print("Data path:", data_path)


# ============================================================
# 2. FIND ALL FIXTURE FILES
# ============================================================

# Search for Excel/HTML fixture files
fixture_files_all = []

for pattern in ["*.xls", "*.xlsx", "*.html"]:
    fixture_files_all.extend(data_path.rglob(pattern))


print("\nFiles found:")
for file in fixture_files_all:
    print(file)


# ============================================================
# 3. LOOK FOR FILES CONTAINING FIXTURE/MATCH INFORMATION
# ============================================================

fixture_candidates = [
    f for f in fixture_files_all
    if any(
        word in f.name.lower()
        for word in ["fixture", "schedule", "match"]
    )
]

print("\n" + "=" * 60)
print("FIXTURE CANDIDATES")
print("=" * 60)

for file in fixture_candidates:
    print(file)


# ============================================================
# 4. IF YOUR FIXTURE FILES WERE SAVED UNDER DIFFERENT NAMES,
#    SHOW ALL HTML/EXCEL FILES SO WE CAN IDENTIFY THEM.
# ============================================================

if len(fixture_candidates) == 0:

    print("\nNo obvious fixture files found.")
    print("\nAll Excel/HTML files:")

    for file in fixture_files_all:
        print(file)


# ============================================================
# 5. STORE THE RESULT
# ============================================================

fixture_files = fixture_candidates

print("\nNumber of fixture candidates:", len(fixture_files))

Project path: C:\Users\karab\PremierLeagueML
Data path: C:\Users\karab\PremierLeagueML\data

Files found:
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\PL 2022 HomeAway.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\PL 2022 Overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Goalkeeping Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Goalkeeping Squad.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Miscellaneous Stats O.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Miscellaneous Stats S.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Playing Time Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Playing Time S.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Shooting Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Shooting S.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Standard Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Standard Stats Squad .xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Premier League 2023 HomeAway.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Premier League 2023 Overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Goalkeeping Opponent Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Goalkeeping Squad Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Miscellaneous Stats Opponent Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Miscellaneous Stats Squad Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Playing Time Opponent Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Playing Time Squad Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Shooting Opponent stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Standard Stats 2023.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Standard Stats Opponent Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Sthooting Squad Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\2024 PL Season Home Away.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\2024 PL Season overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Goalkeeping 2023-2024 Premier League Opponent Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Goalkeeping 2023-2024 Premier League Opponents.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Goalkeeping 2023-2024 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Miscellaneous Stats 2023-2024 Premier League Opponents.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Miscellaneous Stats 2023-2024 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Playing Time 2023-2024 Premier Leagu Opponents.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Playing Time 2023-2024 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Shooting 2023-2024 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Standard Stats 2023-2024 Premier League Opponet Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Standard Stats 2023-2024 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Premier League home and away .xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Premier League Overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Goalkeeping 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Goalkeeping Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Miscellaneous Stats 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Miscellaneous Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Playing Time 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Playing Time Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Shooting 2024-2025 Premier League .xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Shooting Opponent .xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Standard Stats 2024-2025 Premier League opponent stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Standard Stats 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Premier League 2026 Overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Premier League Home,away.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad goalkeeping 2026 PL.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Goalkeeping Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Miscellaneous Stats 2025-2026 Premier Leag.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Miscellaneous Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Playing Time 2025-2026 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Playing Time Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Shooting 2025-2026 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Shooting Opponent .xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Standard Stats 2025-2026 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Standard Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2021-2022 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2022-2023 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2023-2024 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2024-2025 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2025-2026 PL Season.xls

============================================================
FIXTURE CANDIDATES
============================================================

No obvious fixture files found.

All Excel/HTML files:
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\PL 2022 HomeAway.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\PL 2022 Overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Goalkeeping Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Goalkeeping Squad.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Miscellaneous Stats O.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Miscellaneous Stats S.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Playing Time Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Playing Time S.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Shooting Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Shooting S.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Standard Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\Squad Standard Stats Squad .xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Premier League 2023 HomeAway.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Premier League 2023 Overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Goalkeeping Opponent Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Goalkeeping Squad Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Miscellaneous Stats Opponent Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Miscellaneous Stats Squad Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Playing Time Opponent Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Playing Time Squad Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Shooting Opponent stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Standard Stats 2023.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Standard Stats Opponent Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Squad Sthooting Squad Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\2024 PL Season Home Away.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\2024 PL Season overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Goalkeeping 2023-2024 Premier League Opponent Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Goalkeeping 2023-2024 Premier League Opponents.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Goalkeeping 2023-2024 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Miscellaneous Stats 2023-2024 Premier League Opponents.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Miscellaneous Stats 2023-2024 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Playing Time 2023-2024 Premier Leagu Opponents.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Playing Time 2023-2024 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Shooting 2023-2024 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Standard Stats 2023-2024 Premier League Opponet Stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\Squad Standard Stats 2023-2024 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Premier League home and away .xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Premier League Overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Goalkeeping 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Goalkeeping Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Miscellaneous Stats 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Miscellaneous Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Playing Time 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Playing Time Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Shooting 2024-2025 Premier League .xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Shooting Opponent .xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Standard Stats 2024-2025 Premier League opponent stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Standard Stats 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Premier League 2026 Overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Premier League Home,away.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad goalkeeping 2026 PL.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Goalkeeping Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Miscellaneous Stats 2025-2026 Premier Leag.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Miscellaneous Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Playing Time 2025-2026 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Playing Time Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Shooting 2025-2026 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Shooting Opponent .xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Standard Stats 2025-2026 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Standard Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2021-2022 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2022-2023 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2023-2024 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2024-2025 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2025-2026 PL Season.xls

Number of fixture candidates: 0

In [7]:
# ============================================================
# FIND HOME/AWAY FIXTURE FILES
# ============================================================

from pathlib import Path

project_path = Path(r"C:\Users\karab\PremierLeagueML")
data_path = project_path / "data" / "raw"

all_files = list(data_path.rglob("*"))

print("=" * 70)
print("POSSIBLE FIXTURE FILES")
print("=" * 70)

for file in all_files:

    if not file.is_file():
        continue

    name = file.name.lower()

    if (
        "homeaway" in name
        or "home away" in name
        or "fixture" in name
    ):
        print(file)

======================================================================
POSSIBLE FIXTURE FILES
======================================================================
C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\PL 2022 HomeAway.xls
C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Premier League 2023 HomeAway.xls
C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\2024 PL Season Home Away.xls

In [8]:
# ============================================================
# FIND 2025 AND 2026 FIXTURE FILES
# ============================================================

from pathlib import Path

project_path = Path(r"C:\Users\karab\PremierLeagueML")

all_files = list(project_path.rglob("*"))

print("=" * 70)
print("FILES IN 2025 / 2026 FOLDERS")
print("=" * 70)

for file in all_files:

    if not file.is_file():
        continue

    path_lower = str(file).lower()

    if "2025" in path_lower or "2026" in path_lower:
        print(file)

======================================================================
FILES IN 2025 / 2026 FOLDERS
======================================================================
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Premier League home and away .xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Premier League Overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Goalkeeping 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Goalkeeping Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Miscellaneous Stats 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Miscellaneous Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Playing Time 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Playing Time Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Shooting 2024-2025 Premier League .xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Shooting Opponent .xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Standard Stats 2024-2025 Premier League opponent stats.xls
C:\Users\karab\PremierLeagueML\data\raw\2025 PL Season\Squad Standard Stats 2024-2025 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Premier League 2026 Overall.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Premier League Home,away.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad goalkeeping 2026 PL.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Goalkeeping Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Miscellaneous Stats 2025-2026 Premier Leag.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Miscellaneous Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Playing Time 2025-2026 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Playing Time Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Shooting 2025-2026 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Shooting Opponent .xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Standard Stats 2025-2026 Premier League.xls
C:\Users\karab\PremierLeagueML\data\raw\2026 PL Season\Squad Standard Stats Opponent.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2024-2025 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2025-2026 PL Season.xls
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\certifi-2026.7.22.dist-info\INSTALLER
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\certifi-2026.7.22.dist-info\METADATA
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\certifi-2026.7.22.dist-info\RECORD
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\certifi-2026.7.22.dist-info\top_level.txt
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\certifi-2026.7.22.dist-info\WHEEL
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\jsonschema_specifications-2025.9.1.dist-info\INSTALLER
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\jsonschema_specifications-2025.9.1.dist-info\METADATA
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\jsonschema_specifications-2025.9.1.dist-info\RECORD
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\jsonschema_specifications-2025.9.1.dist-info\WHEEL
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\rpds_py-2026.6.3.dist-info\INSTALLER
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\rpds_py-2026.6.3.dist-info\METADATA
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\rpds_py-2026.6.3.dist-info\RECORD
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\rpds_py-2026.6.3.dist-info\WHEEL
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\tzdata-2026.3.dist-info\INSTALLER
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\tzdata-2026.3.dist-info\METADATA
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\tzdata-2026.3.dist-info\RECORD
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\tzdata-2026.3.dist-info\top_level.txt
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\tzdata-2026.3.dist-info\WHEEL
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\tzdata-2026.3.dist-info\licenses\LICENSE
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\tzdata-2026.3.dist-info\licenses\licenses\LICENSE_APACHE
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\rpds_py-2026.6.3.dist-info\licenses\LICENSE
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\rpds_py-2026.6.3.dist-info\sboms\rpds-py.cyclonedx.json
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\jsonschema_specifications-2025.9.1.dist-info\licenses\COPYING
C:\Users\karab\PremierLeagueML\.venv\Lib\site-packages\certifi-2026.7.22.dist-info\licenses\LICENSE

In [9]:
# ============================================================
# LOAD THE FIVE PREMIER LEAGUE FIXTURE DATASETS
# ============================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# FILE PATHS
# ------------------------------------------------------------

fixture_paths = {
    2022: Path(
        r"C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\PL 2022 HomeAway.xls"
    ),

    2023: Path(
        r"C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Premier League 2023 HomeAway.xls"
    ),

    2024: Path(
        r"C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\2024 PL Season Home Away.xls"
    ),

    2025: Path(
        r"C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2024-2025\PL Season.xls"
    ),

    2026: Path(
        r"C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2025-2026\PL Season.xls"
    )
}


# ------------------------------------------------------------
# CHECK THAT FILES EXIST
# ------------------------------------------------------------

print("=" * 70)
print("CHECKING FIXTURE FILES")
print("=" * 70)

for season, path in fixture_paths.items():

    print(f"\n{season}:", path)

    if path.exists():
        print("   ✓ File found")
    else:
        print("   ✗ FILE NOT FOUND")


# ------------------------------------------------------------
# LOAD THE HTML TABLES
# ------------------------------------------------------------

fixture_raw = {}

print("\n" + "=" * 70)
print("LOADING FIXTURE DATA")
print("=" * 70)

for season, path in fixture_paths.items():

    try:

        tables = pd.read_html(path)

        print(f"\n{season}:")
        print("   Tables found:", len(tables))

        # First table is the fixture table
        fixture_raw[season] = tables[0]

        print("   Shape:", tables[0].shape)
        print("   Columns:")
        print("   ", tables[0].columns.tolist())

    except Exception as e:

        print(f"\n{season}: ERROR")
        print(e)


# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("LOADED SEASONS")
print("=" * 70)

for season, df in fixture_raw.items():

    print(
        f"{season}: "
        f"{len(df)} rows × {len(df.columns)} columns"
    )

======================================================================
CHECKING FIXTURE FILES
======================================================================

2022: C:\Users\karab\PremierLeagueML\data\raw\2022 PL Season\PL 2022 HomeAway.xls
   ✓ File found

2023: C:\Users\karab\PremierLeagueML\data\raw\2023 PL Season\Premier League 2023 HomeAway.xls
   ✓ File found

2024: C:\Users\karab\PremierLeagueML\data\raw\2024 PL Season\2024 PL Season Home Away.xls
   ✓ File found

2025: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2024-2025\PL Season.xls
   ✗ FILE NOT FOUND

2026: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2025-2026\PL Season.xls
   ✗ FILE NOT FOUND

======================================================================
LOADING FIXTURE DATA
======================================================================

2022:
   Tables found: 1
   Shape: (20, 20)
   Columns:
    [('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Squad'), ('Home', 'MP'), ('Home', 'W'), ('Home', 'D'), ('Home', 'L'), ('Home', 'GF'), ('Home', 'GA'), ('Home', 'GD'), ('Home', 'Pts'), ('Home', 'Pts/MP'), ('Away', 'MP'), ('Away', 'W'), ('Away', 'D'), ('Away', 'L'), ('Away', 'GF'), ('Away', 'GA'), ('Away', 'GD'), ('Away', 'Pts'), ('Away', 'Pts/MP')]

2023:
   Tables found: 1
   Shape: (20, 20)
   Columns:
    [('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Squad'), ('Home', 'MP'), ('Home', 'W'), ('Home', 'D'), ('Home', 'L'), ('Home', 'GF'), ('Home', 'GA'), ('Home', 'GD'), ('Home', 'Pts'), ('Home', 'Pts/MP'), ('Away', 'MP'), ('Away', 'W'), ('Away', 'D'), ('Away', 'L'), ('Away', 'GF'), ('Away', 'GA'), ('Away', 'GD'), ('Away', 'Pts'), ('Away', 'Pts/MP')]

2024:
   Tables found: 1
   Shape: (20, 20)
   Columns:
    [('Unnamed: 0_level_0', 'Rk'), ('Unnamed: 1_level_0', 'Squad'), ('Home', 'MP'), ('Home', 'W'), ('Home', 'D'), ('Home', 'L'), ('Home', 'GF'), ('Home', 'GA'), ('Home', 'GD'), ('Home', 'Pts'), ('Home', 'Pts/MP'), ('Away', 'MP'), ('Away', 'W'), ('Away', 'D'), ('Away', 'L'), ('Away', 'GF'), ('Away', 'GA'), ('Away', 'GD'), ('Away', 'Pts'), ('Away', 'Pts/MP')]

2025: ERROR
[Errno 2] No such file or directory: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2024-2025\PL Season.xls

2026: ERROR
[Errno 2] No such file or directory: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2025-2026\PL Season.xls

======================================================================
LOADED SEASONS
======================================================================
2022: 20 rows × 20 columns
2023: 20 rows × 20 columns
2024: 20 rows × 20 columns

In [10]:
# ============================================================
# FIND THE ACTUAL FIXTURE FILES
# ============================================================

from pathlib import Path

project_path = Path(r"C:\Users\karab\PremierLeagueML")

print("=" * 70)
print("EXACT FIXTURE FILES")
print("=" * 70)

fixture_paths_found = []

for file in project_path.rglob("*.xls"):

    path_text = str(file).lower()

    # Only look inside the Fixtures directory
    if "\\fixtures\\" in path_text:

        print(file)

        fixture_paths_found.append(file)


print("\n" + "=" * 70)
print("NUMBER FOUND:", len(fixture_paths_found))
print("=" * 70)

======================================================================
EXACT FIXTURE FILES
======================================================================
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2021-2022 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2022-2023 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2023-2024 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2024-2025 PL Season.xls
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2025-2026 PL Season.xls

======================================================================
NUMBER FOUND: 5
======================================================================

In [11]:
# ============================================================
# LOAD + CLEAN ALL 5 PREMIER LEAGUE FIXTURE SEASONS
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path


# ============================================================
# 1. FIXTURE FILES
# ============================================================

project_path = Path(r"C:\Users\karab\PremierLeagueML")

fixture_paths = {
    2022: project_path / "data" / "raw" / "Fixtures" / "2021-2022" / "PL Season.xls",
    2023: project_path / "data" / "raw" / "Fixtures" / "2022-2023" / "PL Season.xls",
    2024: project_path / "data" / "raw" / "Fixtures" / "2023-2024" / "PL Season.xls",
    2025: project_path / "data" / "raw" / "Fixtures" / "2024-2025" / "PL Season.xls",
    2026: project_path / "data" / "raw" / "Fixtures" / "2025-2026" / "PL Season.xls"
}


# ============================================================
# 2. LOAD RAW FIXTURE TABLES
# ============================================================

fixture_raw = {}

for season, path in fixture_paths.items():

    print(f"\nLoading {season}...")

    tables = pd.read_html(path)

    print("Tables found:", len(tables))

    fixture_raw[season] = tables[0]

    print("Raw shape:", tables[0].shape)


# ============================================================
# 3. CLEAN EACH SEASON
# ============================================================

fixtures = {}

for season, df in fixture_raw.items():

    df = df.copy()

    # --------------------------------------------------------
    # Keep only rows containing an actual Home and Away team
    # --------------------------------------------------------

    df = df.dropna(subset=["Home", "Away"]).copy()

    # --------------------------------------------------------
    # Remove rows without a completed score
    # --------------------------------------------------------

    df = df.dropna(subset=["Score"]).copy()

    # --------------------------------------------------------
    # Convert score to string
    # --------------------------------------------------------

    df["Score"] = df["Score"].astype(str)

    # --------------------------------------------------------
    # Fix the incorrectly decoded dash from FBref
    # --------------------------------------------------------

    df["Score"] = (
        df["Score"]
        .str.replace("â€“", "-", regex=False)
        .str.replace("–", "-", regex=False)
        .str.replace("—", "-", regex=False)
    )

    # --------------------------------------------------------
    # Extract Home and Away goals
    # --------------------------------------------------------

    score_parts = df["Score"].str.split("-", expand=True)

    df["HomeGoals"] = pd.to_numeric(
        score_parts[0],
        errors="coerce"
    )

    df["AwayGoals"] = pd.to_numeric(
        score_parts[1],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Remove anything where goals could not be extracted
    # --------------------------------------------------------

    df = df.dropna(
        subset=["HomeGoals", "AwayGoals"]
    ).copy()

    # --------------------------------------------------------
    # Convert goals to integers
    # --------------------------------------------------------

    df["HomeGoals"] = df["HomeGoals"].astype(int)
    df["AwayGoals"] = df["AwayGoals"].astype(int)

    # --------------------------------------------------------
    # Create result
    # --------------------------------------------------------

    df["Result"] = np.select(
        [
            df["HomeGoals"] > df["AwayGoals"],
            df["HomeGoals"] < df["AwayGoals"]
        ],
        [
            "H",
            "A"
        ],
        default="D"
    )

    # --------------------------------------------------------
    # Convert date
    # --------------------------------------------------------

    df["Date"] = pd.to_datetime(
        df["Date"],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Sort chronologically
    # --------------------------------------------------------

    df = df.sort_values(
        ["Date", "Wk"],
        na_position="last"
    ).reset_index(drop=True)

    # --------------------------------------------------------
    # Add project season label
    # --------------------------------------------------------

    df["Season"] = season

    fixtures[season] = df


# ============================================================
# 4. CHECK RESULTS
# ============================================================

print("\n" + "=" * 70)
print("CLEAN FIXTURE SUMMARY")
print("=" * 70)

for season, df in fixtures.items():

    print(
        f"\n{season}: "
        f"{len(df)} matches | "
        f"{df['Date'].min().date()} → "
        f"{df['Date'].max().date()}"
    )

    print("Results:")
    print(df["Result"].value_counts().to_dict())


# ============================================================
# 5. COMBINE ALL SEASONS
# ============================================================

fixtures_all = pd.concat(
    fixtures.values(),
    ignore_index=True
)

print("\n" + "=" * 70)
print("ALL SEASONS")
print("=" * 70)

print("Shape:", fixtures_all.shape)

print("\nMatches by season:")
print(fixtures_all.groupby("Season").size())

print("\nColumns:")
print(fixtures_all.columns.tolist())

Loading 2022...

FileNotFoundError: [Errno 2] No such file or directory: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2021-2022\PL Season.xls

In [12]:
# ============================================================
# LOAD + CLEAN ALL 5 FIXTURE SEASONS
# FIX: FBref .xls files are actually HTML
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path
from io import StringIO


# ============================================================
# 1. FIXTURE FILES
# ============================================================

project_path = Path(r"C:\Users\karab\PremierLeagueML")

fixture_paths = {
    2022: project_path / "data" / "raw" / "Fixtures" / "2021-2022" / "PL Season.xls",
    2023: project_path / "data" / "raw" / "Fixtures" / "2022-2023" / "PL Season.xls",
    2024: project_path / "data" / "raw" / "Fixtures" / "2023-2024" / "PL Season.xls",
    2025: project_path / "data" / "raw" / "Fixtures" / "2024-2025" / "PL Season.xls",
    2026: project_path / "data" / "raw" / "Fixtures" / "2025-2026" / "PL Season.xls"
}


# ============================================================
# 2. FUNCTION TO READ FBREF HTML-DISGUISED-AS-XLS
# ============================================================

def read_fbref_xls(path):

    with open(path, "rb") as f:
        content = f.read()

    # FBref files are HTML, so decode the bytes
    html = content.decode("utf-8", errors="replace")

    tables = pd.read_html(StringIO(html))

    return tables


# ============================================================
# 3. LOAD RAW FIXTURE TABLES
# ============================================================

fixture_raw = {}

print("=" * 70)
print("LOADING FIXTURE DATA")
print("=" * 70)

for season, path in fixture_paths.items():

    print(f"\nLoading {season}...")

    if not path.exists():
        print("   ERROR: file not found")
        continue

    try:

        tables = read_fbref_xls(path)

        print("   Tables found:", len(tables))

        # The fixture table is the first table
        fixture_raw[season] = tables[0]

        print("   Raw shape:", tables[0].shape)

        print("   Columns:")
        print("   ", tables[0].columns.tolist())

    except Exception as e:

        print("   ERROR:", e)


# ============================================================
# 4. CLEAN EACH SEASON
# ============================================================

fixtures = {}

for season, df in fixture_raw.items():

    print(f"\nCleaning {season}...")

    df = df.copy()

    # --------------------------------------------------------
    # Keep rows containing Home and Away teams
    # --------------------------------------------------------

    df = df.dropna(
        subset=["Home", "Away"]
    ).copy()

    # --------------------------------------------------------
    # Keep completed fixtures
    # --------------------------------------------------------

    df = df.dropna(
        subset=["Score"]
    ).copy()

    # --------------------------------------------------------
    # Convert score to string
    # --------------------------------------------------------

    df["Score"] = df["Score"].astype(str)

    # --------------------------------------------------------
    # Fix FBref character encoding
    # --------------------------------------------------------

    df["Score"] = (
        df["Score"]
        .str.replace("â€“", "-", regex=False)
        .str.replace("–", "-", regex=False)
        .str.replace("—", "-", regex=False)
    )

    # --------------------------------------------------------
    # Extract goals
    # --------------------------------------------------------

    score_parts = df["Score"].str.split(
        "-",
        expand=True
    )

    df["HomeGoals"] = pd.to_numeric(
        score_parts[0],
        errors="coerce"
    )

    df["AwayGoals"] = pd.to_numeric(
        score_parts[1],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Remove invalid scores
    # --------------------------------------------------------

    df = df.dropna(
        subset=["HomeGoals", "AwayGoals"]
    ).copy()

    # --------------------------------------------------------
    # Convert goals to integers
    # --------------------------------------------------------

    df["HomeGoals"] = df["HomeGoals"].astype(int)
    df["AwayGoals"] = df["AwayGoals"].astype(int)

    # --------------------------------------------------------
    # Result
    # --------------------------------------------------------

    df["Result"] = np.select(
        [
            df["HomeGoals"] > df["AwayGoals"],
            df["HomeGoals"] < df["AwayGoals"]
        ],
        [
            "H",
            "A"
        ],
        default="D"
    )

    # --------------------------------------------------------
    # Date
    # --------------------------------------------------------

    df["Date"] = pd.to_datetime(
        df["Date"],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Chronological order
    # --------------------------------------------------------

    df = df.sort_values(
        ["Date", "Wk"],
        na_position="last"
    ).reset_index(drop=True)

    # --------------------------------------------------------
    # Season label
    # --------------------------------------------------------

    df["Season"] = season

    fixtures[season] = df

    print(
        f"   Clean matches: {len(df)}"
    )


# ============================================================
# 5. SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("CLEAN FIXTURE SUMMARY")
print("=" * 70)

for season, df in fixtures.items():

    print(
        f"{season}: "
        f"{len(df)} matches | "
        f"{df['Date'].min().date()} → "
        f"{df['Date'].max().date()}"
    )


# ============================================================
# 6. COMBINE ALL SEASONS
# ============================================================

fixtures_all = pd.concat(
    fixtures.values(),
    ignore_index=True
)

print("\n" + "=" * 70)
print("ALL SEASONS COMBINED")
print("=" * 70)

print("Shape:", fixtures_all.shape)

print("\nMatches by season:")
print(
    fixtures_all.groupby("Season").size()
)

print("\nColumns:")
print(
    fixtures_all.columns.tolist()
)

======================================================================
LOADING FIXTURE DATA
======================================================================

Loading 2022...
   ERROR: file not found

Loading 2023...
   ERROR: file not found

Loading 2024...
   ERROR: file not found

Loading 2025...
   ERROR: file not found

Loading 2026...
   ERROR: file not found

======================================================================
CLEAN FIXTURE SUMMARY
======================================================================

ValueError: No objects to concatenate

In [13]:
# ============================================================
# LOAD + CLEAN ALL 5 PREMIER LEAGUE FIXTURE SEASONS
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path
from io import StringIO

# ============================================================
# 1. PROJECT PATH
# ============================================================

PROJECT = Path(r"C:\Users\karab\PremierLeagueML")

FIXTURE_BASE = PROJECT / "data" / "raw" / "Fixtures"


# ============================================================
# 2. EXACT FIXTURE FILES
# ============================================================

fixture_paths = {
    2022: FIXTURE_BASE / "2021-2022" / "PL Season.xls",
    2023: FIXTURE_BASE / "2022-2023" / "PL Season.xls",
    2024: FIXTURE_BASE / "2023-2024" / "PL Season.xls",
    2025: FIXTURE_BASE / "2024-2025" / "PL Season.xls",
    2026: FIXTURE_BASE / "2025-2026" / "PL Season.xls",
}


# ============================================================
# 3. READ FBREF .XLS
# ============================================================

def read_fbref_html_xls(path):

    # IMPORTANT:
    # Read the actual file bytes first.
    # Do NOT give the Path directly to pd.read_html().

    with open(path, "rb") as f:
        content = f.read()

    # FBref .xls files are actually HTML
    html = content.decode("utf-8", errors="replace")

    # Feed HTML text to pandas
    tables = pd.read_html(StringIO(html))

    return tables


# ============================================================
# 4. LOAD EACH SEASON
# ============================================================

fixture_raw = {}

print("=" * 70)
print("CHECKING FIXTURE FILES")
print("=" * 70)

for season, path in fixture_paths.items():

    print(f"\n{season}:")
    print(path)

    if not path.exists():
        print("   ❌ FILE NOT FOUND")
        continue

    print("   ✓ File exists")

    try:

        tables = read_fbref_html_xls(path)

        print("   Tables found:", len(tables))

        if len(tables) == 0:
            print("   ❌ No tables found")
            continue

        # First table is the fixture table
        fixture_raw[season] = tables[0]

        print("   Raw shape:", tables[0].shape)

    except Exception as e:

        print("   ❌ ERROR:", repr(e))


# ============================================================
# 5. MAKE SURE SOMETHING LOADED
# ============================================================

print("\n" + "=" * 70)
print("LOADED SEASONS")
print("=" * 70)

for season, df in fixture_raw.items():
    print(f"{season}: {df.shape}")


if not fixture_raw:
    raise RuntimeError(
        "\nNO FIXTURE DATA WAS LOADED.\n"
        "Check the file paths and the HTML contents of the files."
    )


# ============================================================
# 6. CLEAN FUNCTION
# ============================================================

def clean_fixture_table(df, season):

    df = df.copy()

    # --------------------------------------------------------
    # Keep actual fixtures
    # --------------------------------------------------------

    df = df.dropna(
        subset=["Home", "Away", "Score"]
    ).copy()

    # --------------------------------------------------------
    # Score → string
    # --------------------------------------------------------

    df["Score"] = df["Score"].astype(str)

    # --------------------------------------------------------
    # Clean different dash characters
    # --------------------------------------------------------

    df["Score"] = (
        df["Score"]
        .str.replace("â€“", "-", regex=False)
        .str.replace("–", "-", regex=False)
        .str.replace("—", "-", regex=False)
        .str.strip()
    )

    # --------------------------------------------------------
    # Extract goals
    # --------------------------------------------------------

    score_parts = df["Score"].str.extract(
        r"^\s*(\d+)\s*-\s*(\d+)\s*$"
    )

    df["HomeGoals"] = pd.to_numeric(
        score_parts[0],
        errors="coerce"
    )

    df["AwayGoals"] = pd.to_numeric(
        score_parts[1],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Remove invalid/incomplete fixtures
    # --------------------------------------------------------

    df = df.dropna(
        subset=["HomeGoals", "AwayGoals"]
    ).copy()

    # --------------------------------------------------------
    # Integer goals
    # --------------------------------------------------------

    df["HomeGoals"] = df["HomeGoals"].astype(int)
    df["AwayGoals"] = df["AwayGoals"].astype(int)

    # --------------------------------------------------------
    # Result
    # --------------------------------------------------------

    df["Result"] = np.select(
        [
            df["HomeGoals"] > df["AwayGoals"],
            df["HomeGoals"] < df["AwayGoals"]
        ],
        [
            "H",
            "A"
        ],
        default="D"
    )

    # --------------------------------------------------------
    # Date
    # --------------------------------------------------------

    df["Date"] = pd.to_datetime(
        df["Date"],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Matchweek
    # --------------------------------------------------------

    df["Wk"] = pd.to_numeric(
        df["Wk"],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Remove rows without dates
    # --------------------------------------------------------

    df = df.dropna(
        subset=["Date"]
    ).copy()

    # --------------------------------------------------------
    # Sort chronologically
    # --------------------------------------------------------

    df = df.sort_values(
        ["Date", "Wk"]
    ).reset_index(drop=True)

    # --------------------------------------------------------
    # Season
    # --------------------------------------------------------

    df["Season"] = season

    return df


# ============================================================
# 7. CLEAN ALL SEASONS
# ============================================================

fixtures = {}

print("\n" + "=" * 70)
print("CLEANING FIXTURES")
print("=" * 70)

for season, raw_df in fixture_raw.items():

    print(f"\nCleaning {season}...")

    cleaned = clean_fixture_table(
        raw_df,
        season
    )

    fixtures[season] = cleaned

    print("   Matches:", len(cleaned))
    print(
        "   Date:",
        cleaned["Date"].min().date(),
        "→",
        cleaned["Date"].max().date()
    )

    print(
        "   Results:",
        cleaned["Result"].value_counts().to_dict()
    )


# ============================================================
# 8. COMBINE ALL SEASONS
# ============================================================

fixtures_all = pd.concat(
    list(fixtures.values()),
    ignore_index=True
)

# Sort the combined dataset
fixtures_all = fixtures_all.sort_values(
    ["Date", "Season", "Wk"]
).reset_index(drop=True)


# ============================================================
# 9. FINAL CHECKS
# ============================================================

print("\n" + "=" * 70)
print("FINAL FIXTURE DATASET")
print("=" * 70)

print("\nShape:")
print(fixtures_all.shape)

print("\nMatches by season:")
print(
    fixtures_all.groupby("Season").size()
)

print("\nMissing values:")
print(
    fixtures_all[
        ["Date", "Home", "Away",
         "HomeGoals", "AwayGoals", "Result"]
    ].isna().sum()
)

print("\nResult distribution:")
print(
    fixtures_all["Result"].value_counts()
)

print("\nFirst 10:")
print(
    fixtures_all[
        ["Season", "Wk", "Date", "Home",
         "Away", "HomeGoals", "AwayGoals", "Result"]
    ].head(10)
)

print("\nLast 10:")
print(
    fixtures_all[
        ["Season", "Wk", "Date", "Home",
         "Away", "HomeGoals", "AwayGoals", "Result"]
    ].tail(10)
)


# ============================================================
# 10. CHECK CHRONOLOGICAL ORDER
# ============================================================

print("\nChronological order:")

print(
    fixtures_all["Date"].is_monotonic_increasing
)


# ============================================================
# 11. CHECK MATCHWEEKS
# ============================================================

print("\nMatchweeks by season:")

for season, df in fixtures.items():

    print(
        season,
        "→",
        sorted(df["Wk"].dropna().unique())
    )


# ============================================================
# 12. SAVE CLEAN FIXTURES
# ============================================================

processed_path = (
    PROJECT
    / "data"
    / "processed"
    / "fixtures_all.csv"
)

processed_path.parent.mkdir(
    parents=True,
    exist_ok=True
)

fixtures_all.to_csv(
    processed_path,
    index=False
)

print("\nSaved to:")
print(processed_path)

======================================================================
CHECKING FIXTURE FILES
======================================================================

2022:
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2021-2022\PL Season.xls
   ❌ FILE NOT FOUND

2023:
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2022-2023\PL Season.xls
   ❌ FILE NOT FOUND

2024:
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2023-2024\PL Season.xls
   ❌ FILE NOT FOUND

2025:
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2024-2025\PL Season.xls
   ❌ FILE NOT FOUND

2026:
C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2025-2026\PL Season.xls
   ❌ FILE NOT FOUND

======================================================================
LOADED SEASONS
======================================================================

RuntimeError:
NO FIXTURE DATA WAS LOADED.
Check the file paths and the HTML contents of the files.

In [14]:
# ============================================================
# ROBUST FIXTURE LOADER — ALL 5 PREMIER LEAGUE SEASONS
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path
from io import StringIO

# ============================================================
# 1. PROJECT PATH
# ============================================================

PROJECT_PATH = Path(r"C:\Users\karab\PremierLeagueML")

FIXTURES_PATH = PROJECT_PATH / "data" / "raw" / "Fixtures"

print("Project:")
print(PROJECT_PATH)

print("\nFixtures folder:")
print(FIXTURES_PATH)

print("\nExists:", FIXTURES_PATH.exists())


# ============================================================
# 2. SEASON FOLDERS
# ============================================================

season_folders = {
    2022: "2021-2022",
    2023: "2022-2023",
    2024: "2023-2024",
    2025: "2024-2025",
    2026: "2025-2026"
}


# ============================================================
# 3. FIND THE ACTUAL XLS FILE
# ============================================================

def find_fixture_file(folder):

    folder_path = FIXTURES_PATH / folder

    if not folder_path.exists():
        return None

    # Find every .xls file
    files = list(folder_path.glob("*.xls"))

    if len(files) == 0:
        return None

    # If there are multiple files, look for one containing PL
    pl_files = [
        f for f in files
        if "PL" in f.name.upper()
    ]

    if pl_files:
        return pl_files[0]

    return files[0]


# ============================================================
# 4. DISPLAY WHAT WE FOUND
# ============================================================

print("\n" + "=" * 70)
print("FINDING FIXTURE FILES")
print("=" * 70)

fixture_paths = {}

for season, folder in season_folders.items():

    path = find_fixture_file(folder)

    if path is None:

        print(f"\n{season}: ❌ NOT FOUND")
        print("Folder:", FIXTURES_PATH / folder)

    else:

        fixture_paths[season] = path

        print(f"\n{season}: ✓ FOUND")
        print(path)


# ============================================================
# 5. READ FBREF HTML-DISGUISED-AS-XLS
# ============================================================

def read_fbref_xls(path):

    with open(path, "rb") as f:
        content = f.read()

    html = content.decode(
        "utf-8",
        errors="replace"
    )

    tables = pd.read_html(
        StringIO(html)
    )

    return tables


# ============================================================
# 6. LOAD FIXTURES
# ============================================================

fixture_raw = {}

print("\n" + "=" * 70)
print("LOADING FIXTURE DATA")
print("=" * 70)

for season, path in fixture_paths.items():

    print(f"\nLoading {season}...")
    print("File:", path)

    try:

        tables = read_fbref_xls(path)

        print("Tables found:", len(tables))

        # Find the table containing Home + Away
        fixture_table = None

        for table in tables:

            columns = table.columns

            # Flatten MultiIndex columns if necessary
            column_names = []

            for col in columns:

                if isinstance(col, tuple):
                    column_names.extend(
                        [str(x) for x in col]
                    )
                else:
                    column_names.append(str(col))

            column_text = " ".join(
                column_names
            )

            if "Home" in column_text and "Away" in column_text:

                fixture_table = table
                break

        # Fallback to first table
        if fixture_table is None:

            fixture_table = tables[0]

        fixture_raw[season] = fixture_table

        print(
            "Raw shape:",
            fixture_table.shape
        )

    except Exception as e:

        print(
            "❌ ERROR:",
            repr(e)
        )


# ============================================================
# 7. CHECK LOADED SEASONS
# ============================================================

print("\n" + "=" * 70)
print("LOADED SEASONS")
print("=" * 70)

for season, df in fixture_raw.items():

    print(
        f"{season}: {df.shape}"
    )

if not fixture_raw:

    raise RuntimeError(
        "NO FIXTURE DATA WAS LOADED."
    )


# ============================================================
# 8. CLEAN FIXTURES
# ============================================================

fixtures = {}

print("\n" + "=" * 70)
print("CLEANING FIXTURES")
print("=" * 70)

for season, df in fixture_raw.items():

    print(f"\nCleaning {season}...")

    df = df.copy()

    # --------------------------------------------------------
    # Keep completed fixtures
    # --------------------------------------------------------

    if "Home" not in df.columns or "Away" not in df.columns:

        print(
            "❌ Home/Away columns not found."
        )

        print(
            df.columns.tolist()
        )

        continue

    df = df.dropna(
        subset=["Home", "Away"]
    ).copy()

    if "Score" not in df.columns:

        print(
            "❌ Score column not found."
        )

        continue

    df = df.dropna(
        subset=["Score"]
    ).copy()

    # --------------------------------------------------------
    # Clean score
    # --------------------------------------------------------

    df["Score"] = (
        df["Score"]
        .astype(str)
        .str.replace("â€“", "-", regex=False)
        .str.replace("–", "-", regex=False)
        .str.replace("—", "-", regex=False)
        .str.strip()
    )

    # --------------------------------------------------------
    # Extract goals
    # --------------------------------------------------------

    score_parts = df["Score"].str.extract(
        r"(\d+)\s*-\s*(\d+)"
    )

    df["HomeGoals"] = pd.to_numeric(
        score_parts[0],
        errors="coerce"
    )

    df["AwayGoals"] = pd.to_numeric(
        score_parts[1],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Remove incomplete/invalid fixtures
    # --------------------------------------------------------

    df = df.dropna(
        subset=[
            "HomeGoals",
            "AwayGoals"
        ]
    ).copy()

    df["HomeGoals"] = (
        df["HomeGoals"]
        .astype(int)
    )

    df["AwayGoals"] = (
        df["AwayGoals"]
        .astype(int)
    )

    # --------------------------------------------------------
    # Result
    # --------------------------------------------------------

    df["Result"] = np.select(
        [
            df["HomeGoals"] > df["AwayGoals"],
            df["HomeGoals"] < df["AwayGoals"]
        ],
        [
            "H",
            "A"
        ],
        default="D"
    )

    # --------------------------------------------------------
    # Date
    # --------------------------------------------------------

    if "Date" in df.columns:

        df["Date"] = pd.to_datetime(
            df["Date"],
            errors="coerce"
        )

    # --------------------------------------------------------
    # Matchweek
    # --------------------------------------------------------

    if "Wk" in df.columns:

        df["Wk"] = pd.to_numeric(
            df["Wk"],
            errors="coerce"
        )

    # --------------------------------------------------------
    # Sort chronologically
    # --------------------------------------------------------

    sort_columns = []

    if "Date" in df.columns:
        sort_columns.append("Date")

    if "Wk" in df.columns:
        sort_columns.append("Wk")

    if sort_columns:

        df = df.sort_values(
            sort_columns
        )

    df = df.reset_index(
        drop=True
    )

    # --------------------------------------------------------
    # Season
    # --------------------------------------------------------

    df["Season"] = season

    fixtures[season] = df

    print(
        f"✓ {season}: {len(df)} completed matches"
    )


# ============================================================
# 9. SEASON SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("SEASON SUMMARY")
print("=" * 70)

for season, df in fixtures.items():

    print(
        f"\n{season}:"
    )

    print(
        "Matches:",
        len(df)
    )

    if "Date" in df.columns:

        print(
            "Date:",
            df["Date"].min(),
            "→",
            df["Date"].max()
        )

    if "Wk" in df.columns:

        print(
            "Matchweeks:",
            df["Wk"].nunique()
        )


# ============================================================
# 10. COMBINE ALL FIVE SEASONS
# ============================================================

fixtures_all = pd.concat(
    list(fixtures.values()),
    ignore_index=True
)

print("\n" + "=" * 70)
print("ALL FIVE SEASONS")
print("=" * 70)

print(
    "Shape:",
    fixtures_all.shape
)

print("\nMatches per season:")

print(
    fixtures_all
    .groupby("Season")
    .size()
)

print("\nColumns:")

print(
    fixtures_all.columns.tolist()
)


# ============================================================
# 11. BASIC VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("VALIDATION")
print("=" * 70)

print(
    "\nMissing Home:",
    fixtures_all["Home"].isna().sum()
)

print(
    "Missing Away:",
    fixtures_all["Away"].isna().sum()
)

print(
    "Missing HomeGoals:",
    fixtures_all["HomeGoals"].isna().sum()
)

print(
    "Missing AwayGoals:",
    fixtures_all["AwayGoals"].isna().sum()
)

print(
    "Missing Result:",
    fixtures_all["Result"].isna().sum()
)

print(
    "\nResult distribution:"
)

print(
    fixtures_all["Result"]
    .value_counts()
)

print("\n✓ FIXTURE LOADING COMPLETE")

Project:
C:\Users\karab\PremierLeagueML

Fixtures folder:
C:\Users\karab\PremierLeagueML\data\raw\Fixtures

Exists: True

======================================================================
FINDING FIXTURE FILES
======================================================================

2022: ❌ NOT FOUND
Folder: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2021-2022

2023: ❌ NOT FOUND
Folder: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2022-2023

2024: ❌ NOT FOUND
Folder: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2023-2024

2025: ❌ NOT FOUND
Folder: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2024-2025

2026: ❌ NOT FOUND
Folder: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2025-2026

======================================================================
LOADING FIXTURE DATA
======================================================================

======================================================================
LOADED SEASONS
======================================================================

RuntimeError: NO FIXTURE DATA WAS LOADED.

In [1]:
# ============================================================
# PREMIER LEAGUE ML
# STEP 1 — RELIABLE FIXTURE LOADER
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path
from io import StringIO


# ============================================================
# 1. PROJECT PATH
# ============================================================

PROJECT_PATH = Path(r"C:\Users\karab\PremierLeagueML")

FIXTURES_PATH = PROJECT_PATH / "data" / "raw" / "Fixtures"


print("=" * 70)
print("PROJECT")
print("=" * 70)

print("Project:", PROJECT_PATH)
print("Fixtures:", FIXTURES_PATH)

if not PROJECT_PATH.exists():
    raise FileNotFoundError(
        f"Project path does not exist:\n{PROJECT_PATH}"
    )

if not FIXTURES_PATH.exists():
    raise FileNotFoundError(
        f"Fixtures folder does not exist:\n{FIXTURES_PATH}"
    )


# ============================================================
# 2. FIND ALL PL SEASON FILES AUTOMATICALLY
# ============================================================

print("\n" + "=" * 70)
print("SEARCHING FOR FIXTURE FILES")
print("=" * 70)

all_fixture_files = list(
    FIXTURES_PATH.rglob("*.xls")
)

print(f"\nTotal .xls files found: {len(all_fixture_files)}")


# Only keep files called "PL Season.xls"
fixture_files = []

for file in all_fixture_files:

    if file.name.lower() == "pl season.xls":
        fixture_files.append(file)


print(f"PL Season files found: {len(fixture_files)}")


# ============================================================
# 3. DISPLAY WHAT WAS FOUND
# ============================================================

for file in sorted(fixture_files):

    print("\n", file)


# ============================================================
# 4. EXPECT EXACTLY FIVE SEASONS
# ============================================================

expected_seasons = {
    "2021-2022": 2022,
    "2022-2023": 2023,
    "2023-2024": 2024,
    "2024-2025": 2025,
    "2025-2026": 2026
}


fixture_paths = {}


for file in fixture_files:

    parent_name = file.parent.name

    if parent_name in expected_seasons:

        season = expected_seasons[parent_name]

        fixture_paths[season] = file


# ============================================================
# 5. CHECK SEASONS
# ============================================================

print("\n" + "=" * 70)
print("SEASON FILE CHECK")
print("=" * 70)

for season in sorted(expected_seasons.values()):

    if season in fixture_paths:

        print(
            f"{season}: ✓ FOUND\n"
            f"      {fixture_paths[season]}"
        )

    else:

        print(
            f"{season}: ✗ NOT FOUND"
        )


# ============================================================
# 6. STOP IF ANY SEASON IS MISSING
# ============================================================

missing_seasons = [
    season
    for season in expected_seasons.values()
    if season not in fixture_paths
]


if missing_seasons:

    raise RuntimeError(
        "\nMissing fixture seasons: "
        + ", ".join(map(str, missing_seasons))
        + "\n\nCheck the filenames/folders above."
    )


# ============================================================
# 7. FBREF HTML READER
# ============================================================

def read_fbref_xls(path):

    with open(path, "rb") as f:
        content = f.read()

    html = content.decode(
        "utf-8",
        errors="replace"
    )

    tables = pd.read_html(
        StringIO(html)
    )

    return tables


# ============================================================
# 8. LOAD EACH SEASON
# ============================================================

fixture_raw = {}

print("\n" + "=" * 70)
print("LOADING FIXTURES")
print("=" * 70)


for season in sorted(fixture_paths):

    path = fixture_paths[season]

    print(f"\nLoading {season}...")
    print("File:", path)

    tables = read_fbref_xls(path)

    print("Tables found:", len(tables))

    # First table is the fixture table
    df = tables[0].copy()

    print("Raw shape:", df.shape)

    fixture_raw[season] = df


# ============================================================
# 9. BASIC INSPECTION
# ============================================================

print("\n" + "=" * 70)
print("RAW FIXTURE DATA CHECK")
print("=" * 70)


for season, df in fixture_raw.items():

    print(
        f"\n{season}:"
        f"\nShape: {df.shape}"
        f"\nColumns:"
    )

    print(df.columns.tolist())

    print("\nFirst 3 rows:")

    print(
        df.head(3)
    )


# ============================================================
# 10. CONFIRM EVERYTHING LOADED
# ============================================================

print("\n" + "=" * 70)
print("SUCCESS")
print("=" * 70)

print(
    f"\nSuccessfully loaded "
    f"{len(fixture_raw)} seasons."
)

print(
    "Next step: clean and standardise "
    "the five fixture tables."
)

======================================================================
PROJECT
======================================================================
Project: C:\Users\karab\PremierLeagueML
Fixtures: C:\Users\karab\PremierLeagueML\data\raw\Fixtures

======================================================================
SEARCHING FOR FIXTURE FILES
======================================================================

Total .xls files found: 5
PL Season files found: 0

======================================================================
SEASON FILE CHECK
======================================================================
2022: ✗ NOT FOUND
2023: ✗ NOT FOUND
2024: ✗ NOT FOUND
2025: ✗ NOT FOUND
2026: ✗ NOT FOUND

RuntimeError:
Missing fixture seasons: 2022, 2023, 2024, 2025, 2026

Check the filenames/folders above.

In [2]:
# ============================================================
# STEP 1 — LOAD AND CLEAN ALL 5 PREMIER LEAGUE SEASONS
# ============================================================

import pandas as pd
import numpy as np
import io
from pathlib import Path


# ============================================================
# 1. PROJECT PATH
# ============================================================

project_path = Path(r"C:\Users\karab\PremierLeagueML")


# ============================================================
# 2. EXACT FIXTURE PATHS
# ============================================================

fixture_paths = {
    2022: project_path / "data" / "raw" / "Fixtures" / "2021-2022 PL Season.xls",
    2023: project_path / "data" / "raw" / "Fixtures" / "2022-2023 PL Season.xls",
    2024: project_path / "data" / "raw" / "Fixtures" / "2023-2024 PL Season.xls",
    2025: project_path / "data" / "raw" / "Fixtures" / "2024-2025 PL Season.xls",
    2026: project_path / "data" / "raw" / "Fixtures" / "2025-2026 PL Season.xls"
}


# ============================================================
# 3. FUNCTION TO LOAD FBREF HTML-DISGUISED-AS-XLS
# ============================================================

def load_fixture_file(path):

    # Files are HTML, not real Excel files
    with open(path, encoding="utf-8") as fh:
        html = fh.read()

    # Parse the HTML table
    df = pd.read_html(io.StringIO(html))[0]

    return df


# ============================================================
# 4. LOAD + CLEAN EACH SEASON
# ============================================================

fixtures = {}

print("=" * 70)
print("LOADING PREMIER LEAGUE FIXTURES")
print("=" * 70)

for season, path in fixture_paths.items():

    print(f"\nLoading {season}...")
    print("Path:", path)

    # Check file exists
    if not path.exists():
        raise FileNotFoundError(
            f"\nFixture file not found:\n{path}"
        )

    # Load HTML table
    df = load_fixture_file(path)

    print("Raw shape:", df.shape)

    # --------------------------------------------------------
    # Remove completely empty spacer rows
    # --------------------------------------------------------

    df = df[df["Date"].notna()].copy()

    # --------------------------------------------------------
    # Date
    # --------------------------------------------------------

    df["Date"] = pd.to_datetime(
        df["Date"],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Matchweek
    # --------------------------------------------------------

    df["Wk"] = pd.to_numeric(
        df["Wk"],
        errors="coerce"
    ).astype(int)

    # --------------------------------------------------------
    # Home / Away
    # --------------------------------------------------------

    df["Home"] = df["Home"].astype(str).str.strip()
    df["Away"] = df["Away"].astype(str).str.strip()

    # --------------------------------------------------------
    # Extract goals
    #
    # This deliberately does NOT split on "-"
    # because FBref uses an en-dash.
    # --------------------------------------------------------

    goals = df["Score"].astype(str).str.extract(
        r"(\d+)\D+(\d+)"
    )

    df["HomeGoals"] = pd.to_numeric(
        goals[0],
        errors="coerce"
    )

    df["AwayGoals"] = pd.to_numeric(
        goals[1],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Remove rows where score could not be interpreted
    # --------------------------------------------------------

    df = df.dropna(
        subset=[
            "Date",
            "Home",
            "Away",
            "HomeGoals",
            "AwayGoals"
        ]
    ).copy()

    # --------------------------------------------------------
    # Convert goals to integers
    # --------------------------------------------------------

    df["HomeGoals"] = df["HomeGoals"].astype(int)
    df["AwayGoals"] = df["AwayGoals"].astype(int)

    # --------------------------------------------------------
    # Match result
    # --------------------------------------------------------

    df["Result"] = np.select(
        [
            df["HomeGoals"] > df["AwayGoals"],
            df["HomeGoals"] < df["AwayGoals"]
        ],
        [
            "H",
            "A"
        ],
        default="D"
    )

    # --------------------------------------------------------
    # Season
    # --------------------------------------------------------

    df["Season"] = season

    # --------------------------------------------------------
    # Sort chronologically
    # --------------------------------------------------------

    df = df.sort_values(
        ["Date", "Wk"]
    ).reset_index(drop=True)

    # --------------------------------------------------------
    # Keep useful columns
    # --------------------------------------------------------

    df = df[
        [
            "Season",
            "Wk",
            "Date",
            "Home",
            "Away",
            "Score",
            "HomeGoals",
            "AwayGoals",
            "Result"
        ]
    ]

    fixtures[season] = df

    print("Clean shape:", df.shape)
    print(
        "Date range:",
        df["Date"].min().date(),
        "→",
        df["Date"].max().date()
    )

    print(
        "Matchweeks:",
        df["Wk"].nunique()
    )


# ============================================================
# 5. COMBINE ALL SEASONS
# ============================================================

fixtures_all = pd.concat(
    fixtures.values(),
    ignore_index=True
)


# ============================================================
# 6. SORT EVERYTHING
# ============================================================

fixtures_all = fixtures_all.sort_values(
    ["Season", "Date", "Wk"]
).reset_index(drop=True)


# ============================================================
# 7. FINAL VALIDATION
# ============================================================

print("\n")
print("=" * 70)
print("FINAL FIXTURE DATASET")
print("=" * 70)

print("\nShape:")
print(fixtures_all.shape)

print("\nMatches per season:")
print(
    fixtures_all.groupby("Season").size()
)

print("\nMatchweeks per season:")
print(
    fixtures_all.groupby("Season")["Wk"].nunique()
)

print("\nMissing values:")
print(
    fixtures_all[
        [
            "Season",
            "Wk",
            "Date",
            "Home",
            "Away",
            "HomeGoals",
            "AwayGoals",
            "Result"
        ]
    ].isna().sum()
)

print("\nNumber of teams:")
print(
    len(
        set(fixtures_all["Home"])
        |
        set(fixtures_all["Away"])
    )
)

print("\nFirst 10 matches:")
print(
    fixtures_all.head(10).to_string(index=False)
)

print("\nLast 10 matches:")
print(
    fixtures_all.tail(10).to_string(index=False)
)

======================================================================
LOADING PREMIER LEAGUE FIXTURES
======================================================================

Loading 2022...
Path: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2021-2022 PL Season.xls
Raw shape: (448, 12)
Clean shape: (380, 9)
Date range: 2021-08-13 → 2022-05-22
Matchweeks: 38

Loading 2023...
Path: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2022-2023 PL Season.xls
Raw shape: (430, 12)
Clean shape: (380, 9)
Date range: 2022-08-05 → 2023-05-28
Matchweeks: 38

Loading 2024...
Path: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2023-2024 PL Season.xls
Raw shape: (423, 12)
Clean shape: (380, 9)
Date range: 2023-08-11 → 2024-05-19
Matchweeks: 38

Loading 2025...
Path: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2024-2025 PL Season.xls
Raw shape: (420, 12)
Clean shape: (380, 9)
Date range: 2024-08-16 → 2025-05-25
Matchweeks: 38

Loading 2026...
Path: C:\Users\karab\PremierLeagueML\data\raw\Fixtures\2025-2026 PL Season.xls
Raw shape: (419, 12)
Clean shape: (380, 9)
Date range: 2025-08-15 → 2026-05-24
Matchweeks: 38


======================================================================
FINAL FIXTURE DATASET
======================================================================

Shape:
(1900, 9)

Matches per season:
Season
2022    380
2023    380
2024    380
2025    380
2026    380
dtype: int64

Matchweeks per season:
Season
2022    38
2023    38
2024    38
2025    38
2026    38
Name: Wk, dtype: int64

Missing values:
Season       0
Wk           0
Date         0
Home         0
Away         0
HomeGoals    0
AwayGoals    0
Result       0
dtype: int64

Number of teams:
27

First 10 matches:
 Season  Wk       Date           Home            Away Score  HomeGoals  AwayGoals Result
   2022   1 2021-08-13      Brentford         Arsenal   2–0          2          0      H
   2022   1 2021-08-14 Manchester Utd    Leeds United   5–1          5          1      H
   2022   1 2021-08-14 Leicester City          Wolves   1–0          1          0      H
   2022   1 2021-08-14        Burnley        Brighton   1–2          1          2      A
   2022   1 2021-08-14        Chelsea  Crystal Palace   3–0          3          0      H
   2022   1 2021-08-14        Watford     Aston Villa   3–2          3          2      H
   2022   1 2021-08-14        Everton     Southampton   3–1          3          1      H
   2022   1 2021-08-14   Norwich City       Liverpool   0–3          0          3      A
   2022   1 2021-08-15      Newcastle        West Ham   2–4          2          4      A
   2022   1 2021-08-15      Tottenham Manchester City   1–0          1          0      H

Last 10 matches:
 Season  Wk       Date            Home           Away Score  HomeGoals  AwayGoals Result
   2026  38 2026-05-24       Tottenham        Everton   1–0          1          0      H
   2026  38 2026-05-24      Sunderland        Chelsea   2–1          2          1      H
   2026  38 2026-05-24         Burnley         Wolves   1–1          1          1      D
   2026  38 2026-05-24          Fulham      Newcastle   2–0          2          0      H
   2026  38 2026-05-24        Brighton Manchester Utd   0–3          0          3      A
   2026  38 2026-05-24      Nottingham    Bournemouth   1–1          1          1      D
   2026  38 2026-05-24 Manchester City    Aston Villa   1–2          1          2      A
   2026  38 2026-05-24       Liverpool      Brentford   1–1          1          1      D
   2026  38 2026-05-24  Crystal Palace        Arsenal   1–2          1          2      A
   2026  38 2026-05-24        West Ham   Leeds United   3–0          3          0      H

In [3]:
# ============================================================
# STEP 1 — BUILD PRE-MATCH HISTORICAL FEATURES
# ============================================================

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# Make a working copy
# ------------------------------------------------------------

df = fixtures_all.copy()

# Make absolutely sure matches are chronological
df = df.sort_values(
    ["Date", "Season", "Wk"]
).reset_index(drop=True)

print("=" * 70)
print("BUILDING PRE-MATCH FEATURES")
print("=" * 70)


# ============================================================
# 1. INITIALISE TEAM HISTORY
# ============================================================

team_history = {}

feature_rows = []


# ============================================================
# 2. PROCESS MATCHES IN CHRONOLOGICAL ORDER
# ============================================================

for idx, match in df.iterrows():

    home = match["Home"]
    away = match["Away"]

    season = match["Season"]
    date = match["Date"]

    # --------------------------------------------------------
    # Create team history if this is the team's first match
    # --------------------------------------------------------

    if home not in team_history:
        team_history[home] = {
            "points": 0,
            "goals_for": 0,
            "goals_against": 0,
            "games": 0,
            "last5": [],
            "last_date": None
        }

    if away not in team_history:
        team_history[away] = {
            "points": 0,
            "goals_for": 0,
            "goals_against": 0,
            "games": 0,
            "last5": [],
            "last_date": None
        }


    h = team_history[home]
    a = team_history[away]


    # ========================================================
    # HOME PRE-MATCH FEATURES
    # ========================================================

    if h["games"] > 0:

        home_ppg = h["points"] / h["games"]

        home_gf_pg = (
            h["goals_for"] /
            h["games"]
        )

        home_ga_pg = (
            h["goals_against"] /
            h["games"]
        )

    else:

        home_ppg = np.nan
        home_gf_pg = np.nan
        home_ga_pg = np.nan


    # ========================================================
    # AWAY PRE-MATCH FEATURES
    # ========================================================

    if a["games"] > 0:

        away_ppg = a["points"] / a["games"]

        away_gf_pg = (
            a["goals_for"] /
            a["games"]
        )

        away_ga_pg = (
            a["goals_against"] /
            a["games"]
        )

    else:

        away_ppg = np.nan
        away_gf_pg = np.nan
        away_ga_pg = np.nan


    # ========================================================
    # LAST 5 FORM
    # ========================================================

    if len(h["last5"]) > 0:
        home_last5_ppg = np.mean(h["last5"])
    else:
        home_last5_ppg = np.nan


    if len(a["last5"]) > 0:
        away_last5_ppg = np.mean(a["last5"])
    else:
        away_last5_ppg = np.nan


    # ========================================================
    # REST DAYS
    # ========================================================

    if h["last_date"] is not None:

        home_rest = (
            date - h["last_date"]
        ).days

    else:

        home_rest = np.nan


    if a["last_date"] is not None:

        away_rest = (
            date - a["last_date"]
        ).days

    else:

        away_rest = np.nan


    # ========================================================
    # STORE PRE-MATCH FEATURES
    # ========================================================

    feature_rows.append({

        "Season": season,
        "Wk": match["Wk"],
        "Date": date,

        "Home": home,
        "Away": away,

        "HomeGoals": match["HomeGoals"],
        "AwayGoals": match["AwayGoals"],
        "Result": match["Result"],

        # Historical performance
        "Home_PPG_Before": home_ppg,
        "Away_PPG_Before": away_ppg,

        "Home_GF_PerGame_Before": home_gf_pg,
        "Away_GF_PerGame_Before": away_gf_pg,

        "Home_GA_PerGame_Before": home_ga_pg,
        "Away_GA_PerGame_Before": away_ga_pg,

        # Recent form
        "Home_Last5_PPG": home_last5_ppg,
        "Away_Last5_PPG": away_last5_ppg,

        # Rest
        "Home_Rest_Days": home_rest,
        "Away_Rest_Days": away_rest
    })


    # ========================================================
    # UPDATE HISTORY AFTER THE MATCH
    # ========================================================

    home_goals = match["HomeGoals"]
    away_goals = match["AwayGoals"]


    # Goals
    h["goals_for"] += home_goals
    h["goals_against"] += away_goals

    a["goals_for"] += away_goals
    a["goals_against"] += home_goals


    # Points
    if home_goals > away_goals:

        h["points"] += 3
        a["points"] += 0

        home_points = 3
        away_points = 0

    elif home_goals < away_goals:

        h["points"] += 0
        a["points"] += 3

        home_points = 0
        away_points = 3

    else:

        h["points"] += 1
        a["points"] += 1

        home_points = 1
        away_points = 1


    # Games
    h["games"] += 1
    a["games"] += 1


    # Last 5
    h["last5"].append(home_points)
    a["last5"].append(away_points)

    h["last5"] = h["last5"][-5:]
    a["last5"] = a["last5"][-5:]


    # Last match date
    h["last_date"] = date
    a["last_date"] = date


# ============================================================
# 3. CREATE FEATURE DATAFRAME
# ============================================================

fixture_features = pd.DataFrame(feature_rows)


# ============================================================
# 4. CREATE DIFFERENCE FEATURES
# ============================================================

fixture_features["PPG_Difference"] = (
    fixture_features["Home_PPG_Before"]
    -
    fixture_features["Away_PPG_Before"]
)

fixture_features["GF_PerGame_Difference"] = (
    fixture_features["Home_GF_PerGame_Before"]
    -
    fixture_features["Away_GF_PerGame_Before"]
)

fixture_features["GA_PerGame_Difference"] = (
    fixture_features["Home_GA_PerGame_Before"]
    -
    fixture_features["Away_GA_PerGame_Before"]
)

fixture_features["Last5_PPG_Difference"] = (
    fixture_features["Home_Last5_PPG"]
    -
    fixture_features["Away_Last5_PPG"]
)

fixture_features["Rest_Difference"] = (
    fixture_features["Home_Rest_Days"]
    -
    fixture_features["Away_Rest_Days"]
)


# ============================================================
# 5. CHECK RESULT
# ============================================================

print("\n" + "=" * 70)
print("FEATURE DATASET CREATED")
print("=" * 70)

print("\nShape:")
print(fixture_features.shape)

print("\nColumns:")
print(fixture_features.columns.tolist())

print("\nFirst 15 matches:")
print(
    fixture_features.head(15).to_string(index=False)
)

print("\nMissing values:")
print(
    fixture_features.isna().sum()
)

======================================================================
BUILDING PRE-MATCH FEATURES
======================================================================

======================================================================
FEATURE DATASET CREATED
======================================================================

Shape:
(1900, 23)

Columns:
['Season', 'Wk', 'Date', 'Home', 'Away', 'HomeGoals', 'AwayGoals', 'Result', 'Home_PPG_Before', 'Away_PPG_Before', 'Home_GF_PerGame_Before', 'Away_GF_PerGame_Before', 'Home_GA_PerGame_Before', 'Away_GA_PerGame_Before', 'Home_Last5_PPG', 'Away_Last5_PPG', 'Home_Rest_Days', 'Away_Rest_Days', 'PPG_Difference', 'GF_PerGame_Difference', 'GA_PerGame_Difference', 'Last5_PPG_Difference', 'Rest_Difference']

First 15 matches:
 Season  Wk       Date            Home            Away  HomeGoals  AwayGoals Result  Home_PPG_Before  Away_PPG_Before  Home_GF_PerGame_Before  Away_GF_PerGame_Before  Home_GA_PerGame_Before  Away_GA_PerGame_Before  Home_Last5_PPG  Away_Last5_PPG  Home_Rest_Days  Away_Rest_Days  PPG_Difference  GF_PerGame_Difference  GA_PerGame_Difference  Last5_PPG_Difference  Rest_Difference
   2022   1 2021-08-13       Brentford         Arsenal          2          0      H              NaN              NaN                     NaN                     NaN                     NaN                     NaN             NaN             NaN             NaN             NaN             NaN                    NaN                    NaN                   NaN              NaN
   2022   1 2021-08-14  Manchester Utd    Leeds United          5          1      H              NaN              NaN                     NaN                     NaN                     NaN                     NaN             NaN             NaN             NaN             NaN             NaN                    NaN                    NaN                   NaN              NaN
   2022   1 2021-08-14  Leicester City          Wolves          1          0      H              NaN              NaN                     NaN                     NaN                     NaN                     NaN             NaN             NaN             NaN             NaN             NaN                    NaN                    NaN                   NaN              NaN
   2022   1 2021-08-14         Burnley        Brighton          1          2      A              NaN              NaN                     NaN                     NaN                     NaN                     NaN             NaN             NaN             NaN             NaN             NaN                    NaN                    NaN                   NaN              NaN
   2022   1 2021-08-14         Chelsea  Crystal Palace          3          0      H              NaN              NaN                     NaN                     NaN                     NaN                     NaN             NaN             NaN             NaN             NaN             NaN                    NaN                    NaN                   NaN              NaN
   2022   1 2021-08-14         Watford     Aston Villa          3          2      H              NaN              NaN                     NaN                     NaN                     NaN                     NaN             NaN             NaN             NaN             NaN             NaN                    NaN                    NaN                   NaN              NaN
   2022   1 2021-08-14         Everton     Southampton          3          1      H              NaN              NaN                     NaN                     NaN                     NaN                     NaN             NaN             NaN             NaN             NaN             NaN                    NaN                    NaN                   NaN              NaN
   2022   1 2021-08-14    Norwich City       Liverpool          0          3      A              NaN              NaN                     NaN                     NaN                     NaN                     NaN             NaN             NaN             NaN             NaN             NaN                    NaN                    NaN                   NaN              NaN
   2022   1 2021-08-15       Newcastle        West Ham          2          4      A              NaN              NaN                     NaN                     NaN                     NaN                     NaN             NaN             NaN             NaN             NaN             NaN                    NaN                    NaN                   NaN              NaN
   2022   1 2021-08-15       Tottenham Manchester City          1          0      H              NaN              NaN                     NaN                     NaN                     NaN                     NaN             NaN             NaN             NaN             NaN             NaN                    NaN                    NaN                   NaN              NaN
   2022   2 2021-08-21       Liverpool         Burnley          2          0      H              3.0              0.0                     3.0                     1.0                     0.0                     2.0             3.0             0.0             7.0             7.0             3.0                    2.0                   -2.0                   3.0              0.0
   2022   2 2021-08-21     Aston Villa       Newcastle          2          0      H              0.0              0.0                     2.0                     2.0                     3.0                     4.0             0.0             0.0             7.0             6.0             0.0                    0.0                   -1.0                   0.0              1.0
   2022   2 2021-08-21 Manchester City    Norwich City          5          0      H              0.0              0.0                     0.0                     0.0                     1.0                     3.0             0.0             0.0             6.0             7.0             0.0                    0.0                   -2.0                   0.0             -1.0
   2022   2 2021-08-21    Leeds United         Everton          2          2      D              0.0              3.0                     1.0                     3.0                     5.0                     1.0             0.0             3.0             7.0             7.0            -3.0                   -2.0                    4.0                  -3.0              0.0
   2022   2 2021-08-21  Crystal Palace       Brentford          0          0      D              0.0              3.0                     0.0                     2.0                     3.0                     0.0             0.0             3.0             7.0             8.0            -3.0                   -2.0                    3.0                  -3.0             -1.0

Missing values:
Season                     0
Wk                         0
Date                       0
Home                       0
Away                       0
HomeGoals                  0
AwayGoals                  0
Result                     0
Home_PPG_Before           15
Away_PPG_Before           12
Home_GF_PerGame_Before    15
Away_GF_PerGame_Before    12
Home_GA_PerGame_Before    15
Away_GA_PerGame_Before    12
Home_Last5_PPG            15
Away_Last5_PPG            12
Home_Rest_Days            15
Away_Rest_Days            12
PPG_Difference            17
GF_PerGame_Difference     17
GA_PerGame_Difference     17
Last5_PPG_Difference      17
Rest_Difference           17
dtype: int64

In [4]:
print("fixtures_all:", type(fixtures_all), fixtures_all.shape)
print("feature_df:", type(feature_df), feature_df.shape)

fixtures_all: <class 'pandas.DataFrame'> (1900, 9)

NameError: name 'feature_df' is not defined

In [5]:
print("DataFrames currently in memory:")

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        print(f"{name}: {obj.shape}")

DataFrames currently in memory:
df: (1900, 9)
goals: (380, 2)
fixtures_all: (1900, 9)
fixture_features: (1900, 23)

In [6]:
# ============================================================
# STEP 3 — CROSS-SEASON TEAM STRENGTH RATINGS
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("BUILDING CROSS-SEASON TEAM RATINGS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Start with a copy of our existing feature dataset
# ------------------------------------------------------------

fixture_features = fixture_features.copy()

# Make sure matches are chronologically ordered
fixture_features = fixture_features.sort_values(
    ["Season", "Date"]
).reset_index(drop=True)


# ------------------------------------------------------------
# 2. Calculate each team's season PPG
# ------------------------------------------------------------

team_season_stats = {}

for season in sorted(fixture_features["Season"].unique()):

    season_df = fixture_features[
        fixture_features["Season"] == season
    ].copy()

    teams = set(
        season_df["Home"].unique()
    ).union(
        set(season_df["Away"].unique())
    )

    season_stats = {}

    for team in teams:

        home_matches = season_df[
            season_df["Home"] == team
        ]

        away_matches = season_df[
            season_df["Away"] == team
        ]

        # Points earned
        home_points = (
            (home_matches["HomeGoals"] > home_matches["AwayGoals"]) * 3
            + (home_matches["HomeGoals"] == home_matches["AwayGoals"]) * 1
        ).sum()

        away_points = (
            (away_matches["AwayGoals"] > away_matches["HomeGoals"]) * 3
            + (away_matches["AwayGoals"] == away_matches["HomeGoals"]) * 1
        ).sum()

        total_matches = len(home_matches) + len(away_matches)

        if total_matches > 0:
            ppg = (home_points + away_points) / total_matches
        else:
            ppg = np.nan

        season_stats[team] = ppg

    team_season_stats[season] = season_stats


# ------------------------------------------------------------
# 3. Calculate league-average PPG
# ------------------------------------------------------------

all_ppg = []

for season in team_season_stats:

    all_ppg.extend(
        team_season_stats[season].values()
    )

league_mean_ppg = np.nanmean(all_ppg)

print("\nLeague mean PPG:", round(league_mean_ppg, 3))


# ------------------------------------------------------------
# 4. Create carried-over ratings
#
# We shrink previous-season PPG toward the league mean.
#
# 75% previous strength
# 25% regression toward league average
# ------------------------------------------------------------

SHRINKAGE = 0.25

team_start_rating = {}


for season in sorted(fixture_features["Season"].unique()):

    if season == min(fixture_features["Season"].unique()):

        # First season has no previous season available
        team_start_rating[season] = {}

        continue

    previous_season = season - 1

    previous_stats = team_season_stats.get(
        previous_season,
        {}
    )

    current_start = {}

    for team, previous_ppg in previous_stats.items():

        if pd.isna(previous_ppg):
            rating = league_mean_ppg

        else:
            rating = (
                (1 - SHRINKAGE) * previous_ppg
                + SHRINKAGE * league_mean_ppg
            )

        current_start[team] = rating

    team_start_rating[season] = current_start


# ------------------------------------------------------------
# 5. Add starting ratings to every fixture
# ------------------------------------------------------------

fixture_features["Home_Carryover_Rating"] = np.nan
fixture_features["Away_Carryover_Rating"] = np.nan


for idx, row in fixture_features.iterrows():

    season = row["Season"]

    home = row["Home"]
    away = row["Away"]

    ratings = team_start_rating.get(
        season,
        {}
    )

    fixture_features.at[
        idx,
        "Home_Carryover_Rating"
    ] = ratings.get(
        home,
        league_mean_ppg
    )

    fixture_features.at[
        idx,
        "Away_Carryover_Rating"
    ] = ratings.get(
        away,
        league_mean_ppg
    )


# ------------------------------------------------------------
# 6. Difference between starting strengths
# ------------------------------------------------------------

fixture_features["Carryover_Rating_Difference"] = (
    fixture_features["Home_Carryover_Rating"]
    -
    fixture_features["Away_Carryover_Rating"]
)


# ------------------------------------------------------------
# 7. Check results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CROSS-SEASON RATINGS CREATED")
print("=" * 70)

print(
    "\nNew columns:"
)

print(
    [
        "Home_Carryover_Rating",
        "Away_Carryover_Rating",
        "Carryover_Rating_Difference"
    ]
)


# ------------------------------------------------------------
# 8. Show GW1 of each season
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("GAMEWEEK 1 CHECK")
print("=" * 70)

gw1 = fixture_features[
    fixture_features["Wk"] == 1
][
    [
        "Season",
        "Home",
        "Away",
        "Home_Carryover_Rating",
        "Away_Carryover_Rating",
        "Carryover_Rating_Difference"
    ]
]

print(
    gw1.to_string(index=False)
)


# ------------------------------------------------------------
# 9. Missing values
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MISSING VALUES")
print("=" * 70)

print(
    fixture_features[
        [
            "Home_Carryover_Rating",
            "Away_Carryover_Rating",
            "Carryover_Rating_Difference"
        ]
    ].isna().sum()
)


# ------------------------------------------------------------
# 10. Final shape
# ------------------------------------------------------------

print("\nFinal feature dataset shape:")
print(fixture_features.shape)

======================================================================
BUILDING CROSS-SEASON TEAM RATINGS
======================================================================

League mean PPG: 1.381

======================================================================
CROSS-SEASON RATINGS CREATED
======================================================================

New columns:
['Home_Carryover_Rating', 'Away_Carryover_Rating', 'Carryover_Rating_Difference']

======================================================================
GAMEWEEK 1 CHECK
======================================================================
 Season             Home            Away  Home_Carryover_Rating  Away_Carryover_Rating  Carryover_Rating_Difference
   2022        Brentford         Arsenal               1.380526               1.380526                     0.000000
   2022   Manchester Utd    Leeds United               1.380526               1.380526                     0.000000
   2022   Leicester City          Wolves               1.380526               1.380526                     0.000000
   2022          Burnley        Brighton               1.380526               1.380526                     0.000000
   2022          Chelsea  Crystal Palace               1.380526               1.380526                     0.000000
   2022          Watford     Aston Villa               1.380526               1.380526                     0.000000
   2022          Everton     Southampton               1.380526               1.380526                     0.000000
   2022     Norwich City       Liverpool               1.380526               1.380526                     0.000000
   2022        Newcastle        West Ham               1.380526               1.380526                     0.000000
   2022        Tottenham Manchester City               1.380526               1.380526                     0.000000
   2023   Crystal Palace         Arsenal               1.292500               1.706974                    -0.414474
   2023           Fulham       Liverpool               1.380526               2.160921                    -0.780395
   2023        Tottenham     Southampton               1.746447               1.134605                     0.611842
   2023        Newcastle      Nottingham               1.312237               1.380526                    -0.068289
   2023     Leeds United          Wolves               1.095132               1.351711                    -0.256579
   2023      Bournemouth     Aston Villa               1.380526               1.233289                     0.147237
   2023          Everton         Chelsea               1.114868               1.805658                    -0.690789
   2023   Leicester City       Brentford               1.371447               1.253026                     0.118421
   2023   Manchester Utd        Brighton               1.489868               1.351711                     0.138158
   2023         West Ham Manchester City               1.450395               2.180658                    -0.730263
   2024          Burnley Manchester City               1.380526               2.101711                    -0.721184
   2024          Arsenal      Nottingham               2.003026               1.095132                     0.907895
   2024          Everton          Fulham               1.055658               1.371447                    -0.315789
   2024 Sheffield United  Crystal Palace               1.380526               1.233289                     0.147237
   2024         Brighton      Luton Town               1.568816               1.380526                     0.188289
   2024      Bournemouth        West Ham               1.114868               1.134605                    -0.019737
   2024        Newcastle     Aston Villa               1.746447               1.549079                     0.197368
   2024        Brentford       Tottenham               1.509605               1.529342                    -0.019737
   2024          Chelsea       Liverpool               1.213553               1.667500                    -0.453947
   2024   Manchester Utd          Wolves               1.825395               1.154342                     0.671053
   2025   Manchester Utd          Fulham               1.529342               1.272763                     0.256579
   2025     Ipswich Town       Liverpool               1.380526               1.963553                    -0.583026
   2025        Newcastle     Southampton               1.529342               1.380526                     0.148816
   2025       Nottingham     Bournemouth               1.055658               1.292500                    -0.236842
   2025          Everton        Brighton               1.292500               1.292500                     0.000000
   2025          Arsenal          Wolves               2.101711               1.253026                     0.848684
   2025         West Ham     Aston Villa               1.371447               1.687237                    -0.315789
   2025        Brentford  Crystal Palace               1.114868               1.312237                    -0.197368
   2025          Chelsea Manchester City               1.588553               2.141184                    -0.552632
   2025   Leicester City       Tottenham               1.380526               1.647763                    -0.267237
   2026        Liverpool     Bournemouth               2.003026               1.450395                     0.552632
   2026      Aston Villa       Newcastle               1.647763               1.647763                     0.000000
   2026         Brighton          Fulham               1.549079               1.410921                     0.138158
   2026        Tottenham         Burnley               1.095132               1.380526                    -0.285395
   2026       Sunderland        West Ham               1.380526               1.193816                     0.186711
   2026           Wolves Manchester City               1.174079               1.746447                    -0.572368
   2026          Chelsea  Crystal Palace               1.706974               1.391184                     0.315789
   2026       Nottingham       Brentford               1.628026               1.450395                     0.177632
   2026   Manchester Utd         Arsenal               1.174079               1.805658                    -0.631579
   2026     Leeds United         Everton               1.380526               1.292500                     0.088026

======================================================================
MISSING VALUES
======================================================================
Home_Carryover_Rating          0
Away_Carryover_Rating          0
Carryover_Rating_Difference    0
dtype: int64

Final feature dataset shape:
(1900, 26)

In [7]:
# ============================================================
# STEP 4 — PREPARE MATCH RESULT TARGET
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("PREPARING MATCH RESULT TARGET")
print("=" * 70)

# ------------------------------------------------------------
# 1. Confirm current dataset
# ------------------------------------------------------------

print("\nCurrent dataset:")
print("Shape:", fixture_features.shape)

# ------------------------------------------------------------
# 2. Create target
# ------------------------------------------------------------

fixture_ml = fixture_features.copy()

fixture_ml["Target"] = fixture_ml["Result"]

# ------------------------------------------------------------
# 3. Remove information that is only known after the match
# ------------------------------------------------------------

target_columns = [
    "HomeGoals",
    "AwayGoals",
    "Result"
]

fixture_ml = fixture_ml.drop(
    columns=target_columns
)

# ------------------------------------------------------------
# 4. Check target
# ------------------------------------------------------------

print("\nTarget distribution:")
print(
    fixture_ml["Target"]
    .value_counts()
    .sort_index()
)

print("\nTarget proportions:")
print(
    fixture_ml["Target"]
    .value_counts(normalize=True)
    .sort_index()
)

# ------------------------------------------------------------
# 5. Check missing values
# ------------------------------------------------------------

print("\nMissing values:")
print(
    fixture_ml.isna().sum()
    .sort_values(ascending=False)
)

# ------------------------------------------------------------
# 6. Check columns
# ------------------------------------------------------------

print("\nFinal modelling columns:")
for i, col in enumerate(fixture_ml.columns):
    print(f"{i:02d}: {col}")

# ------------------------------------------------------------
# 7. Dataset shape
# ------------------------------------------------------------

print("\nFinal modelling dataset shape:")
print(fixture_ml.shape)

# ------------------------------------------------------------
# 8. Preview
# ------------------------------------------------------------

print("\nFirst 10 rows:")
display(fixture_ml.head(10))

======================================================================
PREPARING MATCH RESULT TARGET
======================================================================

Current dataset:
Shape: (1900, 26)

Target distribution:
Target
A    607
D    454
H    839
Name: count, dtype: int64

Target proportions:
Target
A    0.319474
D    0.238947
H    0.441579
Name: proportion, dtype: float64

Missing values:
GA_PerGame_Difference          17
Last5_PPG_Difference           17
GF_PerGame_Difference          17
PPG_Difference                 17
Rest_Difference                17
Home_Rest_Days                 15
Home_Last5_PPG                 15
Home_GA_PerGame_Before         15
Home_GF_PerGame_Before         15
Home_PPG_Before                15
Away_GF_PerGame_Before         12
Away_GA_PerGame_Before         12
Away_PPG_Before                12
Away_Rest_Days                 12
Away_Last5_PPG                 12
Home_Carryover_Rating           0
Away_Carryover_Rating           0
Carryover_Rating_Difference     0
Season                          0
Wk                              0
Away                            0
Home                            0
Date                            0
Target                          0
dtype: int64

Final modelling columns:
00: Season
01: Wk
02: Date
03: Home
04: Away
05: Home_PPG_Before
06: Away_PPG_Before
07: Home_GF_PerGame_Before
08: Away_GF_PerGame_Before
09: Home_GA_PerGame_Before
10: Away_GA_PerGame_Before
11: Home_Last5_PPG
12: Away_Last5_PPG
13: Home_Rest_Days
14: Away_Rest_Days
15: PPG_Difference
16: GF_PerGame_Difference
17: GA_PerGame_Difference
18: Last5_PPG_Difference
19: Rest_Difference
20: Home_Carryover_Rating
21: Away_Carryover_Rating
22: Carryover_Rating_Difference
23: Target

Final modelling dataset shape:
(1900, 24)

First 10 rows:

,Season,Wk,Date,Home,Away,Home_PPG_Before,Away_PPG_Before,Home_GF_PerGame_Before,Away_GF_PerGame_Before,Home_GA_PerGame_Before,...,Away_Rest_Days,PPG_Difference,GF_PerGame_Difference,GA_PerGame_Difference,Last5_PPG_Difference,Rest_Difference,Home_Carryover_Rating,Away_Carryover_Rating,Carryover_Rating_Difference,Target
0,2022,1,2021-08-13,Brentford,Arsenal,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.0,H
1,2022,1,2021-08-14,Manchester Utd,Leeds United,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.0,H
2,2022,1,2021-08-14,Leicester City,Wolves,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.0,H
3,2022,1,2021-08-14,Burnley,Brighton,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.0,A
4,2022,1,2021-08-14,Chelsea,Crystal Palace,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.0,H
5,2022,1,2021-08-14,Watford,Aston Villa,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.0,H
6,2022,1,2021-08-14,Everton,Southampton,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.0,H
7,2022,1,2021-08-14,Norwich City,Liverpool,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.0,A
8,2022,1,2021-08-15,Newcastle,West Ham,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.0,A
9,2022,1,2021-08-15,Tottenham,Manchester City,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.0,H

In [8]:
# ============================================================
# STEP 5 — INVESTIGATE MISSING PRE-MATCH FEATURES
# ============================================================

print("=" * 70)
print("INVESTIGATING MISSING VALUES")
print("=" * 70)

# ------------------------------------------------------------
# 1. Missing values by column
# ------------------------------------------------------------

missing = (
    fixture_ml.isna()
    .sum()
    .sort_values(ascending=False)
)

print("\nMissing values by column:")
print(missing[missing > 0])


# ------------------------------------------------------------
# 2. Show matches containing missing values
# ------------------------------------------------------------

missing_rows = fixture_ml[
    fixture_ml.isna().any(axis=1)
].copy()

print("\nNumber of matches containing missing values:")
print(len(missing_rows))

print("\nSeasons containing missing values:")
print(
    missing_rows["Season"]
    .value_counts()
    .sort_index()
)


# ------------------------------------------------------------
# 3. Gameweeks containing missing values
# ------------------------------------------------------------

print("\nGameweeks containing missing values:")
print(
    missing_rows["Wk"]
    .value_counts()
    .sort_index()
)


# ------------------------------------------------------------
# 4. Display the affected matches
# ------------------------------------------------------------

display(
    missing_rows[
        [
            "Season",
            "Wk",
            "Date",
            "Home",
            "Away",
            "Home_PPG_Before",
            "Away_PPG_Before",
            "Home_GF_PerGame_Before",
            "Away_GF_PerGame_Before",
            "Home_GA_PerGame_Before",
            "Away_GA_PerGame_Before",
            "Home_Last5_PPG",
            "Away_Last5_PPG",
            "Home_Rest_Days",
            "Away_Rest_Days",
            "PPG_Difference",
            "GF_PerGame_Difference",
            "GA_PerGame_Difference",
            "Last5_PPG_Difference",
            "Rest_Difference",
            "Home_Carryover_Rating",
            "Away_Carryover_Rating",
            "Carryover_Rating_Difference",
            "Target"
        ]
    ]
)

======================================================================
INVESTIGATING MISSING VALUES
======================================================================

Missing values by column:
GA_PerGame_Difference     17
Last5_PPG_Difference      17
GF_PerGame_Difference     17
PPG_Difference            17
Rest_Difference           17
Home_Rest_Days            15
Home_Last5_PPG            15
Home_GA_PerGame_Before    15
Home_GF_PerGame_Before    15
Home_PPG_Before           15
Away_GF_PerGame_Before    12
Away_GA_PerGame_Before    12
Away_PPG_Before           12
Away_Rest_Days            12
Away_Last5_PPG            12
dtype: int64

Number of matches containing missing values:
17

Seasons containing missing values:
Season
2022    10
2023     3
2024     2
2025     1
2026     1
Name: count, dtype: int64

Gameweeks containing missing values:
Wk
1    17
Name: count, dtype: int64

,Season,Wk,Date,Home,Away,Home_PPG_Before,Away_PPG_Before,Home_GF_PerGame_Before,Away_GF_PerGame_Before,Home_GA_PerGame_Before,...,Away_Rest_Days,PPG_Difference,GF_PerGame_Difference,GA_PerGame_Difference,Last5_PPG_Difference,Rest_Difference,Home_Carryover_Rating,Away_Carryover_Rating,Carryover_Rating_Difference,Target
0,2022,1,2021-08-13,Brentford,Arsenal,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.000000,H
1,2022,1,2021-08-14,Manchester Utd,Leeds United,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.000000,H
2,2022,1,2021-08-14,Leicester City,Wolves,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.000000,H
3,2022,1,2021-08-14,Burnley,Brighton,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.000000,A
4,2022,1,2021-08-14,Chelsea,Crystal Palace,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.000000,H
5,2022,1,2021-08-14,Watford,Aston Villa,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.000000,H
6,2022,1,2021-08-14,Everton,Southampton,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.000000,H
7,2022,1,2021-08-14,Norwich City,Liverpool,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.000000,A
8,2022,1,2021-08-15,Newcastle,West Ham,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.000000,A
9,2022,1,2021-08-15,Tottenham,Manchester City,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.380526,1.380526,0.000000,H
381,2023,1,2022-08-06,Fulham,Liverpool,NaN,2.421053,NaN,2.473684,NaN,...,76.0,NaN,NaN,NaN,NaN,NaN,1.380526,2.160921,-0.780395,D
383,2023,1,2022-08-06,Newcastle,Nottingham,1.289474,NaN,1.157895,NaN,1.631579,...,NaN,NaN,NaN,NaN,NaN,NaN,1.312237,1.380526,-0.068289,H
385,2023,1,2022-08-06,Bournemouth,Aston Villa,NaN,1.184211,NaN,1.368421,NaN,...,76.0,NaN,NaN,NaN,NaN,NaN,1.380526,1.233289,0.147237,H
763,2024,1,2023-08-12,Sheffield United,Crystal Palace,NaN,1.223684,NaN,1.184211,NaN,...,76.0,NaN,NaN,NaN,NaN,NaN,1.380526,1.233289,0.147237,A
764,2024,1,2023-08-12,Brighton,Luton Town,1.486842,NaN,1.500000,NaN,1.276316,...,NaN,NaN,NaN,NaN,NaN,NaN,1.568816,1.380526,0.188289,H
1141,2025,1,2024-08-17,Ipswich Town,Liverpool,NaN,2.114035,NaN,2.236842,NaN,...,90.0,NaN,NaN,NaN,NaN,NaN,1.380526,1.963553,-0.583026,A
1524,2026,1,2025-08-16,Sunderland,West Ham,NaN,1.256579,NaN,1.368421,NaN,...,83.0,NaN,NaN,NaN,NaN,NaN,1.380526,1.193816,0.186711,H

In [9]:
# ============================================================
# STEP 6 — VALIDATE CROSS-SEASON CARRYOVER RATINGS
# ============================================================

print("=" * 70)
print("VALIDATING CROSS-SEASON TEAM RATINGS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Get Gameweek 1
# ------------------------------------------------------------

gw1 = fixture_ml[
    fixture_ml["Wk"] == 1
].copy()

print("\nGameweek 1 matches:")
print(len(gw1))


# ------------------------------------------------------------
# 2. Display all Gameweek 1 carryover ratings
# ------------------------------------------------------------

print("\nGameweek 1 team ratings:")

display(
    gw1[
        [
            "Season",
            "Home",
            "Away",
            "Home_Carryover_Rating",
            "Away_Carryover_Rating",
            "Carryover_Rating_Difference",
            "Target"
        ]
    ]
)


# ------------------------------------------------------------
# 3. Find teams that appear in multiple seasons
# ------------------------------------------------------------

all_teams = sorted(
    set(fixture_ml["Home"])
    | set(fixture_ml["Away"])
)

print("\nTotal unique team names:", len(all_teams))


# ------------------------------------------------------------
# 4. Carryover rating statistics
# ------------------------------------------------------------

print("\nCarryover rating statistics:")

print(
    fixture_ml[
        [
            "Home_Carryover_Rating",
            "Away_Carryover_Rating",
            "Carryover_Rating_Difference"
        ]
    ].describe()
)


# ------------------------------------------------------------
# 5. Check teams with league-mean rating
# ------------------------------------------------------------

league_mean = (
    fixture_ml["Home_Carryover_Rating"]
    .mean()
)

print("\nApproximate league-mean rating:")
print(league_mean)

print("\nGameweek 1 teams at/near league mean:")

gw1_mean = gw1[
    (
        np.isclose(
            gw1["Home_Carryover_Rating"],
            league_mean,
            atol=1e-6
        )
    )
    |
    (
        np.isclose(
            gw1["Away_Carryover_Rating"],
            league_mean,
            atol=1e-6
        )
    )
]

display(
    gw1_mean[
        [
            "Season",
            "Home",
            "Away",
            "Home_Carryover_Rating",
            "Away_Carryover_Rating"
        ]
    ]
)

======================================================================
VALIDATING CROSS-SEASON TEAM RATINGS
======================================================================

Gameweek 1 matches:
50

Gameweek 1 team ratings:

,Season,Home,Away,Home_Carryover_Rating,Away_Carryover_Rating,Carryover_Rating_Difference,Target
0,2022,Brentford,Arsenal,1.380526,1.380526,0.000000,H
1,2022,Manchester Utd,Leeds United,1.380526,1.380526,0.000000,H
2,2022,Leicester City,Wolves,1.380526,1.380526,0.000000,H
3,2022,Burnley,Brighton,1.380526,1.380526,0.000000,A
4,2022,Chelsea,Crystal Palace,1.380526,1.380526,0.000000,H
5,2022,Watford,Aston Villa,1.380526,1.380526,0.000000,H
6,2022,Everton,Southampton,1.380526,1.380526,0.000000,H
7,2022,Norwich City,Liverpool,1.380526,1.380526,0.000000,A
8,2022,Newcastle,West Ham,1.380526,1.380526,0.000000,A
9,2022,Tottenham,Manchester City,1.380526,1.380526,0.000000,H
380,2023,Crystal Palace,Arsenal,1.292500,1.706974,-0.414474,A
381,2023,Fulham,Liverpool,1.380526,2.160921,-0.780395,D
382,2023,Tottenham,Southampton,1.746447,1.134605,0.611842,H
383,2023,Newcastle,Nottingham,1.312237,1.380526,-0.068289,H
384,2023,Leeds United,Wolves,1.095132,1.351711,-0.256579,H
385,2023,Bournemouth,Aston Villa,1.380526,1.233289,0.147237,H
386,2023,Everton,Chelsea,1.114868,1.805658,-0.690789,A
387,2023,Leicester City,Brentford,1.371447,1.253026,0.118421,D
388,2023,Manchester Utd,Brighton,1.489868,1.351711,0.138158,A
389,2023,West Ham,Manchester City,1.450395,2.180658,-0.730263,A
760,2024,Burnley,Manchester City,1.380526,2.101711,-0.721184,A
761,2024,Arsenal,Nottingham,2.003026,1.095132,0.907895,H
762,2024,Everton,Fulham,1.055658,1.371447,-0.315789,A
763,2024,Sheffield United,Crystal Palace,1.380526,1.233289,0.147237,A
764,2024,Brighton,Luton Town,1.568816,1.380526,0.188289,H
765,2024,Bournemouth,West Ham,1.114868,1.134605,-0.019737,D
766,2024,Newcastle,Aston Villa,1.746447,1.549079,0.197368,H
767,2024,Brentford,Tottenham,1.509605,1.529342,-0.019737,D
768,2024,Chelsea,Liverpool,1.213553,1.667500,-0.453947,D
769,2024,Manchester Utd,Wolves,1.825395,1.154342,0.671053,H
1140,2025,Manchester Utd,Fulham,1.529342,1.272763,0.256579,H
1141,2025,Ipswich Town,Liverpool,1.380526,1.963553,-0.583026,A
1142,2025,Newcastle,Southampton,1.529342,1.380526,0.148816,H
1143,2025,Nottingham,Bournemouth,1.055658,1.292500,-0.236842,D
1144,2025,Everton,Brighton,1.292500,1.292500,0.000000,A
1145,2025,Arsenal,Wolves,2.101711,1.253026,0.848684,H
1146,2025,West Ham,Aston Villa,1.371447,1.687237,-0.315789,A
1147,2025,Brentford,Crystal Palace,1.114868,1.312237,-0.197368,H
1148,2025,Chelsea,Manchester City,1.588553,2.141184,-0.552632,A
1149,2025,Leicester City,Tottenham,1.380526,1.647763,-0.267237,D
1520,2026,Liverpool,Bournemouth,2.003026,1.450395,0.552632,H
1521,2026,Aston Villa,Newcastle,1.647763,1.647763,0.000000,D
1522,2026,Brighton,Fulham,1.549079,1.410921,0.138158,D
1523,2026,Tottenham,Burnley,1.095132,1.380526,-0.285395,H
1524,2026,Sunderland,West Ham,1.380526,1.193816,0.186711,H
1525,2026,Wolves,Manchester City,1.174079,1.746447,-0.572368,A
1526,2026,Chelsea,Crystal Palace,1.706974,1.391184,0.315789,D
1527,2026,Nottingham,Brentford,1.628026,1.450395,0.177632,H
1528,2026,Manchester Utd,Arsenal,1.174079,1.805658,-0.631579,A
1529,2026,Leeds United,Everton,1.380526,1.292500,0.088026,H

Total unique team names: 27

Carryover rating statistics:
       Home_Carryover_Rating  Away_Carryover_Rating  \
count            1900.000000            1900.000000
mean                1.449155               1.449155
std                 0.255197               0.255197
min                 1.055658               1.055658
25%                 1.307303               1.307303
50%                 1.380526               1.380526
75%                 1.549079               1.549079
max                 2.180658               2.180658

       Carryover_Rating_Difference
count                 1.900000e+03
mean                  1.986715e-18
std                   3.666038e-01
min                  -1.085526e+00
25%                  -1.973684e-01
50%                   0.000000e+00
75%                   1.973684e-01
max                   1.085526e+00

Approximate league-mean rating:
1.449155263157895

Gameweek 1 teams at/near league mean:

Empty DataFrame
Columns: [Season, Home, Away, Home_Carryover_Rating, Away_Carryover_Rating]
Index: []